<?php
require_once(getabspath("classes/cipherer.php"));



$tdataaio_reporting_dashboard = array();
$tdataaio_reporting_dashboard[".ShortName"] = "aio_reporting_dashboard";

$tdataaio_reporting_dashboard[".pagesByType"] = my_json_decode( "{\"dashboard\":[\"dashboard\"]}" );
$tdataaio_reporting_dashboard[".originalPagesByType"] = $tdataaio_reporting_dashboard[".pagesByType"];
$tdataaio_reporting_dashboard[".pages"] = types2pages( my_json_decode( "{\"dashboard\":[\"dashboard\"]}" ) );
$tdataaio_reporting_dashboard[".originalPages"] = $tdataaio_reporting_dashboard[".pages"];
$tdataaio_reporting_dashboard[".defaultPages"] = my_json_decode( "{\"dashboard\":\"dashboard\"}" );
$tdataaio_reporting_dashboard[".originalDefaultPages"] = $tdataaio_reporting_dashboard[".defaultPages"];


//	field labels
$fieldLabelsaio_reporting_dashboard = array();
$pageTitlesaio_reporting_dashboard = array();

if(mlang_getcurrentlang()=="English")
{
	$fieldLabelsaio_reporting_dashboard["English"] = array();
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_CandidateID"] = "Candidate ID";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_StudentID"] = "Student ID";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_First_Name"] = "First Name";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Middle_Name"] = "Middle Name";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Last_Name"] = "Last Name";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Sex"] = "Sex";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_DOB"] = "DOB";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Region"] = "Region";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_City"] = "City";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Sub_City"] = "Sub City";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Zone"] = "Zone";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_House_No"] = "House No";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Phone_Number"] = "Phone Number";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Phone_Number_Alternate"] = "Phone Number Alternate";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Email_Address"] = "Email Address";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Disability_Status"] = "Disability Status";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Disability_Type"] = "Disability Type";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Disability_Type_Other"] = "Disability Type Other";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Institution_Type"] = "Institution Type";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Institution_Name"] = "Institution Name";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Education_Level"] = "Education Level";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Department"] = "Department";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Minor"] = "Minor";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Major"] = "Major";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Enrollement_Type"] = "Enrollement Type";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Skills"] = "Skills";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Languages"] = "Languages";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_English_Proficiency_Level"] = "English Proficiency Level";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Industry_Specific_Skills"] = "Industry Specific Skills";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_IT_Related_Skills"] = "IT Related Skills";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Certifications"] = "Certifications";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Year_of_graduation"] = "Year Of Graduation";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Field_Of_Study"] = "Field Of Study";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_GPA"] = "GPA";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Intervention"] = "Intervention";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Campaign"] = "Campaign";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Attend_Employability_Skill"] = "Attend Employability Skill";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_DAAP_enrolled_1st_Round"] = "DAAP Enrolled 1st Round";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_DAAP_Completed"] = "DAAP Completed";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_DAAP_Completed_Courses"] = "DAAP Completed Courses";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Job_Fair_Clinic"] = "Job Fair Clinic";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Job_Fair"] = "Job Fair";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Exit_Exam_Score"] = "Exit Exam Score";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Exit_Exam_Status"] = "Exit Exam Status";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_DAAP_enrolled_2nd_Round"] = "DAAP Enrolled 2nd Round";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Upload_on_Tracker"] = "Upload On Tracker";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Work_Experience"] = "Work Experience";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Joined_Dereja_Services"] = "Joined Dereja Services";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Dereja_Services"] = "Dereja Services";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Dereja_Training_Services"] = "Dereja Training Services";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Dereja_Event_Services"] = "Dereja Event Services";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Dereja_web_profile_completion"] = "Dereja Web Profile Completion";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Dereja_Information_Source"] = "Dereja Information Source";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Employment_Status"] = "Employment Status";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Employment_Company"] = "Employment Company";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Employment_Position"] = "Employment Position";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_Remark"] = "Remark";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_EventID"] = "Event ID";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_CandidateID"] = "Candidate ID";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_StudentID"] = "Student ID";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Event_Start_Date"] = "Event Start Date";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Event_End_Date"] = "Event End Date";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_First_Name"] = "First Name";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Middle_Name"] = "Middle Name";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Last_Name"] = "Last Name";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Full_Name"] = "Full Name";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Sex"] = "Sex";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Phone"] = "Phone";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Email"] = "Email";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Disability_Status"] = "Disability Status";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Disability_Type"] = "Disability Type";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Disability_Type_Other"] = "Disability Type Other";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Participant_Type"] = "Participant Type";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Participant_Field_of_Study"] = "Participant Field Of Study";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Participant_Organization_Type"] = "Participant Organization Type";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Participant_Organization_Name"] = "Participant Organization Name";
	$fieldLabelsaio_reporting_dashboard["English"]["event_participants_Participant_Home_Address"] = "Participant Home Address";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_TrainingID"] = "Training ID";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_CandidateID"] = "Candidate ID";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_StudentID"] = "Student ID";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_Organizer"] = "Training Organizer";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_Type"] = "Training Type";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Program_Area"] = "Program Area";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_City_Town"] = "Training City Town";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_Venue"] = "Training Venue";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_Start_Date"] = "Training Start Date";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Training_End_Date"] = "Training End Date";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_First_Name"] = "First Name";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Middle_Name"] = "Middle Name";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Last_Name"] = "Last Name";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Full_Name"] = "Full Name";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Sex"] = "Sex";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Email"] = "Email";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Phone"] = "Phone";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Disability_Status"] = "Disability Status";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Disability_Type"] = "Disability Type";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Disability_Type_Other"] = "Disability Type Other";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Participant_Profession"] = "Participant Profession";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Participant_Field_of_Study"] = "Participant Field Of Study";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Participant_Facility_Organization_Type"] = "Participant Facility Organization Type";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Participant_Organization_Name"] = "Participant Organization Name";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Participants_Home_Address"] = "Participants Home Address";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_PreTest_Score"] = "PreTest Score";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Skill_Test"] = "Skill Test";
	$fieldLabelsaio_reporting_dashboard["English"]["training_participants_Post_Test_Score"] = "Post Test Score";
	$fieldLabelsaio_reporting_dashboard["English"]["regions_RegionID"] = "Region ID";
	$fieldLabelsaio_reporting_dashboard["English"]["regions_RegionName"] = "Region Name";
	$fieldLabelsaio_reporting_dashboard["English"]["regions_Lat"] = "Lat";
	$fieldLabelsaio_reporting_dashboard["English"]["regions_Lng"] = "Lng";
	$fieldLabelsaio_reporting_dashboard["English"]["candidates_by_sex_Sex"] = "Sex";
}

/*
//	search fields
$tdataaio_reporting_dashboard[".searchFields"] = array();
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"CandidateID" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_CandidateID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"StudentID" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_StudentID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"First_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_First_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Middle_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Middle_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Last_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Last_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Sex" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Sex"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"DOB" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_DOB"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Region" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Region"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"City" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_City"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Sub_City" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Sub_City"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Zone" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Zone"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"House_No" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_House_No"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Phone_Number" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Phone_Number"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Phone_Number_Alternate" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Phone_Number_Alternate"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Email_Address" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Email_Address"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Disability_Status" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Disability_Status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Disability_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Disability_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Disability_Type_Other" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Disability_Type_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Institution_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Institution_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Institution_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Institution_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Education_Level" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Education_Level"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Department" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Department"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Minor" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Minor"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Major" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Major"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Enrollement_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Enrollement_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Skills" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Skills"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Languages" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Languages"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"English_Proficiency_Level" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_English_Proficiency_Level"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Industry_Specific_Skills" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Industry_Specific_Skills"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"IT_Related_Skills" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_IT_Related_Skills"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Certifications" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Certifications"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Year_of_graduation" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Year_of_graduation"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Field_Of_Study" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Field_Of_Study"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"GPA" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_GPA"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Intervention" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Intervention"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Campaign" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Campaign"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Attend_Employability_Skill" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Attend_Employability_Skill"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"DAAP_enrolled_1st Round" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_DAAP_enrolled_1st_Round"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"DAAP_Completed" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_DAAP_Completed"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"DAAP_Completed_Courses" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_DAAP_Completed_Courses"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Job_Fair_Clinic" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Job_Fair_Clinic"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Job_Fair" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Job_Fair"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Exit_Exam_Score" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Exit_Exam_Score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Exit_Exam_Status" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Exit_Exam_Status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"DAAP_enrolled_2nd_Round" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_DAAP_enrolled_2nd_Round"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Upload_on_Tracker" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Upload_on_Tracker"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Work_Experience" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Work_Experience"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Joined_Dereja_Services" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Joined_Dereja_Services"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Dereja_Services" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Dereja_Services"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Dereja_Training_Services" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Dereja_Training_Services"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Dereja_Event_Services" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Dereja_Event_Services"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Dereja_web_profile_completion" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Dereja_web_profile_completion"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Dereja_Information_Source" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Dereja_Information_Source"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Employment_Status" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Employment_Status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Employment_Company" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Employment_Company"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Employment_Position" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Employment_Position"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates", "field"=>"Remark" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_Remark"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"EventID" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_EventID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"CandidateID" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_CandidateID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"StudentID" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_StudentID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Event_Start_Date" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Event_Start_Date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Event_End_Date" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Event_End_Date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"First_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_First_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Middle_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Middle_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Last_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Last_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Full_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Full_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Sex" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Sex"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Phone" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Phone"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Email" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Email"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Disability_Status" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Disability_Status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Disability_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Disability_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Disability_Type_Other" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Disability_Type_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Participant_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Participant_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Participant_Field_of_Study" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Participant_Field_of_Study"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Participant_Organization_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Participant_Organization_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Participant_Organization_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Participant_Organization_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"event_participants", "field"=>"Participant_Home_Address" );
$tdataaio_reporting_dashboard[".searchFields"]["event_participants_Participant_Home_Address"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"TrainingID" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_TrainingID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"CandidateID" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_CandidateID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"StudentID" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_StudentID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_Organizer" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_Organizer"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Program_Area" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Program_Area"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_City_Town" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_City_Town"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_Venue" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_Venue"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_Start_Date" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_Start_Date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Training_End_Date" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Training_End_Date"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"First_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_First_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Middle_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Middle_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Last_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Last_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Full_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Full_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Sex" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Sex"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Email" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Email"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Phone" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Phone"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Disability_Status" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Disability_Status"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Disability_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Disability_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Disability_Type_Other" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Disability_Type_Other"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Participant_Profession" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Participant_Profession"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Participant_Field_of_Study" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Participant_Field_of_Study"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Participant_Facility_Organization_Type" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Participant_Facility_Organization_Type"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Participant_Organization_Name" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Participant_Organization_Name"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Participants_Home_Address" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Participants_Home_Address"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"PreTest_Score" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_PreTest_Score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Skill_Test" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Skill_Test"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"training_participants", "field"=>"Post_Test_Score" );
$tdataaio_reporting_dashboard[".searchFields"]["training_participants_Post_Test_Score"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"regions", "field"=>"RegionID" );
$tdataaio_reporting_dashboard[".searchFields"]["regions_RegionID"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"regions", "field"=>"RegionName" );
$tdataaio_reporting_dashboard[".searchFields"]["regions_RegionName"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"regions", "field"=>"Lat" );
$tdataaio_reporting_dashboard[".searchFields"]["regions_Lat"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"regions", "field"=>"Lng" );
$tdataaio_reporting_dashboard[".searchFields"]["regions_Lng"] = $dashField;
$dashField = array();
$dashField[] = array( "table"=>"candidates_by_sex", "field"=>"Sex" );
$tdataaio_reporting_dashboard[".searchFields"]["candidates_by_sex_Sex"] = $dashField;

// all search fields
$tdataaio_reporting_dashboard[".allSearchFields"] = array();
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_CandidateID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_StudentID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_First_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Middle_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Last_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Sex";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_DOB";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Region";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_City";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Sub_City";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Zone";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_House_No";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Phone_Number";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Phone_Number_Alternate";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Email_Address";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Disability_Status";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Disability_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Disability_Type_Other";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Institution_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Institution_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Education_Level";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Department";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Minor";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Major";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Enrollement_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Skills";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Languages";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_English_Proficiency_Level";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Industry_Specific_Skills";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_IT_Related_Skills";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Certifications";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Year_of_graduation";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Field_Of_Study";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_GPA";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Intervention";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Campaign";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Attend_Employability_Skill";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_DAAP_enrolled_1st_Round";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_DAAP_Completed";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_DAAP_Completed_Courses";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Job_Fair_Clinic";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Job_Fair";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Exit_Exam_Score";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Exit_Exam_Status";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_DAAP_enrolled_2nd_Round";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Upload_on_Tracker";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Work_Experience";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Joined_Dereja_Services";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Dereja_Services";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Dereja_Training_Services";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Dereja_Event_Services";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Dereja_web_profile_completion";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Dereja_Information_Source";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Employment_Status";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Employment_Company";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Employment_Position";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_Remark";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_EventID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_CandidateID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_StudentID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Event_Start_Date";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Event_End_Date";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_First_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Middle_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Last_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Full_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Sex";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Phone";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Email";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Disability_Status";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Disability_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Disability_Type_Other";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Participant_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Participant_Field_of_Study";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Participant_Organization_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Participant_Organization_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "event_participants_Participant_Home_Address";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_TrainingID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_CandidateID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_StudentID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_Organizer";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Program_Area";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_City_Town";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_Venue";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_Start_Date";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Training_End_Date";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_First_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Middle_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Last_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Full_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Sex";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Email";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Phone";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Disability_Status";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Disability_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Disability_Type_Other";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Participant_Profession";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Participant_Field_of_Study";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Participant_Facility_Organization_Type";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Participant_Organization_Name";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Participants_Home_Address";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_PreTest_Score";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Skill_Test";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "training_participants_Post_Test_Score";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "regions_RegionID";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "regions_RegionName";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "regions_Lat";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "regions_Lng";
$tdataaio_reporting_dashboard[".allSearchFields"][] = "candidates_by_sex_Sex";

// good like search fields
$tdataaio_reporting_dashboard[".googleLikeFields"] = array();
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_CandidateID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_StudentID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_First_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Middle_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Last_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Sex";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_DOB";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Region";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_City";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Sub_City";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Zone";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_House_No";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Phone_Number";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Phone_Number_Alternate";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Email_Address";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Disability_Status";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Disability_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Disability_Type_Other";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Institution_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Institution_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Education_Level";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Department";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Minor";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Major";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Enrollement_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Skills";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Languages";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_English_Proficiency_Level";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Industry_Specific_Skills";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_IT_Related_Skills";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Certifications";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Year_of_graduation";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Field_Of_Study";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_GPA";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Intervention";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Campaign";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Attend_Employability_Skill";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_DAAP_enrolled_1st_Round";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_DAAP_Completed";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_DAAP_Completed_Courses";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Job_Fair_Clinic";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Job_Fair";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Exit_Exam_Score";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Exit_Exam_Status";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_DAAP_enrolled_2nd_Round";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Upload_on_Tracker";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Work_Experience";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Joined_Dereja_Services";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Dereja_Services";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Dereja_Training_Services";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Dereja_Event_Services";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Dereja_web_profile_completion";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Dereja_Information_Source";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Employment_Status";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Employment_Company";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Employment_Position";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "candidates_Remark";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_EventID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_CandidateID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_StudentID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Event_Start_Date";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Event_End_Date";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_First_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Middle_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Last_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Full_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Sex";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Phone";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Email";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Disability_Status";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Disability_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Disability_Type_Other";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Participant_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Participant_Field_of_Study";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Participant_Organization_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Participant_Organization_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "event_participants_Participant_Home_Address";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_TrainingID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_CandidateID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_StudentID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_Organizer";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Program_Area";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_City_Town";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_Venue";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_Start_Date";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Training_End_Date";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_First_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Middle_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Last_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Full_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Sex";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Email";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Phone";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Disability_Status";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Disability_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Disability_Type_Other";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Participant_Profession";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Participant_Field_of_Study";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Participant_Facility_Organization_Type";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Participant_Organization_Name";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Participants_Home_Address";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_PreTest_Score";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Skill_Test";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "training_participants_Post_Test_Score";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "regions_RegionID";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "regions_RegionName";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "regions_Lat";
$tdataaio_reporting_dashboard[".googleLikeFields"][] = "regions_Lng";
*/

/*
$tdataaio_reporting_dashboard[".dashElements"] = array();

	$dbelement = array( "elementName" => "candidates_grid", "table" => "candidates",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "event_participants_grid", "table" => "event_participants",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "training_participants_grid", "table" => "training_participants",
		 "pageName" => "","type" => 0);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
	

	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "regions_map", "table" => "regions",
		 "pageName" => "","type" => 6);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;
		$dbelement["zoom"] = "auto";
	$dbelement["addressF"] = "";
	$dbelement["latF"] = "";
	$dbelement["lonF"] = "";
	$dbelement["descF"] = "";
	$dbelement["mapMarkerCount"] = 50;
	$dbelement["isMarkerIconCustom"] = 0;
			$dbelement["updateMoved"] = true;

	$dbelement["isLocationMarkerIconCustom"] = 0;
	$dbelement["showCurrentLocation"] = 0;
	

	// Advanced map options
	

	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "candidates_search", "table" => "candidates",
		 "pageName" => "","type" => 4);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;


	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
	$dbelement = array( "elementName" => "candidates_by_sex_chart", "table" => "candidates_by_sex",
		 "pageName" => "","type" => 1);
	$dbelement["cellName"] = "";

		$dbelement["reload"] = 60;
		$dbelement["width"] = 800;
		$dbelement["height"] = 600;


	$tdataaio_reporting_dashboard[".dashElements"][] = $dbelement;
*/
$tdataaio_reporting_dashboard[".shortTableName"] = "aio_reporting_dashboard";
$tdataaio_reporting_dashboard[".entityType"] = 4;




$tdataaio_reporting_dashboard[".hasEvents"] = false;


$tdataaio_reporting_dashboard[".tableType"] = "dashboard";


	
$tdataaio_reporting_dashboard[".addPageEvents"] = false;

$tdataaio_reporting_dashboard[".isUseAjaxSuggest"] = true;

$tables_data["AIO_Reporting_Dashboard"]=&$tdataaio_reporting_dashboard;
$field_labels["AIO_Reporting_Dashboard"] = &$fieldLabelsaio_reporting_dashboard;
$page_titles["AIO_Reporting_Dashboard"] = &$pageTitlesaio_reporting_dashboard;

?>