<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_candidates  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeShowView"]=true;

		$this->events["BeforeShowList"]=true;

		$this->events["BeforeShowPrint"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		

// Place event code here.
global $strTableName;
$sql="select * from settings where tablename='".$strTableName."'";
$rs = CustomQuery($sql);
while ($data = db_fetch_array($rs)) {
	if ($data["visible"]!=1) {
		$pageObject->hideField($data["field"]);
	}
}
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		

// Place event code here.
global $strTableName;
$sql="select * from settings where tablename='".$strTableName."'";
$rs = CustomQuery($sql);
while ($data = db_fetch_array($rs)) {
	if ($data["visible"]!=1) {
		$pageObject->hideField($data["field"]);
	}
}
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		

// Place event code here.
global $strTableName;
$sql="select * from settings where tablename='".$strTableName."'";
$rs = CustomQuery($sql);
while ($data = db_fetch_array($rs)) {
	if ($data["visible"]!=1) {
		$pageObject->hideField($data["field"]);
	}
}
;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		

// Place event code here.
global $strTableName;
$sql="select * from settings where tablename='".$strTableName."'";
$rs = CustomQuery($sql);
while ($data = db_fetch_array($rs)) {
	if ($data["visible"]!=1) {
		$xt->assign($data["field"]."_fieldheadercolumn", false);
		$xt->assign($data["field"]."_fieldcolumn", false);
	}
}
;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowPrint(&$xt, &$templatefile, $pageObject)
{

		

// Place event code here.
global $strTableName;
$sql="select * from settings where tablename='".$strTableName."'";

$rs = CustomQuery($sql);
while ($data = db_fetch_array($rs)) {
	if ($data["visible"]!=1) {
		foreach( $xt->xt_vars["body"]["data"] as $page=>$pagedata ) {
			$xt->xt_vars["body"]["data"][$page][$data["field"]."_fieldheadercolumn"] = false;
			$xt->xt_vars["body"]["data"][$page][$data["field"]."_fieldcolumn"] = false;
		}
	}
}
;
} // function BeforeShowPrint

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>