<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_regions  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		
//addNotification("Region Added", "Region", "glyphicon-user", makePageLink(), "1440", "admin@merqconsultancy.org");
//addNotification( "New Region added: ".$values["RegionName"] , "New category", "fa-location", makePageLink( "regions", "view", $keys), "1440", "admin@merqconsultancy.org");  
addNotification( "New Region added: ".$values["RegionName"] , "New Region", "fa-location", makePageLink( "regions", "view", $keys));

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>