<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'snippet1' ),
'above-grid' => array( 'snippet2',
'total_questions',
'snippet3',
'end_message',
'snippet6',
'progressbar' ),
'below-grid' => array( 'prev',
'finish_button',
'save_for_later' ),
'grid' => array( 'questions_block' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'snippet1' => 'top',
'snippet2' => 'above-grid',
'total_questions' => 'above-grid',
'snippet3' => 'above-grid',
'end_message' => 'above-grid',
'snippet6' => 'above-grid',
'progressbar' => 'above-grid',
'prev' => 'below-grid',
'finish_button' => 'below-grid',
'save_for_later' => 'below-grid',
'questions_block' => 'grid' ),
'itemLocations' => array( 'questions_block' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'snippet' => array( 'snippet1',
'snippet2',
'snippet3',
'snippet6',
'progressbar',
'questions_block',
'finish_button',
'save_for_later',
'prev',
'total_questions',
'end_message' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'questions_block' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'snippet1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'snippet2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'total_questions' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'snippet3' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'end_message' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'snippet6' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'progressbar' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'prev',
'finish_button',
'save_for_later' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'questions_block' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'padding' => array( 'top' => '20px' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'snippet1' => array( 'eventId' => 'sv_title',
'label' => array( 'text' => 'sv_title',
'type' => 0 ),
'type' => 'snippet',
'font-size' => '26px',
'bold' => true ),
'snippet2' => array( 'eventId' => 'survey_description',
'label' => array( 'text' => 'survey_description',
'type' => 0 ),
'type' => 'snippet',
'font-size' => '12px' ),
'snippet3' => array( 'eventId' => 'survey_welcome',
'label' => array( 'text' => 'survey_welcome',
'type' => 0 ),
'type' => 'snippet',
'font-size' => '18px' ),
'snippet6' => array( 'eventId' => 'sv_message',
'label' => array( 'text' => 'sv_message',
'type' => 0 ),
'type' => 'snippet' ),
'progressbar' => array( 'eventId' => 'progreessbar',
'label' => array( 'text' => 'progreessbar',
'type' => 0 ),
'type' => 'snippet' ),
'questions_block' => array( 'eventId' => 'response_survey',
'label' => array( 'text' => 'response_survey',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  padding-left:15px;
  width:100% !important;
}' ),
'finish_button' => array( 'eventId' => 'next_submit',
'label' => array( 'text' => 'next-submit',
'type' => 0 ),
'type' => 'snippet' ),
'save_for_later' => array( 'eventId' => 'Save_for_later',
'label' => array( 'text' => 'Save for later',
'type' => 0 ),
'type' => 'snippet' ),
'prev' => array( 'eventId' => 'prev',
'label' => array( 'text' => 'prev',
'type' => 0 ),
'type' => 'snippet' ),
'total_questions' => array( 'eventId' => 'total_questions',
'label' => array( 'text' => 'total_questions',
'type' => 0 ),
'type' => 'snippet',
'font-size' => '14px' ),
'end_message' => array( 'eventId' => 'survey_end',
'label' => array( 'text' => 'survey_end',
'type' => 0 ),
'type' => 'snippet',
'font-size' => '20px' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>