<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'snippet' ),
'above-grid' => array( 'snippet1',
'snippet3',
'snippet2' ),
'below-grid' => array( 'custom_button' ),
'grid' => array( 'snippet4' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'snippet' => 'top',
'snippet1' => 'above-grid',
'snippet3' => 'above-grid',
'snippet2' => 'above-grid',
'custom_button' => 'below-grid',
'snippet4' => 'grid' ),
'itemLocations' => array( 'snippet4' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'custom_button' => array( 'custom_button' ),
'snippet' => array( 'snippet',
'snippet1',
'snippet2',
'snippet3',
'snippet4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'snippet4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'Back_to_survey_list1' ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Back_to_survey_list1' ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'snippet' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'snippet1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'snippet3' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'snippet2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'custom_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'snippet4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'custom_button' => array( 'eventId' => 'Back_to_survey_list1',
'label' => array( 'text' => 'Back to List',
'type' => 0 ),
'type' => 'custom_button' ),
'snippet' => array( 'type' => 'snippet',
'eventId' => 'sv_title',
'label' => array( 'text' => 'sv_title',
'type' => 0 ),
'bold' => true,
'font-size' => '26px' ),
'snippet1' => array( 'type' => 'snippet',
'eventId' => 'survey_description',
'label' => array( 'text' => 'survey_description',
'type' => 0 ),
'font-size' => '12px' ),
'snippet2' => array( 'type' => 'snippet',
'eventId' => 'survey_welcome',
'label' => array( 'text' => 'survey_welcome',
'type' => 0 ),
'font-size' => '18px' ),
'snippet3' => array( 'type' => 'snippet',
'eventId' => 'total_questions',
'label' => array( 'text' => 'total_questions',
'type' => 0 ),
'font-size' => '14px' ),
'snippet4' => array( 'type' => 'snippet',
'eventId' => 'survey_response_view',
'label' => array( 'text' => 'survey_response_view',
'type' => 0 ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  padding-left:15px;
  width:100% !important;
}' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>