<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pdf_formfields  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if($data["fieldsql"])
	$record["id_value"] = "<select class='form-control' id='sqlfield_".$data["id"]."' fieldid='".$data["id"]."'><option value='".$data["fieldsql"]."'>".$data["fieldsql"]."</option></select>";
else
	$record["id_value"] = "<select class='form-control' id='sqlfield_".$data["id"]."' fieldid='".$data["id"]."'><option value=''>".GetCustomlabel("please_select_text")."</option></select>";



;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		if(postvalue("a") == "savesqlfield"){
	DB::Update("pdf_formfields", array("fieldsql"=>postvalue("val")),array("id"=>postvalue("fieldid")));
	exit();
}
if(postvalue("a") == "getselect"){
	$rs = DB::Select("pdf_formfields", array("id"=>postvalue("fieldid")));
	$data = $rs->fetchAssoc();
	$formid = $data["formid"];

	$multif = postvalue("multifields");

	$selectpdf_sqlfields = "<option value=''>Please select...</option>";
	$rs = DB::Select("pdf_sqlfields", array("formid"=>$formid));
	while($mdata = $rs->fetchAssoc()){
		$s = "";
		$needAdd = true;
		if($data["fieldsql"] == $mdata["sqlfield"])
			$s = " selected";
		else{
			if($multif!="true"){
				$rs2 = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("pdf_formfields")." where ".addFieldWrappers("fieldsql")."='".$mdata["sqlfield"]."' and ".addFieldWrappers("formid")."=".$formid);
				$data2 = $rs2->fetchAssoc();
				if($data2["cnt"]>0)
					$needAdd = false;
			}
		}
		if($needAdd)
			$selectpdf_sqlfields.= "<option value='".$mdata["sqlfield"]."'".$s.">".$mdata["sqlfield"]."</option>";
	}
	echo $selectpdf_sqlfields;
	exit();
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

return false;
;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>