<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_forumtopics  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


		$this->events["BeforeAdd"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowAdd"]=true;


		$this->events["BeforeShowEdit"]=true;


		$this->events["AfterAdd"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["BeforeProcessRowList"]=true;

		$this->events["BeforeShowSearch"]=true;

		$this->events["BeforeQueryList"]=true;

		$this->events["BeforeProcessSearch"]=true;




	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$pageObject->AddJSFile("https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js");
$pageObject->AddCssFile("https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css");

if(Security::getUserGroup() !== "Guest")
	$pageObject->setProxyValue("menu","show");

if(Security::getUserGroup() === "Guest")
	$pageObject->hideItem("Subscribe_on_Category_button");

if(postvalue("a")=="started")
	$pageObject->setProxyValue("search","own");

$userData = Security::currentUserData();

$xt->assign("stylename","forumtopics_list usertype_".$_SESSION["User_Type"]);
$xt->assign("srchOpt_attrs","datapaneltype='custom'");

$_SESSION["forum_category_name"] = false;
if( postvalue("category") !=false )
	$_SESSION["forum_category_name"] = postvalue("category");
else{
	$find = array();
	preg_match_all("/\(categoryid~contains~(.+)\)/U",postvalue("q"),$find);
	if(count($find[0]) > 0)
		$_SESSION["forum_category_name"] = $find[1][0];
}


if($_SESSION["forum_category_name"] ){
 $pageObject->hideItem("categoryid_field");
 $_SESSION["forum_category_id"] = DBLookup(DB::PrepareSQL("select id from forumcategories where name=':1'",$_SESSION["forum_category_name"]));
	

	$is_subcribe = DBLookup( DB::PrepareSQL("select count(*) from forumcategorysubscribers where userid=:1 and categoryid=:2",$userData["id"],$_SESSION["forum_category_id"]) );
	$pageObject->setProxyValue("is_subscribe",$is_subcribe);
}
else{
	$_SESSION["forum_category_name"] = "";
	$pageObject->hideItem("Subscribe_on_Category_button");
}

$userData = Security::currentUserData();
$admin_option_show_active_users = DBLookup("select show_active_users from forumsettings");
$stylename = "show_active_users".$admin_option_show_active_users." forumtopics_list usertype_".$_SESSION["User_Type"];
if( !isset($_SESSION["search_mode"]) ){
	$pageObject->hideItem("created_label");
	$pageObject->hideItem("created_field");
}
else{
	$stylename.=" searchresult";
	$createdsort = "dcreated";
	if(postvalue("orderby")==="acreated") $createdsort = "acreated";  
	$pageObject->setProxyValue("createdsort",$createdsort);
	
}

$xt->assign("stylename",$stylename);
init_forum($pageObject, $xt, true);


;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$values["startedby"]=$_SESSION["user_id"];
$values["solved"]=0;
$values["pinned"]=0;					
$values["views"]=0;
$values["created"]=runner_date_format("Y-m-d H:i:s");
$values["activity"]=runner_date_format("Y-m-d H:i:s");
DB::Update("forumtopics",array("lastreplydate" => time()),array("id" => $values["topicid"]));

return true;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

		
						if(postvalue("masterkey1") == false){
							if(postvalue("qs") != false || isset($_SESSION["forumtopics_qs"])){
								$pageObject->searchClauseObj->_where["_search"] = 0;
								$pageObject->searchClauseObj->_where["_simpleSrch"] = "";
							}
							// advanced searach
							if(!empty($pageObject->searchClauseObj->_where["_srchFields"])) $_SESSION["search_mode"] = true;
								$topicClause = null;
								foreach($pageObject->searchClauseObj->_where["_srchFields"] as $i => $sf){
									if($sf["fName"] === "topic" && $sf["opt"] === "Contains") {
										$topicClause = $sf;
										unset( $pageObject->searchClauseObj->_where["_srchFields"][$i] );
									}
							}

						}



if(postvalue("searching") && postvalue("search")==''){
	header("Location: forumtopics_list.php");
	exit();
}

if(postvalue("userid") && postvalue("topicid")){
	DB::Exec( DB::PrepareSQL("delete from forumsubscribers where topicid=:1 and userid=:2",postvalue("topicid"),postvalue("userid")) );
	echo GetCustomLabel("unsubscribed");
	die();
}

if(postvalue("a") === "fileupload"){
	require_once getabspath('classes/uploadhandler.php');
	$upload_files = array();
	foreach($_FILES as $file){
		$uh = new UploadHandler();
		$path_parts = $uh->pathinfo_local( $file["name"] );
		$new_file_name = $uh->tempnam_sfx("files", str_replace(" ","_",$path_parts["filename"]),$path_parts["extension"]);
		
		upload_File($file,"files/simplemdeUpload/".$new_file_name);
		
		$upload_files[] = projectUrl()."/files/simplemdeUpload/".$new_file_name;
	}
	echo my_json_encode($upload_files);
	exit();
}


;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		$pageObject->addCSSFile("editor/simplemde.min.css");
$pageObject->addJSFile("editor/simplemde.min.js");


$pageObject->addJSFile("editor/marked.js");

$userData = Security::currentUserData();
if($_SESSION["User_Type"] !== "admin"){
	$pageObject->hideItem("pinned_field");
}
init_forum($pageObject, $xt, true);

;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->addCSSFile("editor/simplemde.min.css");
$pageObject->addJSFile("editor/simplemde.min.js");
$pageObject->addJSFile("editor/marked.js");
$userData = Security::currentUserData();
if($_SESSION["User_Type"] !== "admin"){
	$pageObject->hideItem("pinned_field");
}
init_forum($pageObject, $xt, true);
$autoLockAfter = DBLookup("select autolock_after from forumsettings");
$pageObject->setProxyValue("autoLockAfter",$autoLockAfter);
$pageObject->setProxyValue("locked",$values["locked"]);
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		//send notify
global $cLoginTable,$cDisplayNameField, $cUserNameField;
//check count of notify
$userData = Security::currentUserData();
if($_SESSION["User_Type"] === "admin"){
	$str= DB::PrepareSQL("select count(*) from forumcategorysubscribers where categoryid=:2",$values["categoryid"]);
	$count = DBlookup($str);
	if( intval($count) > 50 ){
		HeaderRedirect("forumsettings","edit","page=sendmail&totalsteps=".( intval($count/50) )."&action=ajax_send_mail&topicid=".$keys["id"]);
		exit();
	}
}

$categorySubRs = DB::Select("forumcategorysubscribers",array("categoryid" => $values["categoryid"]));
while($categorySub = $categorySubRs->fetchAssoc()){
	sendMailAfterNewTopic($categorySub,$values);
}
HeaderRedirect("forumtopics","list");
exit();

;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if($data["solved"] === "1"){
	$row["rowattrs"] = " solved='true' ".$row["rowattrs"];
}
$record["checkbox"] = $record["edit_link"];

if(!$record["checkbox"])
	$record["checkbox_attrs"] = "style='display:none'";


;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before record processed
function BeforeProcessRowList(&$data, $pageObject)
{

		

if($data["solved"] === "1"){
	$data["topic"] = GetCustomLabel("solved")." ".$data["topic"];
}
if($data["pinned"] === "1"){
	$data["topic"] = "<span style='font-size:20px;color:#971d1d;' class='glyphicon glyphicon-pushpin'></span> ".$data["topic"];
}
// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeProcessRowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowSearch(&$xt, &$templatefile, $pageObject)
{

		$xt->assign("item_keywords_label","class='control-label r-search-label'");
;
} // function BeforeShowSearch

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		if(isset($_SESSION["topicClause"])){
	$pageObject->searchClauseObj->_where["_srchFields"][] = array("fName"=>"topic","eType"=>"","value1"=>$_SESSION["topicClause"],"not"=>false,"opt" => "Contains","value2" => "");
	$createdorder = "created desc";
	if(postvalue("orderby") === "acreated") $createdorder = "created asc";
	$strOrderBy = "ORDER BY ".$createdorder.", ".$orderby;
}
if(postvalue("qs") != false || isset($_SESSION["forumtopics_qs"])){
	unset($pageObject->searchClauseObj->_where["_search"]);
	$pageObject->searchClauseObj->_where["_simpleSrch"] = postvalue("qs")!=false?postvalue("qs"):$_SESSION["forumtopics_qs"];
}


;
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
				// Search page: Before process
function BeforeProcessSearch($pageObject)
{

		
					global $cDisplayNameField;
foreach($pageObject->searchClauseObj->_where["_srchFields"] as $i => &$sf){
	if($sf["fName"] === "categoryid" && $sf["opt"] === "Equals") {
		$pageObject->setProxyValue("categoryid",getSearchFieldsvalues("forumcategories","name",$sf["value1"])) ;
	}
	if($sf["fName"] === "startedby" && $sf["opt"] === "Equals") {
		$pageObject->setProxyValue("startedby",getSearchFieldsvalues(Security::getLoginTable(),$cDisplayNameField,$sf["value1"]));
	}
}
;
} // function BeforeProcessSearch

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>