<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_forumusers  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessView"]=true;


	}

//	handlers

		
				// View page: Before process
function BeforeProcessView($pageObject)
{

		if(postvalue("editid1") == null){
	$keys = array();
	$userData = Security::currentUserData();
	$keys["id"] = $userData["id"];
	$pageObject->setKeys( $keys );	
}

;
} // function BeforeProcessView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>