<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_forumsubscribers  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowList"]=true;

		$this->events["BeforeMoveNextList"]=true;


		$this->events["BeforeQueryList"]=true;


	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		$_SESSION["subscribelist"] = "";
if(postvalue("unsub") && $_SESSION["user_id"]){
	$_SESSION["subscribelist"] = "List of subscriptions updated";
	DB::Exec( DB::PrepareSQL("delete from forumsubscribers where userid=:1 and topicid=:2",$_SESSION["user_id"],postvalue("unsub")) );
}
if(postvalue("categoryunsub")!=false){
	$userData = Security::currentUserData();
	if(postvalue("userid")!=false){
		$user_id = postvalue("userid");
	}
	else{
		$user_id = $userData[$_SESSION["loginKeyField"]];
	}
	DB::Exec(DB::PrepareSQL("delete from forumcategorysubscribers where userid=:1 and categoryid=:2",$user_id,postvalue("categoryunsub")));
	echo GetCustomLabel("unsubscribed");
	die();
}

$_SESSION["sub_categories"] = array();
$userData = Security::currentUserData();
$userKey = $userData[$_SESSION["loginKeyField"]];
$categorySubRs = DB::Select("forumcategorysubscribers",array( "userid" => $userKey ));
while($categorySub = $categorySubRs->fetchAssoc()){
	$categoryrs = DB::Select("forumcategories",array("id" => $categorySub["categoryid"]));
	$category = $categoryrs->fetchAssoc();
	$_SESSION["sub_categories"][$category["id"]] = $category["name"];
}


;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		init_forum($pageObject, $xt, false);
;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		

if( in_array(intval($data["categoryid"]),array_keys($_SESSION["sub_categories"])) ){
	$record["topicid_value"] = "from ".$_SESSION["sub_categories"][intval($data["categoryid"])];
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: Before SQL query
function BeforeQueryList(&$strSQL, &$strWhereClause, &$strOrderBy, $pageObject)
{

		if($_SESSION["user_id"])
	$strWhereClause = "userid='".$_SESSION["user_id"]."'";
;
} // function BeforeQueryList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>