<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_profile  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeProcessView"]=true;

		$this->events["BeforeShowView"]=true;

		$this->events["BeforeShowEdit"]=true;


	}

//	handlers

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		
$keys = array();
$keys["username"] = $_SESSION["forumudata"]["username"];
$pageObject->setKeys( $keys );	

;
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
				// View page: Before process
function BeforeProcessView($pageObject)
{

		if(postvalue("editid1") == null){
	$keys = array();
	$keys["username"] = $_SESSION["forumudata"]["username"];
	$pageObject->setKeys( $keys );	
}
;
} // function BeforeProcessView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		$xt->assign("stylename","profile");
if(postvalue("editid1") != null && $values["username"] !== $_SESSION["forumudata"]["username"]){
	$pageObject->hideItem("view_edit");
}
;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$xt->assign("stylename","profile");
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>