<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chat_history  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeShowAdd"]=true;


		$this->events["BeforeAdd"]=true;

		$this->events["CustomAdd"]=true;


	}

//	handlers

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		include_once("chat_functions.php");

$userdata = Security::currentUserData();
if(!count($userdata)){
	echo GetCustomLabel("error_login");
	die();
}

$_SESSION["loginTime"] = 10;
$_SESSION["scrollStep"] = 14;
$res = array();

/*if(postvalue("a") == "sound"){
	global $loginKeyFields;
	$userdata = Security::currentUserData();
	$t = explode(" ",this_microtime());
	DB::Insert("chat_history", array("created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4),"isread"=>0,"targetid"=>$_SESSION["targetid"], "soundRecord"=>postvalue("blob"), "ownerid"=>$userdata[$loginKeyFields[0]]));
	die();
}*/


if(postvalue("a") == "closeCallPopup"){
	global $loginKeyFields, $cDisplayNameField, $cUserNameField;
	$userdata = Security::currentUserData();
	DB::Delete("chat_history", array("isVideo"=>3, "targetid"=>$userdata[$loginKeyFields[0]]));
	DB::Delete("chat_history", array("isVideo"=>3, "ownerid"=>$userdata[$loginKeyFields[0]]));
	die();
}

if(postvalue("a") == "closeVideoChat"){
	global $loginKeyFields, $cDisplayNameField, $cUserNameField;
	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;
	$userdata = Security::currentUserData();
	$username = $userdata[$cDisplayNameField];
	if(!$username)
		$username = $userdata[$cUserNameField];
	$t = explode(" ",this_microtime());
	DB::Delete("chat_history", array("isVideo"=>1, "ownerid"=>$userdata[$loginKeyFields[0]]));
	DB::Insert("chat_history", array("messages"=>"cancel","created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4),"isread"=>0,"targetid"=>$_SESSION["targetid"], "isVideo"=>2, "ownerid"=>$userdata[$loginKeyFields[0]]));
	//DB::Insert("chat_history", array("messages"=>"<i>".$username." cancelled video chat</i>","created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4),"isread"=>0,"targetid"=>$_SESSION["targetid"], "isVideo"=>0, "ownerid"=>$userdata[$loginKeyFields[0]]));
	die();
}
if(postvalue("a") == "deleteVideoChat"){
	global $loginKeyFields, $cDisplayNameField, $cUserNameField;
	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;
	$userdata = Security::currentUserData();
	$username = $userdata[$cDisplayNameField];
	if(!$username)
		$username = $userdata[$cUserNameField];
	DB::Delete("chat_history", array("isVideo"=>2, "targetid"=>$userdata[$loginKeyFields[0]]));
	DB::Delete("chat_history", array("isVideo"=>2, "ownerid"=>$userdata[$loginKeyFields[0]]));
	//DB::Insert("chat_history", array("messages"=>"<i>".$username." cancelled video chat</i>","created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4),"isread"=>0,"targetid"=>$_SESSION["targetid"], "isVideo"=>0, "ownerid"=>$userdata[$loginKeyFields[0]]));
	die();
}

if(postvalue("a") == "answerCallChat"){
	global $loginKeyFields, $cDisplayNameField, $cUserNameField;
	$t = explode(" ",this_microtime());
	$userdata = Security::currentUserData();
	DB::Insert("chat_history", array("messages"=>"answer","created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4),"isread"=>0,"targetid"=>$_SESSION["targetid"], "isVideo"=>3, "ownerid"=>$userdata[$loginKeyFields[0]]));
	die();
}

if(postvalue("a") == "delete_chat" && $_SESSION["targetid"]){
	DB::Delete("chat_groups", array("id"=>getGroupID($_SESSION["targetid"])));
	DB::Delete("chat_history", array("targetid"=>$_SESSION["targetid"]));
	unset($_SESSION["targetid"]);
	die();
}

if(postvalue("a") == "leave_chat" && $_SESSION["targetid"]){
	global $loginKeyFields;
	$ownerid = DBLookup("select ".addFieldWrappers("ownerid")." from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("id")."=".getGroupID($_SESSION["targetid"]));
	$userdata = Security::currentUserData();
	$ids = getGroupIDs($_SESSION["targetid"]);
	$IDarray = explode(",",$ids);
	$key = array_search($ownerid,$IDarray);
	unset($IDarray[$key]);
	$key = array_search($userdata[$loginKeyFields[0]],$IDarray);
	unset($IDarray[$key]);
	DB::Update("chat_groups", array("targetid"=>implode(",",$IDarray)), array("id"=>getGroupID($_SESSION["targetid"])));
	unset($_SESSION["targetid"]);
	die();
}
if(postvalue("a") == "getsound"){
	$jpath = DBLookup("select ".addFieldWrappers("soundpath")." from ".addTableWrappers("chat_settings"));
	//$path = my_json_decode($jpath);
	//echo $path[0]["name"];
	echo $jpath;
	die();
}
if(postvalue("a") == "getMessById" && postvalue("id")){
	$txt = DBLookup("select messages from chat_history where id=".postvalue("id"));
	echo $txt;
	die();
}

if(postvalue("a")=="searchuser"){
	global $loginKeyFields, $cLoginTable,$cDisplayNameField, $cUserpicField, $cUserNameField;
	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;
	$res = "";
	$userdata = Security::currentUserData();
	$txt = str_replace("'","\'",postvalue("text"));

	$rs = DB::Query("select * from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("groupname")." LIKE '%".$txt."%'");
	while($data = $rs->fetchAssoc()){
		$users = array();
		$users = explode(",",$data["targetid"]);
		$users[] = $data["ownerid"];
		if(in_array($userdata[$loginKeyFields[0]],$users))
			$res.="<div class='findusers' id='userG".$data["id"]."' uid='G".$data["id"]."'>".$data["groupname"]."</div>";
	}

	$rs = DB::Query("select * from ".addTableWrappers($cLoginTable)." where (".addFieldWrappers($cDisplayNameField)." LIKE '%".$txt."%' or ".addFieldWrappers($cUserNameField)." LIKE '%".$txt."%') and ".addFieldWrappers($loginKeyFields[0])."<>'".$userdata[$loginKeyFields[0]]."'");
	while($data = $rs->fetchAssoc()){
		$name = $data[$cDisplayNameField];
		if(!$name)
			$name = $data[$cUserNameField];
		$res.="<div class='findusers' id='user".$data[$loginKeyFields[0]]."' uid='".$data[$loginKeyFields[0]]."'>".$name."</div>";
	}
	if(!$res)
		$res = "<div class='notfindusers'>".getCustomLabel("seacrh_not_found")."</div>";
	echo $res;
	die();
}

if(postvalue("a")=="suggest"){
	if(!postvalue("text")){
		echo "";
		die();
	}
	global $loginKeyFields, $cLoginTable,$cDisplayNameField, $cUserpicField, $cUserNameField;
	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;

	$res = "";
	$userdata = Security::currentUserData();
	$txt = str_replace("'","\'",postvalue("text"));
	$resArray = array();
	$rs = DB::Query("select * from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("groupname")." LIKE '%".$txt."%' order by ".addFieldWrappers("groupname"));
	while($data = $rs->fetchAssoc()){
		$users = array();
		$users = explode(",",$data["targetid"]);
		$users[] = $data["ownerid"];
		if(in_array($userdata[$loginKeyFields[0]],$users))
			$resArray["G".$data["id"]] = $data["groupname"];
	}

	$rs = DB::Query("select * from ".addTableWrappers($cLoginTable)." where (".addFieldWrappers($cDisplayNameField)." LIKE '%".$txt."%' or ".addFieldWrappers($cUserNameField)." LIKE '%".$txt."%') and ".addFieldWrappers($loginKeyFields[0])."<>'".$userdata[$loginKeyFields[0]]."' order by ".addFieldWrappers($cUserNameField));
	while($data = $rs->fetchAssoc()){
		$name = $data[$cDisplayNameField];
		if(!$name)
			$name = $data[$cUserNameField];
		$resArray[$data[$loginKeyFields[0]]] = $name;
		
	}
	//sort($resArray);
	foreach($resArray as $key=>$val)
		$res.="<div uid='user".$key."' class='suggest_result'>".$val."</div>";
	echo $res;
	die();
}
if(postvalue("a") == "getMobileUsers"){
	echo getGroupMenu();
	echo getMenu();
	die();
}
if(postvalue("a") == "delete_record" && postvalue("rid")){
		$t = explode(" ",this_microtime());
		DB::Update("chat_history", array("status"=>"delete", "status_created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4)), array("id"=>postvalue("rid")));
		die();
}
if(postvalue("a") == "edit_record" && postvalue("rid")){
		$t = explode(" ",this_microtime());
		DB::Update("chat_history", array("messages"=>postvalue("text"),"status"=>"edit", "status_created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4)), array("id"=>postvalue("rid")));
		die();
}

if(postvalue("a") == "setActivity" && postvalue("targetid")){
	$_SESSION["targetid"] = postvalue("targetid");
	$_SESSION["scroll_step"]=0;
	$isVideo = DBLookup("select ".addFieldWrappers("videoenable")." from ".addTableWrappers("chat_settings"));
	if(isGroupTarget(postvalue("targetid")))
		$isVideo = 0;
	echo my_json_encode(array("headertext"=>getHeader(),"isVideo"=>$isVideo));
	die();
}
if(postvalue("a") == "scrollmessages"){
	if(!$_SESSION["scroll_step"])
		$_SESSION["scroll_step"]=0;
	$_SESSION["scroll_step"]++;
	die();
}

if(postvalue("a") == "getsettings"){
	$rs = DB::Select("chat_settings");
	if($data = $rs->fetchAssoc())
		echo my_json_encode(array("period"=>$data["timeperiod"]*1000));
	else
		echo my_json_encode(array("period"=>5000));
	die();
}

if(postvalue("a") == "getchatinfo"){
	global $loginKeyFields, $cLoginTable,$cDisplayNameField, $cUserpicField, $cUserNameField;
	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;

	$res = array();
	$isStart = postvalue("isStart");
	$isTyping = postvalue("isType");
	if(!$isTyping)
		$isTyping = 0;
	$rs = DB::Select("chat_users", array("userid"=>$isTyping));
	if($data = $rs->fetchAssoc()){
		if(strtotime(date("Y-m-d H:i:s")) - strtotime($data["lastaccess"]) > $_SESSION["loginTime"])
			$isTyping = "0";
	}
	$_SESSION["searchValue"] = "";
	$_SESSION["searchSQLValue"] = "";
	$res["search_result"] = "";
	if(postvalue("search")){
		$_SESSION["searchSQLValue"] = " and ".addFieldWrappers("messages")." LIKE '%".postvalue("search")."%'";
		$_SESSION["searchValue"] = postvalue("search");
		$res["search_result"] = "<span class='header_name search_result'>".GetCustomLabel("search_result")." '".$_SESSION["searchValue"] ."'</span>";
		$_SESSION["scroll_step"] = 0;
	}
	$userdata = Security::currentUserData();
	//isType
	$rs = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_users")." where ".addFieldWrappers("userid")."='".$userdata[$loginKeyFields[0]]."'");
	$data = $rs->fetchAssoc();

	if($data["cnt"]>0)
		DB::Update("chat_users", array("lastaccess"=>date("Y-m-d H:i:s"),"isTyping"=>$isTyping), array("userid"=>$userdata[$loginKeyFields[0]]));
	else
		DB::Insert("chat_users", array("userid"=>$userdata[$loginKeyFields[0]], "lastaccess"=>date("Y-m-d H:i:s"), "isTyping"=>$isTyping));
	
	$rs = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_history")." where ".addFieldWrappers("targetid")."='".$userdata[$loginKeyFields[0]]."' and ".addFieldWrappers("isread")."='0'");
	$data = $rs->fetchAssoc();
	if($data["cnt"]>0){
		$res["noti"] = "setNotification";
		$res["noticnt"] = $data["cnt"];
	}

	$res["usermenu"] =  getAjaxMenu();
	$res["groupmenu"] = getGroupAjaxMenu();
	$res["targetid"] = $_SESSION["targetid"];
	$res["currentUserNameStatus"] = getUserStatusHeader($_SESSION["targetid"]);
	$res["msg"] = getMessage($isStart);
	$res["video"] = getVideoCallData();
	$res["isVideoCall"] = $res["video"]["isVideo"];

	$res["isVideo"] = DBLookup("select ".addFieldWrappers("videoenable")." from ".addTableWrappers("chat_settings"));
	
	updateIsRead();
	//DB::Exec("update chat_history set isread='".$_SESSION["targetid"]."' where ownerid=".$_SESSION["targetid"]." and SUBSTR(targetid,1,1)<>'G'");
	
	$res["delete"] = getDeleteMessage();
	$res["edit"] = getEditMessage();
	$res["isread"] = getIsReadStatus();
	echo my_json_encode($res);
	die();
}
;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		global $loginKeyFields, $cDisplayNameField, $cUserNameField, $cLoginTable;
/*	if(!$cDisplayNameField)
		$cDisplayNameField = $cUserNameField;*/

$userdata = Security::currentUserData();

$pageObject->AddJSFile("include/howler.min.js");
$pageObject->hideItem("add_save");
if(postvalue("userid")){
	$_SESSION["targetid"] = "";
	if(isGroupTarget(postvalue("userid"))){
		$gid = getGroupID(postvalue("userid"));
		$rs = DB::Select("chat_groups", array("id"=>$gid));
		if($data = $rs->fetchAssoc()){
			$users = array();
			$users = explode(",",$data["targetid"]);
			$users[] = $data["ownerid"];
			if(in_array($userdata[$loginKeyFields[0]],$users))
				$_SESSION["targetid"] = postvalue("userid");
		}
	}
	else
		$_SESSION["targetid"] = postvalue("userid");
}

$_SESSION["anchor"] = "";

$usersExists = false;
if(postvalue("userid"))
	$usersExists = true;

$rs = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_history")." where ".addFieldWrappers("targetid")."='".$userdata[$loginKeyFields[0]]."' or ".addFieldWrappers("ownerid")."='".$userdata[$loginKeyFields[0]]."'");
$data = $rs->fetchAssoc();
if($data["cnt"]>0)
	$usersExists = true;

$rs = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("ownerid")."='".$userdata[$loginKeyFields[0]]."'");
$data = $rs->fetchAssoc();
if($data["cnt"]>0)
	$usersExists = true;

$rs = DB::Select("chat_groups");
while($data = $rs->fetchAssoc()){
	$arr = explode(",",$data["targetid"]);
	if(in_array($userdata[$loginKeyFields[0]],$arr))
		$usersExists = true;
}

if(!$usersExists){
	$pageObject->hideItem("chat_write");
	$pageObject->hideItem("chat_send");
	$pageObject->hideItem("clip_button");
	$pageObject->hideItem("chat_files");
	$pageObject->hideItem("call_video");
	$pageObject->hideItem("start_audio");
	$_SESSION["targetid"] = 0;
}
$_SESSION["scroll_step"] = 0;

$pageObject->hideItem("select_users");

$pageObject->setProxyValue("targetid",$_SESSION["targetid"]);

$pageObject->hideItem("stop_audio");
$issound = DBLookup("select ".addFieldWrappers("soundenable")." from ".addTableWrappers("chat_settings"));
if(!$issound)
	$pageObject->hideItem("start_audio");
$isVideo = DBLookup("select ".addFieldWrappers("videoenable")." from ".addTableWrappers("chat_settings"));

if(!$isVideo || isGroupTarget($_SESSION["targetid"]))
	$pageObject->hideItem("call_video");
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		global $loginKeyFields;
$recSound = postvalue("soundRecord");
$mess = postvalue("msg");
if(strlen($mess)>4000)
	$mess = substr($mess,0,4000);
$userdata = Security::currentUserData();
$t = explode(" ",this_microtime());
if($values["tmp_file"] || $mess || $recSound){
	DB::Insert("chat_history", array("soundRecord"=>$recSound,"messages"=>$mess, "created"=>date("Y-m-d H:i:s",$t[1]).substr((string)$t[0],1,4), "isread"=>0, "targetid"=>$_SESSION["targetid"], "ownerid"=>$userdata[$loginKeyFields[0]], "status"=>''));
	$message_id = DB::LastId();

	if($values["tmp_file"]){
		$rs = DB::Query("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_files")." where ".addFieldWrappers("messageid")."=".$message_id);
		$data = $rs->fetchAssoc();
		if($data["cnt"] == 0)
			DB::Insert("chat_files", array("messageid"=>$message_id, "files"=>$values["tmp_file"]));
	}
}
return false;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Custom add
function CustomAdd(&$values, &$keys, &$error, $inline, $pageObject)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

return false;
;
} // function CustomAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>