<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_chat_groups  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeEdit"]=true;


		$this->events["AfterEdit"]=true;

		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeShowEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		global $tables_data;
global $loginKeyFields, $cLoginTable, $cUserNameField, $cDisplayNameField;
//if(!$cDisplayNameField)
//	$cDisplayNameField = $cUserNameField;
$users = array();
$rs = DB::Select($cLoginTable,"");
while($data = $rs->fetchAssoc()){
	if(Security::getUserName()!=$data[$cUserNameField])
		$users[] = $data[$cUserNameField];
}
$tables_data["chat_groups"]["targetid"]["EditFormats"]["edit"]["LookupValues"] = $users;

;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		global $loginKeyFields, $cLoginTable, $cUserNameField, $cDisplayNameField;
//if(!$cDisplayNameField)
//	$cDisplayNameField = $cUserNameField;
$userdata = Security::currentUserData();
$values["ownerid"] = $userdata[$loginKeyFields[0]];
if($values['grouptype']==1){
	$rs = DB::Select($cLoginTable,addFieldWrappers($loginKeyFields[0])."<>'".$userdata[$loginKeyFields[0]]."'");
	$res = "";
	while($data = $rs->fetchAssoc()){
		if($res)
			$res.=",";
		$res.= $data[$loginKeyFields[0]];
	}
	$values['targetid'] = $res;
}

if($values['grouptype']==2){
	if(!$values['targetid']){
		$pageObject->setProxyValue("errors", GetCustomLabel("empty_selected_user"));
		return false;
	}
	else{
		$res = array();
		$arr = explode(",",$values['targetid']);
		foreach($arr as $val){
			$udata = Security::getUserData($val);
			$res[] = $udata[$loginKeyFields[0]];
		}
		$values['targetid'] = implode(",",$res);
	}
}

$cnt = DBLookup(DB::PrepareSQL("select count(id) as cnt from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("groupname")."=':1'",$values['groupname']));
if($cnt > 0){
	$pageObject->setProxyValue("errors", GetCustomLabel("groupname_exist"));
	return false;
}


return true;

;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$pageObject->stopPRG = true;
$pageObject->setProxyValue("saved", $keys["id"]);


;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		global $tables_data;
global $loginKeyFields, $cLoginTable, $cUserNameField, $cDisplayNameField;
//if(!$cDisplayNameField)
//	$cDisplayNameField = $cUserNameField;
$users = array();
$rs = DB::Select($cLoginTable,"");
while($data = $rs->fetchAssoc()){
	if(Security::getUserName()!=$data[$cUserNameField])
		$users[] = $data[$cUserNameField];
}
$tables_data["chat_groups"]["targetid"]["EditFormats"]["edit"]["LookupValues"] = $users;

;
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		global $loginKeyFields, $cLoginTable, $cUserNameField, $cDisplayNameField;
$userdata = Security::currentUserData();
$values["ownerid"] = $userdata[$loginKeyFields[0]];
if($values['grouptype']==1){
	$rs = DB::Select($cLoginTable,addFieldWrappers($loginKeyFields[0])."<>'".$userdata[$loginKeyFields[0]]."'");
	$res = "";
	while($data = $rs->fetchAssoc()){
		if($res)
			$res.=",";
		$res.= $data[$loginKeyFields[0]];
	}
	$values['targetid'] = $res;
}


if($values['grouptype']==2){
	if(!$values['targetid']){
		$pageObject->setProxyValue("errors", GetCustomLabel("empty_selected_user"));
		return false;
	}
	else{
		$res = array();
		$arr = explode(",",$values['targetid']);
		foreach($arr as $val){
			$udata = Security::getUserData($val);
			$res[] = $udata[$loginKeyFields[0]];
		}
		$values['targetid'] = implode(",",$res);
	}
}

$cnt = DBLookup(DB::PrepareSQL("select count(".addFieldWrappers("id").") as cnt from ".addTableWrappers("chat_groups")." where ".addFieldWrappers("groupname")."=':1'",$values['groupname']));
if($cnt > 0 && $values['groupname']!=$oldvalues['groupname']){
	$pageObject->setProxyValue("errors", GetCustomLabel("groupname_exist"));
	return false;
}


return true;

;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$pageObject->setProxyValue("saved", $keys["id"]);
$pageObject->stopPRG = true;
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		$pageObject->hideItem("loginform_login");
$pageObject->hideItem("username_button");
$xt->assign("header", false );
$xt->assign("footer", false );
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->hideItem("loginform_login");
$pageObject->hideItem("username_button");
$xt->assign("header", false );
$xt->assign("footer", false );

;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>