<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'DateField' => array( 'totalsType' => '' ),
'Description' => array( 'totalsType' => '' ),
'Subject' => array( 'totalsType' => '' ),
'TimeField' => array( 'totalsType' => '' ),
'EndTime' => array( 'totalsType' => '' ),
'DayEvent' => array( 'totalsType' => '' ),
'EndDate' => array( 'totalsType' => '' ),
'Period' => array( 'totalsType' => '' ),
'PeriodDays' => array( 'totalsType' => '' ),
'Recurrence' => array( 'totalsType' => '' ),
'Category' => array( 'totalsType' => '' ),
'OwnerID' => array( 'totalsType' => '' ),
'RecurType' => array( 'totalsType' => '' ),
'RecurOnValue' => array( 'totalsType' => '' ),
'RecurAfterValue' => array( 'totalsType' => '' ),
'Color' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Subject',
'DateField',
'EndDate',
'Description',
'Category' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array(  ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'left' => array( 'search_panel' ),
'top' => array(  ),
'above-grid' => array( 'snippet' ),
'below-grid' => array(  ),
'grid' => array(  ) ),
'formXtTags' => array( 'top' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'search_panel' => 'left',
'snippet' => 'above-grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'username_button' => 3,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'search_panel' => 5,
'menu' => 3 ) ),
'itemsByType' => array( '-' => array( '-',
'-1',
'-2',
'-3',
'-4' ),
'snippet' => array( 'snippet' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'loginform_login' => array( 'loginform_login' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field1',
'search_panel_field2',
'search_panel_field7',
'search_panel_field11',
'search_panel_field' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'advsearch_link' => array( 'advsearch_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'changepassword_link' => array( 'changepassword_link' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'snippet' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ) ) ) ),
'cells' => array( 'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array(  ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( '-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'snippet' => array( 'eventId' => 'calcalendar_snippet',
'type' => 'snippet' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ),
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'simple_search' => array( 'type' => 'simple_search' ),
'-2' => array( 'type' => '-' ),
'-3' => array( 'type' => '-' ),
'-4' => array( 'type' => '-' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field2',
'search_panel_field1',
'search_panel_field7',
'search_panel_field',
'search_panel_field11' ),
'_flexiblePanel' => true ),
'search_panel_field1' => array( 'field' => 'DateField',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field2' => array( 'field' => 'Subject',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field7' => array( 'field' => 'EndDate',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field11' => array( 'field' => 'Category',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Description',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ) ),
'dbProps' => array(  ),
'version' => 11,
'businessTemplate' => 'Calendar',
'businessTemplatePageId' => 'list',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>