<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'boardname' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'boardname' => array( 'integrated_edit_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array(  ),
'above-grid' => array(  ),
'below-grid' => array( 'edit_back_list',
'edit_close' ),
'grid' => array( 'snippet',
'snippet3',
'snippet1',
'integrated_edit_field',
'snippet2',
'custom_button' ) ),
'formXtTags' => array( 'top' => array(  ),
'above-grid' => array(  ),
'below-grid' => array( 'back_button',
'close_button' ) ),
'itemForms' => array( 'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'snippet' => 'grid',
'snippet3' => 'grid',
'snippet1' => 'grid',
'integrated_edit_field' => 'grid',
'snippet2' => 'grid',
'custom_button' => 'grid' ),
'itemLocations' => array( 'snippet' => array( 'location' => 'grid',
'cellId' => 'c' ),
'snippet3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'snippet1' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'snippet2' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'c5' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_field' => array( 'integrated_edit_field' ),
'snippet' => array( 'snippet',
'snippet1',
'snippet3',
'snippet2' ),
'custom_button' => array( 'custom_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'snippet3',
'snippet1',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'snippet' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'print_board' ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'print_board' ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'snippet' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'snippet3',
'snippet1',
'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'horizontal',
'align' => 'left',
'padding' => array( 'top' => '15px' ),
'width' => '50%' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'snippet2',
'custom_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'orientation' => 'horizontal',
'align' => 'right',
'padding' => array( 'top' => '15px' ),
'width' => '50%' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_back_list' => array( 'type' => 'edit_back_list',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  display:none !important;
}
' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'boardname',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'snippet' => array( 'type' => 'snippet',
'eventId' => 'boards_sections',
'label' => array( 'text' => 'boards_sections',
'type' => 0 ) ),
'snippet1' => array( 'eventId' => 'div_boardname',
'label' => array( 'text' => 'div_boardname',
'type' => 0 ),
'type' => 'snippet' ),
'snippet3' => array( 'eventId' => 'home',
'label' => array( 'text' => 'home',
'type' => 0 ),
'type' => 'snippet',
'padding' => array( 'left' => '12px' ) ),
'snippet2' => array( 'eventId' => 'todoboards_search',
'label' => array( 'text' => 'todoboards_search',
'type' => 0 ),
'type' => 'snippet' ),
'custom_button' => array( 'eventId' => 'print_board',
'label' => array( 'text' => 'Print Board',
'type' => 0 ),
'type' => 'custom_button',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-left:50px;
}
' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>