<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc8bd05d0f1716e91ee1a3dbabbcf7727
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Ifsnop\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ifsnop\\' => 
        array (
            0 => __DIR__ . '/..' . '/ifsnop/mysqldump-php/src/Ifsnop',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc8bd05d0f1716e91ee1a3dbabbcf7727::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc8bd05d0f1716e91ee1a3dbabbcf7727::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc8bd05d0f1716e91ee1a3dbabbcf7727::$classMap;

        }, null, ClassLoader::class);
    }
}
