<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'welcome_group' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumtopics',
'page' => 'list' ) ) ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Dashboard',
'page' => 'dashboard' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumtopics_view',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumreplies_view',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumsubscribers_view',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumsubscribers_dash',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumreplies_chart',
'page' => 'chart' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumsettings',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumcategorysubscribers',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'forumusers_data',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'profile',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'above-grid' => array(  ),
'grid' => array( 'welcome_group',
'welcome_item',
'welcome_item1',
'welcome_item3',
'welcome_item5',
'welcome_item6',
'welcome_item4',
'welcome_item7',
'welcome_item9',
'welcome_item10',
'welcome_item8' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'welcome_group' => 'grid',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item3' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item4' => 'grid',
'welcome_item7' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item8' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'welcome_group' => array( 'welcome_group' ),
'welcome_item' => array( 'welcome_item2',
'welcome_item',
'welcome_item1',
'welcome_item3',
'welcome_item5',
'welcome_item6',
'welcome_item4',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10' ),
'userinfo_link' => array( 'userinfo_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu_Project',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 50,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_group' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item3',
'welcome_item5',
'welcome_item6',
'welcome_item4',
'welcome_item7',
'welcome_item9',
'welcome_item10',
'welcome_item8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'welcome_page' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'welcome_group' => array( 'type' => 'welcome_group',
'linkText' => array( 'text' => 'Forum49',
'type' => 0 ),
'linkIcon' => null,
'linkCSS' => '',
'linkComments' => array( 'text' => 'Project description',
'type' => 0 ),
'items' => array( 'welcome_item2' ) ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumtopics',
'linkPage' => 'list',
'linkText' => array( 'text' => 'Topics',
'type' => 0 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'linkCSS' => '',
'linkComments' => array( 'text' => 'topics description',
'type' => 0 ),
'linkParams' => '',
'linkType' => 0 ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Dashboard',
'linkPage' => 'dashboard',
'linkText' => array( 'table' => 'Dashboard',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'text' => 'Dashboard description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumtopics_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumtopics_view',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Forumtopics View description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumreplies_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumreplies_view',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkComments' => array( 'text' => 'Forumreplies View description',
'type' => 0 ),
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumsubscribers_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumsubscribers_view',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'shopping-cart' ),
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumsubscribers_dash',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumsubscribers_dash',
'type' => 6 ),
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumreplies_chart',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'forumreplies_chart',
'type' => 6 ),
'linkType' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumsettings',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumsettings',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'profile',
'linkPage' => 'list',
'linkText' => array( 'table' => 'profile',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumcategorysubscribers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumcategorysubscribers',
'type' => 6 ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'forumusers_data',
'linkPage' => 'list',
'linkText' => array( 'table' => 'forumusers_data',
'type' => 6 ),
'background' => '#CD853F',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'businessTemplate' => 'Project',
'businessTemplatePageId' => 'menu_Forum',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>