<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list' ),
'grid' => array(  ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashSearch' => array( 'searchFields' => array( 'forumtopics_view_topic' => array( array( 'field' => 'topic',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_startedby' => array( array( 'field' => 'startedby',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_startedby2' => array( array( 'field' => 'startedby2',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_id' => array( array( 'field' => 'id',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_categoryid' => array( array( 'field' => 'categoryid',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_views' => array( array( 'field' => 'views',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_activity' => array( array( 'field' => 'activity',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_pinned' => array( array( 'field' => 'pinned',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_color' => array( array( 'field' => 'color',
'table' => 'forumtopics_view' ) ),
'forumtopics_view_created' => array( array( 'field' => 'created',
'table' => 'forumtopics_view' ) ),
'forumsubscribers_dash_id' => array( array( 'field' => 'id',
'table' => 'forumsubscribers_dash' ) ),
'forumsubscribers_dash_userid' => array( array( 'field' => 'userid',
'table' => 'forumsubscribers_dash' ) ),
'forumsubscribers_dash_topicid' => array( array( 'field' => 'topicid',
'table' => 'forumsubscribers_dash' ) ),
'forumsubscribers_dash_topic' => array( array( 'field' => 'topic',
'table' => 'forumsubscribers_dash' ) ),
'forumsubscribers_dash_name' => array( array( 'field' => 'name',
'table' => 'forumsubscribers_dash' ) ) ),
'allSearchFields' => array( 'forumtopics_view_topic',
'forumtopics_view_startedby',
'forumtopics_view_startedby2',
'forumtopics_view_id',
'forumtopics_view_categoryid',
'forumtopics_view_views',
'forumtopics_view_activity',
'forumtopics_view_pinned',
'forumtopics_view_color',
'forumtopics_view_created',
'forumsubscribers_dash_id',
'forumsubscribers_dash_userid',
'forumsubscribers_dash_topicid',
'forumsubscribers_dash_topic',
'forumsubscribers_dash_name' ),
'googleLikeFields' => array( 'forumtopics_view_topic',
'forumtopics_view_startedby',
'forumtopics_view_startedby2',
'forumtopics_view_id',
'forumtopics_view_categoryid',
'forumtopics_view_views',
'forumtopics_view_activity',
'forumtopics_view_pinned',
'forumtopics_view_color',
'forumtopics_view_created',
'forumsubscribers_dash_id',
'forumsubscribers_dash_userid',
'forumsubscribers_dash_topicid',
'forumsubscribers_dash_topic',
'forumsubscribers_dash_name' ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>