<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => true,
'detailsAdd' => true,
'inlineEdit' => true,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => false,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'forumtopics' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'topicid' => array( 'totalsType' => '' ),
'userid' => array( 'totalsType' => '' ),
'reply' => array( 'totalsType' => '' ),
'created' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'userid2' => array( 'totalsType' => '' ),
'image' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'userid',
'userid2',
'created',
'reply' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'reply' ),
'inlineEditFields' => array( 'reply' ),
'fieldItems' => array( 'userid' => array( 'simple_grid_field1' ),
'userid2' => array( 'simple_grid_field' ),
'created' => array( 'simple_grid_field3' ),
'reply' => array( 'simple_grid_field2' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'Mark_as_Solved',
'mark_is_not_solved',
'inline_add',
'replyCount1' ),
'below-grid' => array( 'Mark_as_Solved1',
'rbutton',
'replyCount2' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'loginform_login',
'alert_notify',
'username_button',
'user_name',
'list_options',
'skins' ),
'left' => array(  ),
'top' => array( 'master_info',
'breadcrumb',
'locked_topic' ),
'grid' => array( 'simple_grid_field1',
'grid_inline_save',
'grid_inline_cancel',
'simple_grid_field',
'grid_checkbox',
'grid_inline_edit',
'simple_grid_field3',
'simple_grid_field2' ) ),
'formXtTags' => array( 'left' => array(  ) ),
'itemForms' => array( 'Mark_as_Solved' => 'above-grid',
'mark_is_not_solved' => 'above-grid',
'inline_add' => 'above-grid',
'replyCount1' => 'above-grid',
'Mark_as_Solved1' => 'below-grid',
'rbutton' => 'below-grid',
'replyCount2' => 'below-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'loginform_login' => 'supertop',
'alert_notify' => 'supertop',
'username_button' => 'supertop',
'user_name' => 'supertop',
'list_options' => 'supertop',
'skins' => 'supertop',
'master_info' => 'top',
'breadcrumb' => 'top',
'locked_topic' => 'top',
'simple_grid_field1' => 'grid',
'grid_inline_save' => 'grid',
'grid_inline_cancel' => 'grid',
'simple_grid_field' => 'grid',
'grid_checkbox' => 'grid',
'grid_inline_edit' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field2' => 'grid' ),
'itemLocations' => array( 'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_inline_save' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_inline_edit' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ) ),
'itemVisiblity' => array( 'menu' => 3,
'loginform_login' => 3,
'username_button' => 3,
'simple_search' => 3,
'list_options' => 3,
'user_name' => 3 ) ),
'itemsByType' => array( 'inline_add' => array( 'inline_add' ),
'snippet' => array( 'replyCount1',
'replyCount2',
'skins',
'user_name',
'alert_notify',
'rbutton' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field',
'simple_grid_field3',
'simple_grid_field2' ),
'grid_inline_save' => array( 'grid_inline_save' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_inline_edit' => array( 'grid_inline_edit' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'master_info' => array( 'master_info' ),
'simple_search' => array( 'simple_search' ),
'breadcrumb' => array( 'breadcrumb' ),
'list_options' => array( 'list_options' ),
'custom_button' => array( 'Mark_as_Solved',
'Mark_as_Solved1',
'mark_is_not_solved' ),
'text' => array( 'locked_topic' ),
'delete_selected' => array( 'delete_selected' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array( 'inline_save',
'inline_cancel' ),
'items' => array( 'grid_inline_save',
'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'userid_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'userid2_fieldcolumn',
'checkbox_column',
'inlineedit_column',
'created_fieldcolumn' ),
'items' => array( 'simple_grid_field',
'grid_checkbox',
'grid_inline_edit',
'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'reply_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 1,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'Mark_as_Solved',
'Mark_as_Solved',
'mark_is_not_solved' ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Mark_as_Solved',
'Mark_as_Solved',
'mark_is_not_solved' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1 ),
array( 'cell' => 'c2',
'rowspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'Mark_as_Solved',
'mark_is_not_solved',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'replyCount1' ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'Mark_as_Solved1',
'rbutton' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'replyCount2' ),
'align' => 'left' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu',
'simple_search' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'alert_notify',
'username_button',
'user_name',
'list_options',
'skins' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'list-vbar',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'locked_topic' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 2 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label3',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label',
'rowspan' => 1 ),
array( 'cell' => 'cell_label2' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_label4' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 2 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'customCSS' => '/* Put  your custom CSS code here */
.panel-heading {
  display:none !important;
}
.panel-default, .panel-primary {
    border:0px !important;
}
' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left',
'border' => array( array( 'side' => 'left',
'width' => '1px' ) ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  vertical-align: top;
}
',
'orientation' => 'vertical',
'field' => 'userid',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_inline_save',
'grid_inline_cancel' ),
'align' => 'left' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left',
'border' => array( array( 'side' => 'left',
'width' => '1px' ) ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  vertical-align: top;
}
',
'orientation' => 'vertical' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field',
'grid_checkbox',
'grid_inline_edit',
'simple_grid_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left',
'border' => array( array( 'side' => 'left',
'width' => '1px' ) ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  vertical-align: top;
}
',
'orientation' => 'horizontal',
'field' => 'userid2',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left',
'border' => array( array( 'side' => 'left',
'width' => '1px' ) ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  vertical-align: top;
}
',
'orientation' => 'vertical',
'field' => 'reply',
'columnName' => 'field' ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'recsPerRow' => 1 ) ),
'items' => array( 'inline_add' => array( 'type' => 'inline_add',
'label' => array( 'type' => 0,
'text' => 'Reply' ) ),
'replyCount1' => array( 'eventId' => 'reply_count_records',
'label' => array( 'text' => 'reply count records',
'type' => 0 ),
'type' => 'snippet' ),
'replyCount2' => array( 'type' => 'snippet',
'eventId' => 'reply_count_records',
'label' => array( 'text' => 'reply count records',
'type' => 0 ) ),
'simple_grid_field1' => array( 'field' => 'userid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_inline_save' => array( 'type' => 'grid_inline_save',
'icon' => array( 'glyph' => '' ),
'buttonStyle' => 'primary',
'label' => array( 'text' => 'Post',
'type' => 0 ) ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel',
'icon' => array( 'glyph' => 'remove' ),
'buttonStyle' => 'default',
'label' => array( 'text' => 'Cancel',
'type' => 0 ) ),
'simple_grid_field' => array( 'field' => 'userid2',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_inline_edit' => array( 'type' => 'grid_inline_edit',
'icon' => array( 'glyph' => 'pencil' ) ),
'simple_grid_field3' => array( 'field' => 'created',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field2' => array( 'field' => 'reply',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'width' => '100%' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ),
'icon' => array( 'glyph' => '' ),
'buttonStyle' => 'link' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'forumtopics' => 'true' ) ),
'simple_search' => array( 'type' => 'simple_search' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected' ),
'buttonStyle' => 'link' ),
'skins' => array( 'type' => 'snippet',
'eventId' => 'skins',
'label' => array( 'text' => 'skins',
'type' => 0 ) ),
'user_name' => array( 'type' => 'snippet',
'eventId' => 'User_Name',
'label' => array( 'text' => 'User Name',
'type' => 0 ),
'mobileControl' => 'button' ),
'alert_notify' => array( 'type' => 'snippet',
'eventId' => 'alert_notify',
'label' => array( 'text' => 'alert notify',
'type' => 0 ) ),
'Mark_as_Solved' => array( 'type' => 'custom_button',
'eventId' => 'Mark_as_Solved',
'label' => array( 'text' => 'Mark as Solved',
'type' => 0 ),
'buttonStyle' => 'primary' ),
'locked_topic' => array( 'type' => 'text',
'label' => array( 'text' => '<span style="font-size:20px;color:#971d1d;" class="glyphicon glyphicon-lock"></span> <b>This topic is locked</b>',
'type' => 0 ),
'editedByRte' => false ),
'Mark_as_Solved1' => array( 'type' => 'custom_button',
'eventId' => 'Mark_as_Solved',
'label' => array( 'text' => 'Mark as Solved',
'type' => 0 ),
'buttonStyle' => 'primary' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'mark_is_not_solved' => array( 'eventId' => 'mark_is_not_solved',
'label' => array( 'text' => 'Mark Is Not Solved',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'primary' ),
'rbutton' => array( 'eventId' => 'rbutton',
'label' => array( 'text' => 'Reply',
'type' => 0 ),
'type' => 'snippet' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>