<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_todocards  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterEdit"]=true;

		$this->events["ProcessValuesView"]=true;


		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeShowView"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		global $cLoginTable, $cUserNameField, $cPasswordField;
include_once("todolist_custom.php");
afterCardUpdated($keys["id"]);

global $cman;
DB::SetConnection(DB::ConnectionByTable($cLoginTable));
$userRs = DB::Select( $cLoginTable, "" );
DB::SetConnection(DB::DefaultConnection());
$userData = array();
while( $data = $userRs->fetchAssoc() ) {
    $userData[ $data["id"] ] = $data;
}

$rs = DB::Select("todocards", array("id"=>$keys["id"]));
$values = $rs->fetchAssoc();

$assign=0;
if($values["assign"])
	$assign=$values["assign"];
$oldassign=0;
if($oldvalues["assign"])
	$oldassign=$oldvalues["assign"];
//$rs = DB::Query("select * from ".$cLoginTable." where id=".$assign);
$data = $userData[$assign];

$cardname = prepareCard($values);
$categoryidid = 0;
if($values["categoryid"])
	$categoryidid = $values["categoryid"];
$rs2 = DB::Select("todocategories", array("id"=>$categoryidid ));
$data2 = $rs2->fetchAssoc();
$categoryid = $data2["color"];

if($assign){
	if($data["avatar"]){
		$avatar = my_json_decode($data["avatar"]);
		$ava = "<img class='assignUser' title='".$data["fullname"]." (".$data[$cUserNameField].")' src='mfhandler.php?file=".$avatar[0]["usrName"]."&table=".$cLoginTable."&field=avatar&pageType=list&page=list&key1=".$assign."&nodisp=1'>";
	}
	else{
		if($data["fullname"])
			$ava = "<span class='assignUser assignText' title='".$data["fullname"]." (".$data[$cUserNameField].")'>".strtoupper(substr($data["fullname"],0,1))."</span>";
		else
			$ava = "<span class='assignUser assignText' title='".$data["fullname"]." (".$data[$cUserNameField].")'>".strtoupper(substr($data[$cUserNameField],0,1))."</span>";
	}
}
?>
<script>
var elem = window.parent.document.querySelector("[data-eid=item_<?php echo $values["id"]?>]");
if(elem){
	elem.querySelector(".title_row").innerHTML = "<?php echo $cardname?>";
	elem.querySelector(".title_row").setAttribute("value","<?php echo $cardname ?>");
	elem.querySelector(".title_row").setAttribute("bgcolor","<?php echo $categoryidid ?>");
	elem.querySelector(".bgcolor_row").style.backgroundColor = "<?php echo $categoryid?>";
}
<?php
if($oldassign){
?>
if(elem)
	elem.querySelector(".divAssignUser").remove(); //1
<?php
}
if($assign){
?>
if(elem){
	var newNode = document.createElement('div');
	newNode.className = 'divAssignUser';
	newNode.innerHTML = "<?php echo $ava;?>";
	newNode.setAttribute("id","assignUser_<?php echo $values["id"];?>");
	referenceNode = elem.querySelector("#editrow_<?php echo $values["id"]?>");
	referenceNode.parentNode.insertBefore(newNode, referenceNode.nextSibling);
}
<?php
}
?>
window.parent.$(".close").click();

</script>
<?php
exit();


;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesView(&$values, $pageObject)
{

		include_once("todolist_custom.php");
$values["cardname"] = prepareCard($values);
if(!$values["assign"])
	$values["assign"] = "";
;
} // function ProcessValuesView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$xt->assign("header","");


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		$xt->assign("header","");
if($values["categoryid"]){
	$rs = DB::Select("todocategories", array("id"=>$values["categoryid"]));
	if($data = $rs->fetchAssoc())
		$pageObject->setProxyValue("color",$data["color"]);
}
$pageObject->setProxyValue("assign",$values["assign"]);

$perm = Security::getPermissions("todocards");
if(!$perm["E"] || $values["ownerid"]!=$_SESSION["UserID"])
	$pageObject->hideItem("custom_button");


;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>