<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => true ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'login_message',
'login_welcome' ),
'top' => array( 'image',
'text',
'login-logo' ),
'grid' => array( 'username_label',
'username',
'password_label',
'password',
'remember_password',
'guest_login',
'captcha' ),
'footer' => array( 'login_button',
'loginform_register_link',
'login_remind' ),
'superbottom' => array( 'text1' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'login_message' => 'above-grid',
'login_welcome' => 'above-grid',
'image' => 'top',
'text' => 'top',
'login-logo' => 'top',
'username_label' => 'grid',
'username' => 'grid',
'password_label' => 'grid',
'password' => 'grid',
'remember_password' => 'grid',
'guest_login' => 'grid',
'captcha' => 'grid',
'login_button' => 'footer',
'loginform_register_link' => 'footer',
'login_remind' => 'footer',
'text1' => 'superbottom' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'username_label' => array( 'username_label' ),
'username' => array( 'username' ),
'password_label' => array( 'password_label' ),
'password' => array( 'password' ),
'login_message' => array( 'login_message' ),
'login_button' => array( 'login_button' ),
'guest_login' => array( 'guest_login' ),
'remember_password' => array( 'remember_password' ),
'login-logo' => array( 'login-logo' ),
'login_welcome' => array( 'login_welcome' ),
'loginform_register_link' => array( 'loginform_register_link' ),
'text' => array( 'text',
'text1' ),
'image' => array( 'image' ),
'login_remind' => array( 'login_remind' ),
'captcha' => array( 'captcha' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'login',
'type' => 'login',
'layoutId' => 'pretty1',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'login-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ),
'align' => 'center' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'login_message' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'login_welcome' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'plogin-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'image',
'text',
'login-logo' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'align' => 'center',
'bold' => true ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'plogin-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'username_label',
'username' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'password_label',
'password' ) ),
'c4' => array( 'model' => 'c4',
'items' => array( 'remember_password' ) ),
'c6' => array( 'model' => 'c6',
'items' => array( 'guest_login' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'captcha' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'plogin-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'login_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_register_link',
'login_remind' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'superbottom' => array( 'modelId' => 'plogin-superbottom',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text1' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'username_label' => array( 'type' => 'username_label' ),
'username' => array( 'type' => 'username' ),
'password_label' => array( 'type' => 'password_label' ),
'password' => array( 'type' => 'password' ),
'login_message' => array( 'type' => 'login_message' ),
'login_button' => array( 'type' => 'login_button' ),
'guest_login' => array( 'type' => 'guest_login' ),
'remember_password' => array( 'type' => 'remember_password' ),
'login-logo' => array( 'type' => 'login-logo',
'font-size' => '24px' ),
'login_welcome' => array( 'type' => 'login_welcome',
'bold' => true,
'font-size' => '22px' ),
'loginform_register_link' => array( 'type' => 'loginform_register_link' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Welcome To ',
'type' => 0 ),
'editedByRte' => false,
'font-size' => '22px',
'bold' => true,
'color' => '#ff0007' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'dereja.png',
'source' => 2 ),
'width' => '100px',
'height' => '100px' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'This Application is for Internal Use only!
It can only be accessed by an authorized personel!',
'type' => 0 ),
'editedByRte' => false,
'color' => '#8e8d8d' ),
'login_remind' => array( 'type' => 'login_remind' ),
'captcha' => array( 'type' => 'captcha' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image',
'fullSize' => true,
'image' => array( 'source' => 1,
'image' => 'windows-SwHvzwEzCfA-unsplash.jpg' ) ),
'imageBgColor' => '#ffffff',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>