<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'image',
'register_activate_message',
'register_activated_message' ),
'supertop' => array( 'text' ),
'top' => array( 'register_success_header' ),
'grid' => array( 'register_proceed',
'register_close' ),
'footer' => array(  ) ),
'formXtTags' => array( 'footer' => array(  ) ),
'itemForms' => array( 'image' => 'above-grid',
'register_activate_message' => 'above-grid',
'register_activated_message' => 'above-grid',
'text' => 'supertop',
'register_success_header' => 'top',
'register_proceed' => 'grid',
'register_close' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'register_proceed' => array( 'register_proceed' ),
'register_success_header' => array( 'register_success_header' ),
'register_close' => array( 'register_close' ),
'image' => array( 'image' ),
'text' => array( 'text' ),
'register_activate_message' => array( 'register_activate_message' ),
'register_activated_message' => array( 'register_activated_message' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array( 'register_activate_message' => array( 'tag' => 'REGISTER_ACTIVATE',
'type' => 2 ) ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'register_success',
'type' => 'register_success',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'register_success-above',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'register_activate_message',
'register_activated_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'register_success-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'register_success_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'register_success-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'register_proceed',
'register_close' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'register_success-footer',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'register_proceed' => array( 'type' => 'register_proceed' ),
'register_success_header' => array( 'type' => 'register_success_header' ),
'register_close' => array( 'type' => 'register_close' ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'dereja.png',
'source' => 2 ) ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p class="ql-align-center"><strong style="color: rgb(255, 0, 0);"><img width="143" height="54" alt="Dereja M&amp;E System" src="./images/derejalogo.svg"></strong></p><h3 class="ql-align-center"><strong style="color: rgb(255, 102, 0);">M</strong><strong style="color: rgb(255, 0, 0);">&amp;</strong><strong style="color: rgb(255, 102, 0);">E</strong><strong> </strong><strong style="color: rgb(255, 0, 0);">System</strong></h3>',
'type' => 0 ),
'editedByRte' => true ),
'register_activate_message' => array( 'type' => 'register_activate_message' ),
'register_activated_message' => array( 'type' => 'register_activated_message' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>