<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'image' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'events',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'trainings',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'event_participants',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_participants',
'page' => 'list' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Companies',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Candidate_Employment_Tracker',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'CompanySectors',
'page' => 'list' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Jobs',
'page' => 'list' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Job_Categories',
'page' => 'list' ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Job_Types',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'regions',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cities',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'sub_cities',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'zones',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_services',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_event_services',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_training_services',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'institution_types',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'departments',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'minor_major',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'education_levels',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'skills',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_information_sources',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'it_related_skills',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'industry_specific_skills',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_types',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'professions',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_venues',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'participant_organization_types',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_organizers',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_city_towns',
'page' => 'list' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'program_areas',
'page' => 'list' ),
'welcome_item33' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Disability_Types',
'page' => 'list' ),
'welcome_item34' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Trainer',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu',
'loginform_login',
'username_button' ),
'above-grid' => array( 'image' ),
'grid' => array( 'welcome_item',
'welcome_item3',
'welcome_item4',
'welcome_item1',
'welcome_item2',
'welcome_item28',
'welcome_item27',
'welcome_item32',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item6',
'welcome_item5',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item15',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item23',
'welcome_item22',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item33',
'welcome_item34' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'image' => 'above-grid',
'welcome_item' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item28' => 'grid',
'welcome_item27' => 'grid',
'welcome_item32' => 'grid',
'welcome_item29' => 'grid',
'welcome_item30' => 'grid',
'welcome_item31' => 'grid',
'welcome_item6' => 'grid',
'welcome_item5' => 'grid',
'welcome_item7' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item15' => 'grid',
'welcome_item14' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item18' => 'grid',
'welcome_item19' => 'grid',
'welcome_item20' => 'grid',
'welcome_item21' => 'grid',
'welcome_item23' => 'grid',
'welcome_item22' => 'grid',
'welcome_item24' => 'grid',
'welcome_item25' => 'grid',
'welcome_item26' => 'grid',
'welcome_item33' => 'grid',
'welcome_item34' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'menu' => array( 'menu' ),
'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item6',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32',
'welcome_item33',
'welcome_item34' ),
'image' => array( 'image' ),
'logo' => array( 'logo' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'bold' => true ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'bold' => true ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item3',
'welcome_item4',
'welcome_item1',
'welcome_item2',
'welcome_item28',
'welcome_item27',
'welcome_item32',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item6',
'welcome_item5',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item15',
'welcome_item14',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item23',
'welcome_item22',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item33',
'welcome_item34' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'menu' => array( 'type' => 'menu',
'background' => '#f7f7f7',
'menuId' => 'secondary',
'color' => '#700000',
'bold' => true ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates',
'linkPage' => 'list',
'linkText' => array( 'table' => 'candidates',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'users' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'event_participants',
'linkPage' => 'list',
'linkText' => array( 'table' => 'event_participants',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'user' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_participants',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_participants',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'user' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'events',
'linkPage' => 'list',
'linkText' => array( 'table' => 'events',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'trainings',
'linkPage' => 'list',
'linkText' => array( 'table' => 'trainings',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'book' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cities',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'location-arrow' ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'regions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'regions',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'map-pin' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'sub_cities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'sub_cities',
'type' => 6 ),
'background' => '#B22222',
'linkIcon' => array( 'fa' => 'location-arrow' ),
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'zones',
'linkPage' => 'list',
'linkText' => array( 'table' => 'zones',
'type' => 6 ),
'background' => '#E07878',
'linkIcon' => array( 'fa' => 'location-arrow' ),
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_services',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_services',
'type' => 6 ),
'background' => '#BC8F8F',
'linkIcon' => array( 'fa' => 'gear' ),
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_event_services',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_event_services',
'type' => 6 ),
'background' => '#EDCA00',
'linkIcon' => array( 'fa' => 'gears' ),
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_training_services',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_training_services',
'type' => 6 ),
'background' => '#D2AF80',
'linkIcon' => array( 'fa' => 'gears' ),
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'institution_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'institution_types',
'type' => 6 ),
'background' => '#4682B4',
'linkIcon' => array( 'fa' => 'institution' ),
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'departments',
'linkPage' => 'list',
'linkText' => array( 'table' => 'departments',
'type' => 6 ),
'background' => '#DC143C',
'linkIcon' => array( 'fa' => 'building-o' ),
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'education_levels',
'linkPage' => 'list',
'linkText' => array( 'table' => 'education_levels',
'type' => 6 ),
'background' => '#E67349',
'linkIcon' => array( 'fa' => 'graduation-cap' ),
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'minor_major',
'linkPage' => 'list',
'linkText' => array( 'table' => 'minor_major',
'type' => 6 ),
'background' => '#DB7093',
'linkIcon' => array( 'fa' => 'paper-plane-o' ),
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'skills',
'linkPage' => 'list',
'linkText' => array( 'table' => 'skills',
'type' => 6 ),
'background' => '#D2691E',
'linkIcon' => array( 'glyph' => 'list-alt' ),
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_information_sources',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_information_sources',
'type' => 6 ),
'background' => '#2F4F4F',
'linkIcon' => array( 'fa' => 'info' ),
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'it_related_skills',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'IT Related Skills' ),
'background' => '#EDCA00',
'linkIcon' => array( 'fa' => 'laptop' ),
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'industry_specific_skills',
'linkPage' => 'list',
'linkText' => array( 'table' => 'industry_specific_skills',
'type' => 6 ),
'background' => '#E07878',
'linkIcon' => array( 'fa' => 'file' ),
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_types',
'type' => 6 ),
'background' => '#B22222',
'linkIcon' => array( 'fa' => 'magic' ),
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'professions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'professions',
'type' => 6 ),
'background' => '#2F4F4F',
'linkIcon' => array( 'fa' => 'certificate' ),
'linkType' => 0 ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'participant_organization_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'participant_organization_types',
'type' => 6 ),
'background' => '#6B8E23',
'linkIcon' => array( 'fa' => 'first-order' ),
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_venues',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_venues',
'type' => 6 ),
'background' => '#BC8F8F',
'linkIcon' => array( 'fa' => 'compass' ),
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_organizers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_organizers',
'type' => 6 ),
'background' => '#DAA520',
'linkIcon' => array( 'glyph' => 'screenshot' ),
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_city_towns',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_city_towns',
'type' => 6 ),
'background' => '#EDCA00',
'linkIcon' => array( 'glyph' => 'globe' ),
'linkType' => 0 ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'program_areas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'program_areas',
'type' => 6 ),
'background' => '#4169E1',
'linkIcon' => array( 'fa' => 'tasks' ),
'linkType' => 0 ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Candidate_Employment_Tracker',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Candidate_Employment_Tracker',
'type' => 6 ),
'background' => '#D2AF80',
'linkIcon' => array( 'fa' => 'dashboard' ),
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Companies',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Companies',
'type' => 6 ),
'background' => '#EDCA00',
'linkIcon' => array( 'fa' => 'suitcase' ),
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Jobs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Jobs',
'type' => 6 ),
'background' => '#6493EA',
'linkIcon' => array( 'fa' => 'briefcase' ),
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Job_Categories',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Job_Categories',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Job_Types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Job_Types',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'CompanySectors',
'linkPage' => 'list',
'linkText' => array( 'table' => 'CompanySectors',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item33' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Disability_Types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Disability_Types',
'type' => 6 ),
'background' => '#6DA5C8',
'linkIcon' => array( 'fa' => 'wheelchair' ),
'linkType' => 0 ),
'image' => array( 'type' => 'image',
'width' => '47px',
'height' => '47px',
'image' => array( 'image' => 'dereja.png',
'source' => 2 ) ),
'logo' => array( 'type' => 'logo' ),
'welcome_item34' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Trainer',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Trainer',
'type' => 6 ),
'background' => '#CD853F',
'linkType' => 0 ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ),
'bold' => true,
'buttonStyle' => 'primary' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false,
'icon' => array( 'glyph' => 'log-in' ),
'bold' => true,
'color' => '#ffffff',
'buttonStyle' => 'primary',
'buttonSize' => 'normal' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'standard',
'menuWidth' => 'full',
'pageAlign' => 'center',
'fixedTopbar' => true,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>