<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'text' => array( 'menutItem' => false ),
'exit_adminarea_link' => array( 'menutItem' => false ),
'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'notifications' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'loginform_register' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'welcome_group1' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'event_participants',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_participants',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'website_data',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Candidate_Employment_Tracker',
'page' => 'list' ) ) ),
'welcome_group2' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item53' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_view',
'page' => 'report' ),
'welcome_item54' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_view',
'page' => 'masterreport' ),
'welcome_item69' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_aggrigated',
'page' => 'list' ),
'welcome_item55' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'event_participants_view',
'page' => 'report' ),
'welcome_item56' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_participants_view',
'page' => 'report' ) ) ),
'welcome_group9' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item52' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dashboards',
'page' => 'list' ),
'welcome_item43' => array( 'menutItem' => true,
'group' => false,
'linkType' => 1,
'items' => null,
'url' => './webreport.php' ),
'welcome_item57' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'AIO_Reporting_Dashboard',
'page' => 'dashboard' ),
'welcome_item38' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'webreports',
'page' => 'list' ),
'welcome_item39' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'webreport_style',
'page' => 'list' ),
'welcome_item40' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'webreport_sql',
'page' => 'list' ),
'welcome_item41' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'webreport_admin',
'page' => 'list' ),
'welcome_item42' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'webreports_view',
'page' => 'report' ) ) ),
'welcome_group5' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item70' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dashboards',
'page' => 'list',
'pageId' => 'AIO_Indicators_Aggregated' ),
'welcome_item63' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_by_gender',
'page' => 'chart' ),
'welcome_item60' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'event_participants_by_events',
'page' => 'chart' ),
'welcome_item61' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_participants_by_trainings',
'page' => 'chart' ),
'welcome_item62' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_reports',
'page' => 'chart' ),
'welcome_item59' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'candidates_by_region',
'page' => 'chart' ) ) ),
'welcome_group3' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'trainings',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'events',
'page' => 'list' ),
'welcome_item37' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Trainer',
'page' => 'list' ),
'welcome_item33' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_organizers',
'page' => 'list' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_types',
'page' => 'list' ),
'welcome_item34' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_city_towns',
'page' => 'list' ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'training_venues',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_training_services',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_event_services',
'page' => 'list' ) ) ),
'welcome_group7' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'departments',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'institution_types',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'minor_major',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'education_levels',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'skills',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'it_related_skills',
'page' => 'list' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'industry_specific_skills',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'participant_organization_types',
'page' => 'list' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'professions',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Languages',
'page' => 'list' ) ) ),
'welcome_group6' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'regions',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cities',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'sub_cities',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'zones',
'page' => 'list' ) ) ),
'welcome_group4' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Jobs',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Job_Categories',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Job_Types',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Job_Fair',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Companies',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'CompanySectors',
'page' => 'list' ) ) ),
'welcome_group' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item44' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'main',
'page' => 'list' ),
'welcome_item45' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'kbarticles',
'page' => 'list' ),
'welcome_item46' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'kbcategories',
'page' => 'list' ),
'welcome_item47' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'kbusers',
'page' => 'list' ),
'welcome_item48' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'faicons',
'page' => 'list' ),
'welcome_item49' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'admin_comments',
'page' => 'list' ) ) ),
'welcome_group10' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item58' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'list' ),
'welcome_item64' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'Chat' ),
'welcome_item65' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'Project_Manager' ),
'welcome_item68' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'Survey' ),
'welcome_item66' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'Project_Manager' ),
'welcome_item67' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'utilities',
'page' => 'list',
'pageId' => 'document_manager' ) ) ),
'welcome_group8' => array( 'menutItem' => true,
'group' => true,
'items' => array( 'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_information_sources',
'page' => 'list' ),
'welcome_item36' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Disability_Types',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dereja_services',
'page' => 'list' ),
'welcome_item35' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'program_areas',
'page' => 'list' ),
'welcome_item50' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'derejame_audit',
'page' => 'list' ),
'welcome_item51' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'dashboard_pages',
'page' => 'list' ) ) ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'exit_adminarea_link',
'text' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'loginform_register',
'username_button' ),
'left' => array( 'menu',
'logo',
'expand_button' ),
'grid' => array( 'welcome_group3',
'welcome_group10',
'welcome_group1',
'welcome_group',
'welcome_group2',
'welcome_group7',
'welcome_group6',
'welcome_group9',
'welcome_group4',
'welcome_group8',
'welcome_group5' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'exit_adminarea_link' => 'above-grid',
'text' => 'above-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'loginform_register' => 'supertop',
'username_button' => 'supertop',
'menu' => 'left',
'logo' => 'left',
'expand_button' => 'left',
'welcome_group3' => 'grid',
'welcome_group10' => 'grid',
'welcome_group1' => 'grid',
'welcome_group' => 'grid',
'welcome_group2' => 'grid',
'welcome_group7' => 'grid',
'welcome_group6' => 'grid',
'welcome_group9' => 'grid',
'welcome_group4' => 'grid',
'welcome_group8' => 'grid',
'welcome_group5' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'exit_adminarea_link' => array( 'exit_adminarea_link' ),
'welcome_group' => array( 'welcome_group1',
'welcome_group9',
'welcome_group6',
'welcome_group8',
'welcome_group3',
'welcome_group7',
'welcome_group4',
'welcome_group',
'welcome_group2',
'welcome_group5',
'welcome_group10' ),
'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item5',
'welcome_item3',
'welcome_item52',
'welcome_item43',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42',
'welcome_item17',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item26',
'welcome_item36',
'welcome_item18',
'welcome_item35',
'welcome_item50',
'welcome_item51',
'welcome_item7',
'welcome_item37',
'welcome_item33',
'welcome_item29',
'welcome_item34',
'welcome_item31',
'welcome_item20',
'welcome_item6',
'welcome_item19',
'welcome_item22',
'welcome_item21',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item27',
'welcome_item28',
'welcome_item32',
'welcome_item30',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item4',
'welcome_item8',
'welcome_item9',
'welcome_item44',
'welcome_item45',
'welcome_item46',
'welcome_item47',
'welcome_item48',
'welcome_item49',
'welcome_item53',
'welcome_item54',
'welcome_item55',
'welcome_item56',
'welcome_item57',
'welcome_item59',
'welcome_item60',
'welcome_item61',
'welcome_item62',
'welcome_item63',
'welcome_item58',
'welcome_item64',
'welcome_item65',
'welcome_item66',
'welcome_item67',
'welcome_item68',
'welcome_item69',
'welcome_item70' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'menu' => array( 'menu' ),
'logo' => array( 'logo' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'loginform_register' => array( 'loginform_register' ),
'notifications' => array( 'notifications' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'text' => array( 'text' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ),
array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right',
'orientation' => 'horizontal' ),
'c1' => array( 'model' => 'c1',
'items' => array( 'exit_adminarea_link' ),
'align' => 'right',
'orientation' => 'horizontal' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'loginform_register',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ),
'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c24',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c23' ),
array( 'cell' => 'c27',
'rowspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c30' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c19',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 5 ),
array( 'cell' => 'c4',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'rowspan' => 4 ),
array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c12',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c21',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'c2',
'colspan' => 3 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_group3' ),
'align' => 'left',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_group10' ),
'align' => 'right',
'background' => 'transparent' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ),
'pageBreak' => 'after' ),
'c10' => array( 'model' => 'c1',
'items' => array( 'welcome_group1' ),
'align' => 'left',
'background' => 'transparent' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'welcome_group' ),
'align' => 'left' ),
'c13' => array( 'model' => 'c1',
'items' => array(  ) ),
'c17' => array( 'model' => 'c1',
'items' => array(  ),
'pageBreak' => 'after' ),
'c21' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ),
'pageBreak' => 'after' ),
'c23' => array( 'model' => 'c1',
'items' => array( 'welcome_group2' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'welcome_group7' ),
'align' => 'right',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c24' => array( 'model' => 'c1',
'items' => array(  ) ),
'c22' => array( 'model' => 'c1',
'items' => array( 'welcome_group6' ),
'align' => 'right',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c27' => array( 'model' => 'c1',
'items' => array( 'welcome_group9' ),
'align' => 'right',
'background' => 'transparent' ),
'c25' => array( 'model' => 'c1',
'items' => array( 'welcome_group4' ),
'align' => 'right',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c5' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'left',
'background' => 'transparent' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'welcome_group8' ),
'align' => 'right',
'background' => 'transparent' ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ),
'c12' => array( 'model' => 'c1',
'items' => array(  ) ),
'c14' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center',
'background' => 'transparent' ),
'c26' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'right',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c15' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center',
'background' => 'transparent',
'pageBreak' => 'before' ),
'c20' => array( 'model' => 'c1',
'items' => array(  ),
'pageBreak' => 'after' ),
'c30' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c16' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'left',
'background' => 'transparent' ),
'c19' => array( 'model' => 'c1',
'items' => array( 'welcome_group5' ),
'align' => 'left',
'background' => 'transparent' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'exit_adminarea_link' => array( 'type' => 'exit_adminarea_link' ),
'welcome_group1' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Candidates Data Managment' ),
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item5',
'welcome_item3' ),
'linkIcon' => array( 'fa' => 'users' ),
'background' => 'transparent' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates',
'linkPage' => 'list',
'linkText' => array( 'table' => 'candidates',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'users' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'event_participants',
'linkPage' => 'list',
'linkText' => array( 'table' => 'event_participants',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'user' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_participants',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_participants',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'user' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'website_data',
'linkPage' => 'list',
'linkText' => array( 'table' => 'website_data',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'internet-explorer' ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Candidate_Employment_Tracker',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Employment Tracker' ),
'linkIcon' => array( 'fa' => 'arrows' ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_group9' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Data Visualization and Reports' ),
'items' => array( 'welcome_item52',
'welcome_item43',
'welcome_item57',
'welcome_item38',
'welcome_item39',
'welcome_item40',
'welcome_item41',
'welcome_item42' ),
'linkIcon' => array( 'fa' => 'bar-chart' ) ),
'welcome_item52' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dashboards',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dashboards',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0,
'linkIcon' => array( 'fa' => 'line-chart' ) ),
'welcome_item43' => array( 'type' => 'welcome_item',
'linkUrl' => './webreport.php',
'linkText' => array( 'type' => 0,
'text' => 'Web Reports Builder' ),
'linkIcon' => array( 'fa' => 'pie-chart' ),
'linkType' => 1 ),
'welcome_item38' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'webreports',
'linkPage' => 'list',
'linkText' => array( 'table' => 'webreports',
'type' => 6 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item39' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'webreport_style',
'linkPage' => 'list',
'linkText' => array( 'table' => 'webreport_style',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item40' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'webreport_sql',
'linkPage' => 'list',
'linkText' => array( 'table' => 'webreport_sql',
'type' => 6 ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item41' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'webreport_admin',
'linkPage' => 'list',
'linkText' => array( 'table' => 'webreport_admin',
'type' => 6 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item42' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'webreports_view',
'linkPage' => 'report',
'linkText' => array( 'table' => 'webreports_view',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_group6' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Localization and Regional Data Management' ),
'items' => array( 'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16' ),
'linkIcon' => array( 'glyph' => 'globe' ) ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Languages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Languages',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'language' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'regions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'regions',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'map-pin' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cities',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'location-arrow' ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'sub_cities',
'linkPage' => 'list',
'linkText' => array( 'table' => 'sub_cities',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'location-arrow' ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'zones',
'linkPage' => 'list',
'linkText' => array( 'table' => 'zones',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'location-arrow' ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_group8' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Miscellaneous' ),
'items' => array( 'welcome_item26',
'welcome_item36',
'welcome_item18',
'welcome_item35',
'welcome_item50',
'welcome_item51' ) ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_information_sources',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Information Sources' ),
'linkIcon' => array( 'fa' => 'info' ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item36' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Disability_Types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Disability_Types',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'wheelchair' ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_services',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_services',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'gear' ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item35' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'program_areas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'program_areas',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'tasks' ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item50' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'derejame_audit',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'System Users Audit' ),
'background' => '#8FBC8B',
'linkType' => 0,
'linkIcon' => array( 'fa' => 'user-plus' ) ),
'welcome_item51' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dashboard_pages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dashboard_pages',
'type' => 6 ),
'background' => '#DC143C',
'linkType' => 0 ),
'welcome_group3' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Training and Events Data Management' ),
'items' => array( 'welcome_item7',
'welcome_item6',
'welcome_item37',
'welcome_item33',
'welcome_item29',
'welcome_item34',
'welcome_item31',
'welcome_item20',
'welcome_item19' ),
'linkIcon' => array( 'glyph' => 'calendar' ) ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'trainings',
'linkPage' => 'list',
'linkText' => array( 'table' => 'trainings',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'book' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item37' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Trainer',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Trainer',
'type' => 6 ),
'background' => '#CD853F',
'linkType' => 0,
'linkIcon' => array( 'glyph' => 'user' ) ),
'welcome_item33' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_organizers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_organizers',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'screenshot' ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_types',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'magic' ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item34' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_city_towns',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_city_towns',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'globe' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_venues',
'linkPage' => 'list',
'linkText' => array( 'table' => 'training_venues',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'compass' ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_training_services',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Training Services' ),
'linkIcon' => array( 'fa' => 'gears' ),
'background' => '#D2AF80',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'events',
'linkPage' => 'list',
'linkText' => array( 'table' => 'events',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dereja_event_services',
'linkPage' => 'list',
'linkText' => array( 'table' => 'dereja_event_services',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'gears' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_group7' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Education and Skills Data Management' ),
'items' => array( 'welcome_item22',
'welcome_item21',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item27',
'welcome_item28',
'welcome_item32',
'welcome_item30',
'welcome_item17' ),
'linkIcon' => array( 'fa' => 'pencil' ) ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'departments',
'linkPage' => 'list',
'linkText' => array( 'table' => 'departments',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'building-o' ),
'background' => '#DC143C',
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'institution_types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'institution_types',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'institution' ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'minor_major',
'linkPage' => 'list',
'linkText' => array( 'table' => 'minor_major',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'paper-plane-o' ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'education_levels',
'linkPage' => 'list',
'linkText' => array( 'table' => 'education_levels',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'graduation-cap' ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'skills',
'linkPage' => 'list',
'linkText' => array( 'table' => 'skills',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'list-alt' ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'it_related_skills',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'IT Related Skills' ),
'linkIcon' => array( 'fa' => 'laptop' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'industry_specific_skills',
'linkPage' => 'list',
'linkText' => array( 'table' => 'industry_specific_skills',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'file' ),
'background' => '#E07878',
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'participant_organization_types',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Participant Org Types' ),
'linkIcon' => array( 'fa' => 'first-order' ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'professions',
'linkPage' => 'list',
'linkText' => array( 'table' => 'professions',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'certificate' ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_group4' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Jobs and Companies Data Management' ),
'items' => array( 'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item4',
'welcome_item8',
'welcome_item9' ),
'linkIcon' => array( 'glyph' => 'briefcase' ) ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Jobs',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Jobs',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'briefcase' ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Job_Categories',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Job_Categories',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tags' ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Job_Types',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Job_Types',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tag' ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Job_Fair',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Job_Fair',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'connectdevelop' ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Companies',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Companies',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'suitcase' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'CompanySectors',
'linkPage' => 'list',
'linkText' => array( 'table' => 'CompanySectors',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'level-up' ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_group' => array( 'type' => 'welcome_group',
'linkText' => array( 'text' => 'KnowledgeBase',
'type' => 0 ),
'items' => array( 'welcome_item44',
'welcome_item45',
'welcome_item46',
'welcome_item47',
'welcome_item48',
'welcome_item49' ) ),
'welcome_item44' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'main',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Main' ),
'linkIcon' => array( 'fa' => 'book' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#DAA520',
'linkType' => 0 ),
'welcome_item45' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'kbarticles',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Articles' ),
'linkIcon' => array( 'fa' => 'newspaper-o' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item46' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'kbcategories',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Categories' ),
'linkIcon' => array( 'fa' => 'stack-exchange' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item47' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'kbusers',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Users' ),
'linkIcon' => array( 'glyph' => 'user' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item48' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'faicons',
'linkPage' => 'list',
'linkText' => array( 'table' => 'faicons',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'picture' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item49' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'admin_comments',
'linkPage' => 'list',
'linkText' => array( 'table' => 'admin_comments',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'text-background' ),
'background' => '#3CB371',
'linkType' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'menu' => array( 'type' => 'menu',
'background' => '#f7f7f7',
'menuId' => 'DerejaMenuSet',
'color' => '#700000',
'bold' => true ),
'logo' => array( 'type' => 'logo',
'mobileDisplay' => 'both',
'background' => 'transparent' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ),
'bold' => true,
'buttonStyle' => 'primary' ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false,
'icon' => array( 'glyph' => 'log-in' ),
'bold' => true,
'color' => '#ffffff',
'buttonStyle' => 'primary',
'buttonSize' => 'normal' ),
'loginform_register' => array( 'type' => 'loginform_register' ),
'notifications' => array( 'type' => 'notifications' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item53' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_view',
'linkPage' => 'report',
'linkText' => array( 'type' => 0,
'text' => 'Candidates Report' ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item54' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_view',
'linkPage' => 'masterreport',
'linkText' => array( 'type' => 0,
'text' => 'Candidates Master Report' ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_group2' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Tabular Reports' ),
'linkIcon' => array( 'fa' => 'table' ),
'items' => array( 'welcome_item53',
'welcome_item54',
'welcome_item69',
'welcome_item55',
'welcome_item56' ),
'bold' => true ),
'welcome_item55' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'event_participants_view',
'linkPage' => 'report',
'linkText' => array( 'type' => 0,
'text' => 'Event Participants Report' ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item56' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_participants_view',
'linkPage' => 'report',
'linkText' => array( 'type' => 0,
'text' => 'Training Participants Report' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item57' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'AIO_Reporting_Dashboard',
'linkPage' => 'dashboard',
'linkText' => array( 'type' => 0,
'text' => 'AIO Reporting Grid' ),
'background' => '#DB7093',
'linkType' => 0,
'linkIcon' => array( 'fa' => 'th' ) ),
'welcome_item59' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_by_region',
'linkPage' => 'chart',
'linkText' => array( 'type' => 0,
'text' => 'Candidates Region Chart' ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item60' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'event_participants_by_events',
'linkPage' => 'chart',
'linkText' => array( 'type' => 0,
'text' => 'Event Participants Chart' ),
'background' => '#6493EA',
'linkType' => 0 ),
'welcome_item61' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'training_participants_by_trainings',
'linkPage' => 'chart',
'linkText' => array( 'type' => 0,
'text' => 'Training Participants Chart' ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_group5' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Charts' ),
'linkIcon' => array( 'fa' => 'linode' ),
'items' => array( 'welcome_item70',
'welcome_item63',
'welcome_item60',
'welcome_item61',
'welcome_item62',
'welcome_item59' ) ),
'welcome_item62' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_reports',
'linkPage' => 'chart',
'linkText' => array( 'table' => 'candidates_reports',
'type' => 6 ),
'background' => '#3CB371',
'linkType' => 0 ),
'welcome_item63' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_by_gender',
'linkPage' => 'chart',
'linkText' => array( 'type' => 0,
'text' => 'Candidates Gender Chart' ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item58' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'AIO Utilities' ),
'background' => '#ffac00',
'linkType' => 0,
'linkPageId' => 'list',
'linkIcon' => array( 'glyph' => 'th-large' ) ),
'welcome_group10' => array( 'type' => 'welcome_group',
'linkText' => array( 'type' => 0,
'text' => 'Utilities' ),
'linkIcon' => array( 'fa' => 'server' ),
'items' => array( 'welcome_item58',
'welcome_item64',
'welcome_item65',
'welcome_item68',
'welcome_item66',
'welcome_item67' ) ),
'welcome_item64' => array( 'type' => 'welcome_item',
'linkUrl' => 'https://website/page',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Chat' ),
'linkIcon' => array( 'fa' => 'comments' ),
'linkType' => 0,
'linkPageId' => 'Chat' ),
'welcome_item65' => array( 'type' => 'welcome_item',
'linkUrl' => 'https://website/page',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Project Managment' ),
'linkIcon' => array( 'fa' => 'braille' ),
'linkType' => 0,
'linkPageId' => 'Project_Manager' ),
'welcome_item66' => array( 'type' => 'welcome_item',
'linkUrl' => 'https://website/page',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Knowledge Managment' ),
'linkIcon' => array( 'fa' => 'book' ),
'linkType' => 0,
'linkPageId' => 'Project_Manager' ),
'welcome_item67' => array( 'type' => 'welcome_item',
'linkUrl' => 'https://website/page',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Document Manager' ),
'linkIcon' => array( 'fa' => 'files-o' ),
'linkType' => 0,
'linkPageId' => 'document_manager' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p class="ql-align-center"><a style="color: rgb(255, 0, 0);" href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><img width="143" height="54" alt="Dereja M&amp;E System" src="https://www.dereja.com/_nuxt/img/Logo-black.7a2b5f8.svg"></strong></a></p><p class="ql-align-center"><a style="color: rgb(255, 102, 0);" href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><u>M</u></strong></a><a style="color: rgb(255, 0, 0);" href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><u>&amp;</u></strong></a><a style="color: rgb(255, 102, 0);" href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><u>E</u></strong></a><a href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><u> </u></strong></a><a style="color: rgb(255, 0, 0);" href="./menu.php" target="_blank" rel="noopener noreferrer"><strong><u>System</u></strong></a></p><p><br></p>',
'type' => 0 ),
'editedByRte' => true ),
'welcome_item68' => array( 'type' => 'welcome_item',
'linkUrl' => 'https://website/page',
'linkTable' => 'utilities',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Survey Manager' ),
'linkIcon' => array( 'fa' => 'wpforms' ),
'linkType' => 0,
'linkPageId' => 'Survey' ),
'welcome_item69' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'candidates_aggrigated',
'linkPage' => 'list',
'linkText' => array( 'table' => 'candidates_aggrigated',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'sort-amount-desc' ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item70' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'dashboards',
'linkPage' => 'list',
'linkText' => array( 'type' => 0,
'text' => 'Indicators' ),
'background' => '#EDCA00',
'linkType' => 0,
'linkPageId' => 'AIO_Indicators_Aggregated',
'linkIcon' => array( 'fa' => 'info' ) ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>