<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'Candidate_Employment_Tracker' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'event_participants' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'training_participants' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'CandidateID',
'Employment_Position',
'Employment_Company',
'Employment_Status',
'Dereja_Information_Source',
'Dereja_web_profile_completion',
'Dereja_Event_Services',
'Dereja_Training_Services',
'Dereja_Services',
'Joined_Dereja_Services',
'Work_Experience',
'Upload_on_Tracker',
'DAAP_enrolled_2nd_Round',
'Exit_Exam_Status',
'Exit_Exam_Score',
'Job_Fair',
'Job_Fair_Clinic',
'DAAP_Completed_Courses',
'DAAP_Completed',
'DAAP_enrolled_1st Round',
'Attend_Employability_Skill',
'Campaign',
'GPA',
'Field_Of_Study',
'Certifications',
'IT_Related_Skills',
'Industry_Specific_Skills',
'English_Proficiency_Level',
'Languages',
'Skills',
'Enrollement_Type',
'Major',
'Minor',
'Department',
'Education_Level',
'Remark',
'Institution_Name',
'Institution_Type',
'Disability_Type_Other',
'Disability_Type',
'Email_Address',
'Phone_Number_Alternate',
'Phone_Number',
'House_No',
'Zone',
'Sub_City',
'City',
'DOB',
'Last_Name',
'Middle_Name',
'First_Name',
'StudentID',
'Intervention',
'Disability_Status',
'Year_of_graduation',
'Region',
'Sex',
'Woreda',
'Kebele',
'Employer_Sector',
'Salary',
'Career_Level_Of_Payment',
'Placement_Type',
'Placement_Duration',
'Date',
'Upload_on_Website' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CandidateID' => array( 'report_grid_field' ),
'Employment_Position' => array( 'report_grid_field56' ),
'Employment_Company' => array( 'report_grid_field55' ),
'Employment_Status' => array( 'report_grid_field54' ),
'Dereja_Information_Source' => array( 'report_grid_field53' ),
'Dereja_web_profile_completion' => array( 'report_grid_field52' ),
'Dereja_Event_Services' => array( 'report_grid_field51' ),
'Dereja_Training_Services' => array( 'report_grid_field50' ),
'Dereja_Services' => array( 'report_grid_field49' ),
'Joined_Dereja_Services' => array( 'report_grid_field48' ),
'Work_Experience' => array( 'report_grid_field47' ),
'Upload_on_Tracker' => array( 'report_grid_field46' ),
'DAAP_enrolled_2nd_Round' => array( 'report_grid_field45',
'report_group_field8' ),
'Exit_Exam_Status' => array( 'report_grid_field44',
'report_group_field13' ),
'Exit_Exam_Score' => array( 'report_grid_field43',
'report_group_field12' ),
'Job_Fair' => array( 'report_grid_field42',
'report_group_field16' ),
'Job_Fair_Clinic' => array( 'report_grid_field41',
'report_group_field17' ),
'DAAP_Completed_Courses' => array( 'report_grid_field40',
'report_group_field6' ),
'DAAP_Completed' => array( 'report_grid_field39',
'report_group_field5' ),
'DAAP_enrolled_1st Round' => array( 'report_grid_field38',
'report_group_field7' ),
'Attend_Employability_Skill' => array( 'report_grid_field37' ),
'Campaign' => array( 'report_grid_field36' ),
'GPA' => array( 'report_grid_field35',
'report_group_field14' ),
'Field_Of_Study' => array( 'report_grid_field34',
'report_group_field10' ),
'Certifications' => array( 'report_grid_field33' ),
'IT_Related_Skills' => array( 'report_grid_field32' ),
'Industry_Specific_Skills' => array( 'report_grid_field31' ),
'English_Proficiency_Level' => array( 'report_grid_field30' ),
'Languages' => array( 'report_grid_field29',
'report_group_field4' ),
'Skills' => array( 'report_grid_field28' ),
'Enrollement_Type' => array( 'report_grid_field27',
'report_group_field11' ),
'Major' => array( 'report_grid_field26' ),
'Minor' => array( 'report_grid_field25' ),
'Department' => array( 'report_grid_field24',
'report_group_field9' ),
'Education_Level' => array( 'report_grid_field23' ),
'Remark' => array( 'report_grid_field22' ),
'Institution_Name' => array( 'report_grid_field21' ),
'Institution_Type' => array( 'report_grid_field20' ),
'Disability_Type_Other' => array( 'report_grid_field19' ),
'Disability_Type' => array( 'report_grid_field18' ),
'Email_Address' => array( 'report_grid_field17' ),
'Phone_Number_Alternate' => array( 'report_grid_field16' ),
'Phone_Number' => array( 'report_grid_field15' ),
'House_No' => array( 'report_grid_field14' ),
'Zone' => array( 'report_grid_field13' ),
'Sub_City' => array( 'report_grid_field12' ),
'City' => array( 'report_grid_field11',
'report_group_field3' ),
'DOB' => array( 'report_grid_field10',
'report_group_field1' ),
'Last_Name' => array( 'report_grid_field9' ),
'Middle_Name' => array( 'report_grid_field8' ),
'First_Name' => array( 'report_grid_field7' ),
'StudentID' => array( 'report_grid_field6' ),
'Intervention' => array( 'report_grid_field5',
'report_group_field15' ),
'Disability_Status' => array( 'report_grid_field4' ),
'Year_of_graduation' => array( 'report_grid_field3',
'report_group_field18' ),
'Region' => array( 'report_grid_field2',
'report_group_field2' ),
'Sex' => array( 'report_grid_field1',
'report_group_field' ),
'Woreda' => array( 'report_grid_field57' ),
'Kebele' => array( 'report_grid_field58' ),
'Employer_Sector' => array( 'report_grid_field59' ),
'Salary' => array( 'report_grid_field60' ),
'Career_Level_Of_Payment' => array( 'report_grid_field61' ),
'Placement_Type' => array( 'report_grid_field62' ),
'Placement_Duration' => array( 'report_grid_field63' ),
'Date' => array( 'report_grid_field64' ),
'Upload_on_Website' => array( 'report_grid_field65' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'print_pdf' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6',
'report_group_field7',
'report_group_field8',
'report_group_field9',
'report_group_field10',
'report_group_field11',
'report_group_field12',
'report_group_field13',
'report_group_field14',
'report_group_field15',
'report_group_field16',
'report_group_field17',
'report_group_field18',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56',
'report_grid_field57',
'report_grid_field58',
'report_grid_field59',
'report_grid_field60',
'report_grid_field61',
'report_grid_field62',
'report_grid_field63',
'report_grid_field64',
'report_grid_field65' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'print_pdf' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_group_field5' => 'grid',
'report_group_field6' => 'grid',
'report_group_field7' => 'grid',
'report_group_field8' => 'grid',
'report_group_field9' => 'grid',
'report_group_field10' => 'grid',
'report_group_field11' => 'grid',
'report_group_field12' => 'grid',
'report_group_field13' => 'grid',
'report_group_field14' => 'grid',
'report_group_field15' => 'grid',
'report_group_field16' => 'grid',
'report_group_field17' => 'grid',
'report_group_field18' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field14' => 'grid',
'report_grid_field15' => 'grid',
'report_grid_field16' => 'grid',
'report_grid_field17' => 'grid',
'report_grid_field18' => 'grid',
'report_grid_field19' => 'grid',
'report_grid_field20' => 'grid',
'report_grid_field21' => 'grid',
'report_grid_field22' => 'grid',
'report_grid_field23' => 'grid',
'report_grid_field24' => 'grid',
'report_grid_field25' => 'grid',
'report_grid_field26' => 'grid',
'report_grid_field27' => 'grid',
'report_grid_field28' => 'grid',
'report_grid_field29' => 'grid',
'report_grid_field30' => 'grid',
'report_grid_field31' => 'grid',
'report_grid_field32' => 'grid',
'report_grid_field33' => 'grid',
'report_grid_field34' => 'grid',
'report_grid_field35' => 'grid',
'report_grid_field36' => 'grid',
'report_grid_field37' => 'grid',
'report_grid_field38' => 'grid',
'report_grid_field39' => 'grid',
'report_grid_field40' => 'grid',
'report_grid_field41' => 'grid',
'report_grid_field42' => 'grid',
'report_grid_field43' => 'grid',
'report_grid_field44' => 'grid',
'report_grid_field45' => 'grid',
'report_grid_field46' => 'grid',
'report_grid_field47' => 'grid',
'report_grid_field48' => 'grid',
'report_grid_field49' => 'grid',
'report_grid_field50' => 'grid',
'report_grid_field51' => 'grid',
'report_grid_field52' => 'grid',
'report_grid_field53' => 'grid',
'report_grid_field54' => 'grid',
'report_grid_field55' => 'grid',
'report_grid_field56' => 'grid',
'report_grid_field57' => 'grid',
'report_grid_field58' => 'grid',
'report_grid_field59' => 'grid',
'report_grid_field60' => 'grid',
'report_grid_field61' => 'grid',
'report_grid_field62' => 'grid',
'report_grid_field63' => 'grid',
'report_grid_field64' => 'grid',
'report_grid_field65' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field',
'report_grid_field56',
'report_grid_field55',
'report_grid_field54',
'report_grid_field53',
'report_grid_field52',
'report_grid_field51',
'report_grid_field50',
'report_grid_field49',
'report_grid_field48',
'report_grid_field47',
'report_grid_field46',
'report_grid_field45',
'report_grid_field44',
'report_grid_field43',
'report_grid_field42',
'report_grid_field41',
'report_grid_field40',
'report_grid_field39',
'report_grid_field38',
'report_grid_field37',
'report_grid_field36',
'report_grid_field35',
'report_grid_field34',
'report_grid_field33',
'report_grid_field32',
'report_grid_field31',
'report_grid_field30',
'report_grid_field29',
'report_grid_field28',
'report_grid_field27',
'report_grid_field26',
'report_grid_field25',
'report_grid_field24',
'report_grid_field23',
'report_grid_field22',
'report_grid_field21',
'report_grid_field20',
'report_grid_field19',
'report_grid_field18',
'report_grid_field17',
'report_grid_field16',
'report_grid_field15',
'report_grid_field14',
'report_grid_field13',
'report_grid_field12',
'report_grid_field11',
'report_grid_field10',
'report_grid_field9',
'report_grid_field8',
'report_grid_field7',
'report_grid_field6',
'report_grid_field5',
'report_grid_field4',
'report_grid_field3',
'report_grid_field2',
'report_grid_field1',
'report_grid_field57',
'report_grid_field58',
'report_grid_field59',
'report_grid_field60',
'report_grid_field61',
'report_grid_field62',
'report_grid_field63',
'report_grid_field64',
'report_grid_field65' ),
'report_group_field' => array( 'report_group_field4',
'report_group_field3',
'report_group_field2',
'report_group_field1',
'report_group_field',
'report_group_field5',
'report_group_field6',
'report_group_field7',
'report_group_field8',
'report_group_field9',
'report_group_field10',
'report_group_field11',
'report_group_field12',
'report_group_field13',
'report_group_field14',
'report_group_field15',
'report_group_field16',
'report_group_field17',
'report_group_field18' ),
'print_pdf' => array( 'print_pdf' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Sex',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DOB',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Region',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'City',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Languages',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed_Courses',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_1st Round',
'color' => array( 'header' => 'd9d3bb',
'summary' => 'fff8dc' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'color' => array( 'header' => '93d928',
'summary' => 'adff2f' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Department',
'color' => array( 'header' => 'bed9d9',
'summary' => 'e0ffff' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Field_Of_Study',
'color' => array( 'header' => 'd98868',
'summary' => 'ffa07a' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Enrollement_Type',
'color' => array( 'header' => 'd9bd93',
'summary' => 'ffdead' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Score',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Status',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'GPA',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Intervention',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair_Clinic',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Year_of_graduation',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Region',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Intervention',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DOB',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sub_City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Zone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'House_No',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Remark',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Education_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Department',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Minor',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Major',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Languages',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Certifications',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'GPA',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Campaign',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Work_Experience',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Company',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Position',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'field' => 'Woreda',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Kebele',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Employer_Sector',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Salary',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Career_Level_Of_Payment',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Placement_Type',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Placement_Duration',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Date',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Upload_on_Website',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'block',
'vertSummary' => true ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6',
'report_group_field7',
'report_group_field8',
'report_group_field9',
'report_group_field10',
'report_group_field11',
'report_group_field12',
'report_group_field13',
'report_group_field14',
'report_group_field15',
'report_group_field16',
'report_group_field17',
'report_group_field18' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56',
'report_grid_field57',
'report_grid_field58',
'report_grid_field59',
'report_grid_field60',
'report_grid_field61',
'report_grid_field62',
'report_grid_field63',
'report_grid_field64',
'report_grid_field65' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Sex',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DOB',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Region',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'City',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Languages',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed_Courses',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_1st Round',
'color' => array( 'header' => 'd9d3bb',
'summary' => 'fff8dc' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'color' => array( 'header' => '93d928',
'summary' => 'adff2f' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Department',
'color' => array( 'header' => 'bed9d9',
'summary' => 'e0ffff' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Field_Of_Study',
'color' => array( 'header' => 'd98868',
'summary' => 'ffa07a' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Enrollement_Type',
'color' => array( 'header' => 'd9bd93',
'summary' => 'ffdead' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Score',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Status',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'GPA',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Intervention',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair_Clinic',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Year_of_graduation',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Region',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Intervention',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DOB',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sub_City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Zone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'House_No',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Remark',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Education_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Department',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Minor',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Major',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Languages',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Certifications',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'GPA',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Campaign',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Work_Experience',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Company',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Position',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'field' => 'Woreda',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Kebele',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Employer_Sector',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Salary',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Career_Level_Of_Payment',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Placement_Type',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Placement_Duration',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Date',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'Upload_on_Website',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'block',
'vertSummary' => true ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field' => array( 'field' => 'CandidateID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field56' => array( 'field' => 'Employment_Position',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field55' => array( 'field' => 'Employment_Company',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field54' => array( 'field' => 'Employment_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field53' => array( 'field' => 'Dereja_Information_Source',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field52' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field51' => array( 'field' => 'Dereja_Event_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field50' => array( 'field' => 'Dereja_Training_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field49' => array( 'field' => 'Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field48' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field47' => array( 'field' => 'Work_Experience',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field46' => array( 'field' => 'Upload_on_Tracker',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field45' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field44' => array( 'field' => 'Exit_Exam_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field43' => array( 'field' => 'Exit_Exam_Score',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field42' => array( 'field' => 'Job_Fair',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field41' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field40' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field39' => array( 'field' => 'DAAP_Completed',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field38' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field37' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field36' => array( 'field' => 'Campaign',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field35' => array( 'field' => 'GPA',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field34' => array( 'field' => 'Field_Of_Study',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field33' => array( 'field' => 'Certifications',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field32' => array( 'field' => 'IT_Related_Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field31' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field30' => array( 'field' => 'English_Proficiency_Level',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field29' => array( 'field' => 'Languages',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field28' => array( 'field' => 'Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field27' => array( 'field' => 'Enrollement_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field26' => array( 'field' => 'Major',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field25' => array( 'field' => 'Minor',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field24' => array( 'field' => 'Department',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field23' => array( 'field' => 'Education_Level',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field22' => array( 'field' => 'Remark',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field21' => array( 'field' => 'Institution_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field20' => array( 'field' => 'Institution_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field19' => array( 'field' => 'Disability_Type_Other',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field18' => array( 'field' => 'Disability_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field17' => array( 'field' => 'Email_Address',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field16' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field15' => array( 'field' => 'Phone_Number',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field14' => array( 'field' => 'House_No',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field13' => array( 'field' => 'Zone',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field12' => array( 'field' => 'Sub_City',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field11' => array( 'field' => 'City',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field10' => array( 'field' => 'DOB',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field9' => array( 'field' => 'Last_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field8' => array( 'field' => 'Middle_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field7' => array( 'field' => 'First_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field6' => array( 'field' => 'StudentID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field5' => array( 'field' => 'Intervention',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field4' => array( 'field' => 'Disability_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field3' => array( 'field' => 'Year_of_graduation',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field2' => array( 'field' => 'Region',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field1' => array( 'field' => 'Sex',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_group_field4' => array( 'field' => 'Languages',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'City',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'Region',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'DOB',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field' => array( 'field' => 'Sex',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'report_group_field5' => array( 'field' => 'DAAP_Completed',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field6' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field7' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field8' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field9' => array( 'field' => 'Department',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field10' => array( 'field' => 'Field_Of_Study',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field11' => array( 'field' => 'Enrollement_Type',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field12' => array( 'field' => 'Exit_Exam_Score',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field13' => array( 'field' => 'Exit_Exam_Status',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field14' => array( 'field' => 'GPA',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field15' => array( 'field' => 'Intervention',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field16' => array( 'field' => 'Job_Fair',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field17' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field18' => array( 'field' => 'Year_of_graduation',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'report_grid_field57' => array( 'field' => 'Woreda',
'type' => 'report_grid_field' ),
'report_grid_field58' => array( 'field' => 'Kebele',
'type' => 'report_grid_field' ),
'report_grid_field59' => array( 'field' => 'Employer_Sector',
'type' => 'report_grid_field' ),
'report_grid_field60' => array( 'field' => 'Salary',
'type' => 'report_grid_field' ),
'report_grid_field61' => array( 'field' => 'Career_Level_Of_Payment',
'type' => 'report_grid_field' ),
'report_grid_field62' => array( 'field' => 'Placement_Type',
'type' => 'report_grid_field' ),
'report_grid_field63' => array( 'field' => 'Placement_Duration',
'type' => 'report_grid_field' ),
'report_grid_field64' => array( 'field' => 'Date',
'type' => 'report_grid_field' ),
'report_grid_field65' => array( 'field' => 'Upload_on_Website',
'type' => 'report_grid_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>