<?php
			$optionsArray = array( 'totals' => array( 'CandidateID' => array( 'totalsType' => '' ),
'StudentID' => array( 'totalsType' => '' ),
'Full_Name' => array( 'totalsType' => '' ),
'First_Name' => array( 'totalsType' => '' ),
'Middle_Name' => array( 'totalsType' => '' ),
'Last_Name' => array( 'totalsType' => '' ),
'Sex' => array( 'totalsType' => '' ),
'DOB' => array( 'totalsType' => '' ),
'Age' => array( 'totalsType' => '' ),
'Region' => array( 'totalsType' => '' ),
'City' => array( 'totalsType' => '' ),
'Sub_City' => array( 'totalsType' => '' ),
'Zone' => array( 'totalsType' => '' ),
'Woreda' => array( 'totalsType' => '' ),
'Kebele' => array( 'totalsType' => '' ),
'House_No' => array( 'totalsType' => '' ),
'Phone_Number' => array( 'totalsType' => '' ),
'Phone_Number_Alternate' => array( 'totalsType' => '' ),
'Email_Address' => array( 'totalsType' => '' ),
'Disability_Status' => array( 'totalsType' => '' ),
'Disability_Type' => array( 'totalsType' => '' ),
'Disability_Type_Other' => array( 'totalsType' => '' ),
'Institution_Type' => array( 'totalsType' => '' ),
'Institution_Name' => array( 'totalsType' => '' ),
'Education_Level' => array( 'totalsType' => '' ),
'Department' => array( 'totalsType' => '' ),
'Minor' => array( 'totalsType' => '' ),
'Major' => array( 'totalsType' => '' ),
'Enrollement_Type' => array( 'totalsType' => '' ),
'Skills' => array( 'totalsType' => '' ),
'Languages' => array( 'totalsType' => '' ),
'English_Proficiency_Level' => array( 'totalsType' => '' ),
'Industry_Specific_Skills' => array( 'totalsType' => '' ),
'IT_Related_Skills' => array( 'totalsType' => '' ),
'Certifications' => array( 'totalsType' => '' ),
'Year_of_graduation' => array( 'totalsType' => '' ),
'Field_Of_Study' => array( 'totalsType' => '' ),
'GPA' => array( 'totalsType' => '' ),
'Intervention' => array( 'totalsType' => '' ),
'Campaign' => array( 'totalsType' => '' ),
'Attend_Employability_Skill' => array( 'totalsType' => '' ),
'DAAP_enrolled_1st Round' => array( 'totalsType' => '' ),
'DAAP_Completed' => array( 'totalsType' => '' ),
'DAAP_Completed_Courses' => array( 'totalsType' => '' ),
'Job_Fair_Clinic' => array( 'totalsType' => '' ),
'Job_Fair' => array( 'totalsType' => '' ),
'Exit_Exam_Score' => array( 'totalsType' => '' ),
'Exit_Exam_Status' => array( 'totalsType' => '' ),
'DAAP_enrolled_2nd_Round' => array( 'totalsType' => '' ),
'Upload_on_Tracker' => array( 'totalsType' => '' ),
'Work_Experience' => array( 'totalsType' => '' ),
'Joined_Dereja_Services' => array( 'totalsType' => '' ),
'Dereja_Services' => array( 'totalsType' => '' ),
'Dereja_Training_Services' => array( 'totalsType' => '' ),
'Dereja_Event_Services' => array( 'totalsType' => '' ),
'Dereja_web_profile_completion' => array( 'totalsType' => '' ),
'Dereja_Information_Source' => array( 'totalsType' => '' ),
'Employment_Status' => array( 'totalsType' => '' ),
'Employment_Company' => array( 'totalsType' => '' ),
'Employer_Sector' => array( 'totalsType' => '' ),
'Employment_Position' => array( 'totalsType' => '' ),
'Salary' => array( 'totalsType' => '' ),
'Career_Level_Of_Payment' => array( 'totalsType' => '' ),
'Placement_Type' => array( 'totalsType' => '' ),
'Placement_Duration' => array( 'totalsType' => '' ),
'Remark' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CandidateID',
'First_Name',
'Middle_Name',
'Last_Name',
'Sex',
'DOB',
'Region',
'City',
'Sub_City',
'Zone',
'House_No',
'Phone_Number',
'Phone_Number_Alternate',
'Email_Address',
'Institution_Type',
'Education_Level',
'Department',
'Minor',
'Major',
'Skills',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Certifications',
'Year_of_graduation',
'Work_Experience',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Training_Services',
'Dereja_Event_Services',
'Dereja_web_profile_completion',
'Dereja_Information_Source',
'StudentID',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Field_Of_Study',
'GPA',
'Institution_Name',
'Languages',
'Employment_Status',
'Employment_Company',
'Employment_Position',
'Remark',
'Enrollement_Type',
'Intervention',
'Campaign',
'Attend_Employability_Skill',
'DAAP_enrolled_1st Round',
'DAAP_Completed',
'DAAP_Completed_Courses',
'Job_Fair_Clinic',
'Job_Fair',
'Exit_Exam_Score',
'Exit_Exam_Status',
'DAAP_enrolled_2nd_Round',
'Upload_on_Tracker',
'Age',
'Full_Name',
'Woreda',
'Kebele',
'Employer_Sector',
'Salary',
'Career_Level_Of_Payment',
'Placement_Type',
'Placement_Duration' ),
'exportFields' => array( 'CandidateID',
'First_Name',
'Middle_Name',
'Last_Name',
'Sex',
'DOB',
'Region',
'City',
'Sub_City',
'Zone',
'House_No',
'Phone_Number',
'Email_Address',
'Institution_Type',
'Education_Level',
'Department',
'Minor',
'Major',
'Skills',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Certifications',
'Year_of_graduation',
'Work_Experience',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Training_Services',
'Dereja_Event_Services',
'Dereja_web_profile_completion',
'Dereja_Information_Source',
'StudentID',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Field_Of_Study',
'GPA',
'Institution_Name',
'Languages',
'Employment_Status',
'Employment_Company',
'Employment_Position',
'Remark',
'Phone_Number_Alternate',
'Enrollement_Type',
'Intervention',
'Campaign',
'Attend_Employability_Skill',
'DAAP_enrolled_1st Round',
'DAAP_Completed',
'DAAP_Completed_Courses',
'Job_Fair_Clinic',
'Job_Fair',
'Exit_Exam_Score',
'Exit_Exam_Status',
'DAAP_enrolled_2nd_Round',
'Upload_on_Tracker',
'Age',
'Full_Name',
'Woreda',
'Kebele',
'Employer_Sector',
'Salary',
'Career_Level_Of_Payment',
'Placement_Type',
'Placement_Duration' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CandidateID' => array( 'export_field' ),
'First_Name' => array( 'export_field1' ),
'Middle_Name' => array( 'export_field2' ),
'Last_Name' => array( 'export_field3' ),
'Sex' => array( 'export_field4' ),
'DOB' => array( 'export_field5' ),
'Region' => array( 'export_field6' ),
'City' => array( 'export_field7' ),
'Sub_City' => array( 'export_field8' ),
'Zone' => array( 'export_field9' ),
'House_No' => array( 'export_field10' ),
'Phone_Number' => array( 'export_field11' ),
'Phone_Number_Alternate' => array( 'export_field12' ),
'Email_Address' => array( 'export_field13' ),
'Institution_Type' => array( 'export_field14' ),
'Education_Level' => array( 'export_field15' ),
'Department' => array( 'export_field16' ),
'Minor' => array( 'export_field17' ),
'Major' => array( 'export_field18' ),
'Skills' => array( 'export_field19' ),
'English_Proficiency_Level' => array( 'export_field20' ),
'Industry_Specific_Skills' => array( 'export_field21' ),
'IT_Related_Skills' => array( 'export_field22' ),
'Certifications' => array( 'export_field23' ),
'Year_of_graduation' => array( 'export_field24' ),
'Work_Experience' => array( 'export_field25' ),
'Joined_Dereja_Services' => array( 'export_field26' ),
'Dereja_Services' => array( 'export_field27' ),
'Dereja_Training_Services' => array( 'export_field28' ),
'Dereja_Event_Services' => array( 'export_field29' ),
'Dereja_web_profile_completion' => array( 'export_field30' ),
'Dereja_Information_Source' => array( 'export_field31' ),
'StudentID' => array( 'export_field32' ),
'Disability_Status' => array( 'export_field33' ),
'Disability_Type' => array( 'export_field34' ),
'Disability_Type_Other' => array( 'export_field35' ),
'Field_Of_Study' => array( 'export_field36' ),
'GPA' => array( 'export_field37' ),
'Institution_Name' => array( 'export_field38' ),
'Languages' => array( 'export_field39' ),
'Employment_Status' => array( 'export_field40' ),
'Employment_Company' => array( 'export_field41' ),
'Employment_Position' => array( 'export_field42' ),
'Remark' => array( 'export_field43' ),
'Enrollement_Type' => array( 'export_field44' ),
'Intervention' => array( 'export_field45' ),
'Campaign' => array( 'export_field46' ),
'Attend_Employability_Skill' => array( 'export_field47' ),
'DAAP_enrolled_1st Round' => array( 'export_field48' ),
'DAAP_Completed' => array( 'export_field49' ),
'DAAP_Completed_Courses' => array( 'export_field50' ),
'Job_Fair_Clinic' => array( 'export_field51' ),
'Job_Fair' => array( 'export_field52' ),
'Exit_Exam_Score' => array( 'export_field53' ),
'Exit_Exam_Status' => array( 'export_field54' ),
'DAAP_enrolled_2nd_Round' => array( 'export_field55' ),
'Upload_on_Tracker' => array( 'export_field56' ),
'Age' => array( 'export_field57' ),
'Full_Name' => array( 'export_field58' ),
'Woreda' => array( 'export_field59' ),
'Kebele' => array( 'export_field60' ),
'Employer_Sector' => array( 'export_field61' ),
'Salary' => array( 'export_field62' ),
'Career_Level_Of_Payment' => array( 'export_field63' ),
'Placement_Type' => array( 'export_field64' ),
'Placement_Duration' => array( 'export_field65' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field12',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field12' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field62' => 'grid',
'export_field63' => 'grid',
'export_field64' => 'grid',
'export_field65' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field12',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'CandidateID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'First_Name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Middle_Name',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Last_Name',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Sex',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'DOB',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Region',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'City',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Sub_City',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Zone',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'House_No',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Phone_Number',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Email_Address',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Institution_Type',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Education_Level',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Department',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Minor',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Major',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Skills',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'English_Proficiency_Level',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'IT_Related_Skills',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Certifications',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Year_of_graduation',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Work_Experience',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Dereja_Services',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Dereja_Training_Services',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Dereja_Event_Services',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'Dereja_Information_Source',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'StudentID',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'Disability_Status',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'Disability_Type',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Disability_Type_Other',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'Field_Of_Study',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'GPA',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'Institution_Name',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'Languages',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'Employment_Status',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'Employment_Company',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'Employment_Position',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'Remark',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'Enrollement_Type',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'Intervention',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'Campaign',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'DAAP_Completed',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'Job_Fair',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'Exit_Exam_Score',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'Exit_Exam_Status',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'Upload_on_Tracker',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'Age',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'Full_Name',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'Woreda',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'Kebele',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'Employer_Sector',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'Salary',
'type' => 'export_field' ),
'export_field63' => array( 'field' => 'Career_Level_Of_Payment',
'type' => 'export_field' ),
'export_field64' => array( 'field' => 'Placement_Type',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'Placement_Duration',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>