<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'First Name',
'Middle Name',
'Last Name',
'Sex',
'DOB',
'Region',
'City',
'Sub City',
'Zone',
'House No',
'Phone Number',
'Phone Number Family',
'Email Address',
'Institution Type',
'Education Level',
'Department',
'Minor',
'Major',
'Skills',
'English Proficiency Level',
'Industry Specific Skills',
'IT Related Skills',
'Certifications',
'Year of graduation',
'Work Experience',
'Joined Dereja Services',
'Dereja Services',
'Dereja Training Services',
'Dereja Event Services',
'Dereja web profile completion',
'Dereja Information Source',
'Training Organizer',
'Training Type',
'Program Area',
'Training City Town',
'Training Venue',
'Training start date',
'Training end date',
'Training Title',
'Participant Profession',
'Participant Field of Study',
'Participant Facility or Organization Type',
'Participant Organization Name',
'Participant Home Address',
'Disablity Status',
'Pre-Test Score',
'Skill Test',
'Post-Test Score' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'import_field' ),
'First Name' => array( 'import_field1' ),
'Middle Name' => array( 'import_field2' ),
'Last Name' => array( 'import_field3' ),
'Sex' => array( 'import_field4' ),
'DOB' => array( 'import_field5' ),
'Region' => array( 'import_field6' ),
'City' => array( 'import_field7' ),
'Sub City' => array( 'import_field8' ),
'Zone' => array( 'import_field9' ),
'House No' => array( 'import_field10' ),
'Phone Number' => array( 'import_field11' ),
'Phone Number Family' => array( 'import_field12' ),
'Email Address' => array( 'import_field13' ),
'Institution Type' => array( 'import_field14' ),
'Education Level' => array( 'import_field15' ),
'Department' => array( 'import_field16' ),
'Minor' => array( 'import_field17' ),
'Major' => array( 'import_field18' ),
'Skills' => array( 'import_field19' ),
'English Proficiency Level' => array( 'import_field20' ),
'Industry Specific Skills' => array( 'import_field21' ),
'IT Related Skills' => array( 'import_field22' ),
'Certifications' => array( 'import_field23' ),
'Year of graduation' => array( 'import_field24' ),
'Work Experience' => array( 'import_field25' ),
'Joined Dereja Services' => array( 'import_field26' ),
'Dereja Services' => array( 'import_field27' ),
'Dereja Training Services' => array( 'import_field28' ),
'Dereja Event Services' => array( 'import_field29' ),
'Dereja web profile completion' => array( 'import_field30' ),
'Dereja Information Source' => array( 'import_field31' ),
'Training Organizer' => array( 'import_field32' ),
'Training Type' => array( 'import_field33' ),
'Program Area' => array( 'import_field34' ),
'Training City Town' => array( 'import_field35' ),
'Training Venue' => array( 'import_field36' ),
'Training start date' => array( 'import_field37' ),
'Training end date' => array( 'import_field38' ),
'Training Title' => array( 'import_field39' ),
'Participant Profession' => array( 'import_field40' ),
'Participant Field of Study' => array( 'import_field41' ),
'Participant Facility or Organization Type' => array( 'import_field42' ),
'Participant Organization Name' => array( 'import_field43' ),
'Participant Home Address' => array( 'import_field44' ),
'Disablity Status' => array( 'import_field45' ),
'Pre-Test Score' => array( 'import_field46' ),
'Skill Test' => array( 'import_field47' ),
'Post-Test Score' => array( 'import_field48' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'First Name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Middle Name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Last Name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Sex',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'DOB',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Region',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'City',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Sub City',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Zone',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'House No',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Phone Number',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Phone Number Family',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Email Address',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Institution Type',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Education Level',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Department',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Minor',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Major',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Skills',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'English Proficiency Level',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Industry Specific Skills',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'IT Related Skills',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Certifications',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'Year of graduation',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Work Experience',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Joined Dereja Services',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Dereja Services',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Dereja Training Services',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Dereja Event Services',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'Dereja web profile completion',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'Dereja Information Source',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'Training Organizer',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Training Type',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'Program Area',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Training City Town',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Training Venue',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'Training start date',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'Training end date',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'Training Title',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'Participant Profession',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'Participant Field of Study',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'Participant Facility or Organization Type',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'Participant Organization Name',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'Participant Home Address',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'Disablity Status',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'Pre-Test Score',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'Skill Test',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'Post-Test Score',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>