<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'CandidateID',
'JobID',
'Referral_from_Dereja_service',
'Company_Name',
'Company_Phone_Number',
'Sector',
'Job_Position',
'Job_Type',
'Job_Placement_Date',
'Employment_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'CurrentEmploymentStatus',
'Full_Name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CandidateID' => array( 'import_field' ),
'JobID' => array( 'import_field1' ),
'Referral_from_Dereja_service' => array( 'import_field2' ),
'Company_Name' => array( 'import_field3' ),
'Company_Phone_Number' => array( 'import_field4' ),
'Sector' => array( 'import_field5' ),
'Job_Position' => array( 'import_field6' ),
'Job_Type' => array( 'import_field7' ),
'Job_Placement_Date' => array( 'import_field8' ),
'Employment_End_Date' => array( 'import_field9' ),
'First_Name' => array( 'import_field10' ),
'Middle_Name' => array( 'import_field11' ),
'Last_Name' => array( 'import_field12' ),
'CurrentEmploymentStatus' => array( 'import_field13' ),
'Full_Name' => array( 'import_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'CandidateID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'JobID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Referral_from_Dereja_service',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Company_Name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Company_Phone_Number',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Sector',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Job_Position',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Job_Type',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Job_Placement_Date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Employment_End_Date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'First_Name',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Middle_Name',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Last_Name',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'CurrentEmploymentStatus',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Full_Name',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>