<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'COUNT(CandidateID)',
'First_Name',
'Middle_Name',
'Last_Name',
'DOB',
'Region',
'City',
'Zone',
'House_No',
'Phone_Number',
'Phone_Number_Alternate',
'Email_Address',
'Disability_Type',
'Disability_Type_Other',
'Institution_Type',
'Institution_Name',
'Education_Level',
'Department',
'Minor',
'Major',
'Enrollement_Type',
'Skills',
'Languages',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Certifications',
'Year_of_graduation',
'Field_Of_Study',
'GPA',
'Intervention',
'Campaign',
'Attend_Employability_Skill',
'DAAP_enrolled_1st Round',
'DAAP_Completed',
'DAAP_Completed_Courses',
'Job_Fair_Clinic',
'Job_Fair',
'Exit_Exam_Score',
'Exit_Exam_Status',
'DAAP_enrolled_2nd_Round',
'Upload_on_Tracker',
'Work_Experience',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Training_Services',
'Dereja_Event_Services',
'Dereja_web_profile_completion',
'Dereja_Information_Source',
'Employment_Status',
'Employment_Company',
'Employment_Position',
'Remark' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'COUNT(CandidateID)' => array( 'report_grid_field' ),
'First_Name' => array( 'report_grid_field2' ),
'Middle_Name' => array( 'report_grid_field3' ),
'Last_Name' => array( 'report_grid_field4' ),
'DOB' => array( 'report_grid_field6' ),
'Region' => array( 'report_grid_field7' ),
'City' => array( 'report_grid_field8' ),
'Zone' => array( 'report_grid_field10' ),
'House_No' => array( 'report_grid_field11' ),
'Phone_Number' => array( 'report_grid_field12' ),
'Phone_Number_Alternate' => array( 'report_grid_field13' ),
'Email_Address' => array( 'report_grid_field14' ),
'Disability_Type' => array( 'report_grid_field16' ),
'Disability_Type_Other' => array( 'report_grid_field17' ),
'Institution_Type' => array( 'report_grid_field18' ),
'Institution_Name' => array( 'report_grid_field19' ),
'Education_Level' => array( 'report_grid_field20' ),
'Department' => array( 'report_grid_field21' ),
'Minor' => array( 'report_grid_field22' ),
'Major' => array( 'report_grid_field23' ),
'Enrollement_Type' => array( 'report_grid_field24' ),
'Skills' => array( 'report_grid_field25' ),
'Languages' => array( 'report_grid_field26' ),
'English_Proficiency_Level' => array( 'report_grid_field27' ),
'Industry_Specific_Skills' => array( 'report_grid_field28' ),
'IT_Related_Skills' => array( 'report_grid_field29' ),
'Certifications' => array( 'report_grid_field30' ),
'Year_of_graduation' => array( 'report_grid_field31' ),
'Field_Of_Study' => array( 'report_grid_field32' ),
'GPA' => array( 'report_grid_field33' ),
'Intervention' => array( 'report_grid_field34' ),
'Campaign' => array( 'report_grid_field35' ),
'Attend_Employability_Skill' => array( 'report_grid_field36' ),
'DAAP_enrolled_1st Round' => array( 'report_grid_field37' ),
'DAAP_Completed' => array( 'report_grid_field38' ),
'DAAP_Completed_Courses' => array( 'report_grid_field39' ),
'Job_Fair_Clinic' => array( 'report_grid_field40' ),
'Job_Fair' => array( 'report_grid_field41' ),
'Exit_Exam_Score' => array( 'report_grid_field42' ),
'Exit_Exam_Status' => array( 'report_grid_field43' ),
'DAAP_enrolled_2nd_Round' => array( 'report_grid_field44' ),
'Upload_on_Tracker' => array( 'report_grid_field45' ),
'Work_Experience' => array( 'report_grid_field46' ),
'Joined_Dereja_Services' => array( 'report_grid_field47' ),
'Dereja_Services' => array( 'report_grid_field48' ),
'Dereja_Training_Services' => array( 'report_grid_field49' ),
'Dereja_Event_Services' => array( 'report_grid_field50' ),
'Dereja_web_profile_completion' => array( 'report_grid_field51' ),
'Dereja_Information_Source' => array( 'report_grid_field52' ),
'Employment_Status' => array( 'report_grid_field53' ),
'Employment_Company' => array( 'report_grid_field54' ),
'Employment_Position' => array( 'report_grid_field55' ),
'Remark' => array( 'report_grid_field56' ),
'Sex' => array( 'report_group_field' ),
'Age' => array( 'report_group_field1' ),
'Disability_Status' => array( 'report_group_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56',
'report_grid_field' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field14' => 'grid',
'report_grid_field16' => 'grid',
'report_grid_field17' => 'grid',
'report_grid_field18' => 'grid',
'report_grid_field19' => 'grid',
'report_grid_field20' => 'grid',
'report_grid_field21' => 'grid',
'report_grid_field22' => 'grid',
'report_grid_field23' => 'grid',
'report_grid_field24' => 'grid',
'report_grid_field25' => 'grid',
'report_grid_field26' => 'grid',
'report_grid_field27' => 'grid',
'report_grid_field28' => 'grid',
'report_grid_field29' => 'grid',
'report_grid_field30' => 'grid',
'report_grid_field31' => 'grid',
'report_grid_field32' => 'grid',
'report_grid_field33' => 'grid',
'report_grid_field34' => 'grid',
'report_grid_field35' => 'grid',
'report_grid_field36' => 'grid',
'report_grid_field37' => 'grid',
'report_grid_field38' => 'grid',
'report_grid_field39' => 'grid',
'report_grid_field40' => 'grid',
'report_grid_field41' => 'grid',
'report_grid_field42' => 'grid',
'report_grid_field43' => 'grid',
'report_grid_field44' => 'grid',
'report_grid_field45' => 'grid',
'report_grid_field46' => 'grid',
'report_grid_field47' => 'grid',
'report_grid_field48' => 'grid',
'report_grid_field49' => 'grid',
'report_grid_field50' => 'grid',
'report_grid_field51' => 'grid',
'report_grid_field52' => 'grid',
'report_grid_field53' => 'grid',
'report_grid_field54' => 'grid',
'report_grid_field55' => 'grid',
'report_grid_field56' => 'grid',
'report_grid_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1',
'report_group_field2' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93B7C3',
'summary' => 'ADD8E6' ),
'field' => 'Sex' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7ACA7A',
'summary' => '90EE90' ),
'field' => 'Age' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D89AA4',
'summary' => 'FFB6C1' ),
'field' => 'Disability_Status' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'First_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Middle_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Last_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DOB',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Region',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'City',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Zone',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'House_No',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Phone_Number',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Email_Address',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Disability_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Institution_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Institution_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Education_Level',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Department',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Minor',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Major',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Languages',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Certifications',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'GPA',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Intervention',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Campaign',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Job_Fair',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Work_Experience',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Status',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Company',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Position',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Remark',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'COUNT(CandidateID)',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56',
'report_grid_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93B7C3',
'summary' => 'ADD8E6' ),
'field' => 'Sex' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7ACA7A',
'summary' => '90EE90' ),
'field' => 'Age' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'D89AA4',
'summary' => 'FFB6C1' ),
'field' => 'Disability_Status' ) ),
'fields' => array( array( 'avg' => false,
'field' => 'First_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Middle_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Last_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DOB',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Region',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'City',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Zone',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'House_No',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Phone_Number',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Email_Address',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Disability_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Institution_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Institution_Name',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Education_Level',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Department',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Minor',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Major',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Languages',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Certifications',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'GPA',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Intervention',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Campaign',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Job_Fair',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Work_Experience',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Status',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Company',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Employment_Position',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'Remark',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ),
array( 'avg' => false,
'field' => 'COUNT(CandidateID)',
'grid' => true,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'stepped',
'vertSummary' => false ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field' => array( 'field' => 'COUNT(CandidateID)',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field2' => array( 'field' => 'First_Name',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field3' => array( 'field' => 'Middle_Name',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field4' => array( 'field' => 'Last_Name',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'DOB',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field7' => array( 'field' => 'Region',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'City',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field10' => array( 'field' => 'Zone',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field11' => array( 'field' => 'House_No',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field12' => array( 'field' => 'Phone_Number',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field13' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field14' => array( 'field' => 'Email_Address',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field16' => array( 'field' => 'Disability_Type',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field17' => array( 'field' => 'Disability_Type_Other',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field18' => array( 'field' => 'Institution_Type',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field19' => array( 'field' => 'Institution_Name',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field20' => array( 'field' => 'Education_Level',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field21' => array( 'field' => 'Department',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field22' => array( 'field' => 'Minor',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field23' => array( 'field' => 'Major',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field24' => array( 'field' => 'Enrollement_Type',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field25' => array( 'field' => 'Skills',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field26' => array( 'field' => 'Languages',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field27' => array( 'field' => 'English_Proficiency_Level',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field28' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field29' => array( 'field' => 'IT_Related_Skills',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field30' => array( 'field' => 'Certifications',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field31' => array( 'field' => 'Year_of_graduation',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field32' => array( 'field' => 'Field_Of_Study',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field33' => array( 'field' => 'GPA',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field34' => array( 'field' => 'Intervention',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field35' => array( 'field' => 'Campaign',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field36' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field37' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field38' => array( 'field' => 'DAAP_Completed',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field39' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field40' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field41' => array( 'field' => 'Job_Fair',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field42' => array( 'field' => 'Exit_Exam_Score',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field43' => array( 'field' => 'Exit_Exam_Status',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field44' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field45' => array( 'field' => 'Upload_on_Tracker',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field46' => array( 'field' => 'Work_Experience',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field47' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field48' => array( 'field' => 'Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field49' => array( 'field' => 'Dereja_Training_Services',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field50' => array( 'field' => 'Dereja_Event_Services',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field51' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field52' => array( 'field' => 'Dereja_Information_Source',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field53' => array( 'field' => 'Employment_Status',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field54' => array( 'field' => 'Employment_Company',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field55' => array( 'field' => 'Employment_Position',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field56' => array( 'field' => 'Remark',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'Sex',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'Age',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'Disability_Status',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>