<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'allDetails' => array( 'linkType' => 1 ),
'details' => array( 'Candidate_Employment_Tracker' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true ),
'event_participants' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true ),
'training_participants' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array( 'CandidateID',
'StudentID',
'First_Name',
'Middle_Name',
'Last_Name',
'Sex',
'DOB',
'Region',
'City',
'Sub_City',
'Zone',
'House_No',
'Phone_Number',
'Phone_Number_Alternate',
'Email_Address',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Institution_Type',
'Institution_Name',
'Education_Level',
'Department',
'Minor',
'Major',
'Enrollement_Type',
'Skills',
'Languages',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Certifications',
'Year_of_graduation',
'Field_Of_Study',
'GPA',
'Intervention',
'Campaign',
'Attend_Employability_Skill',
'DAAP_enrolled_1st Round',
'DAAP_Completed',
'DAAP_Completed_Courses',
'Job_Fair_Clinic',
'Job_Fair',
'Exit_Exam_Score',
'Exit_Exam_Status',
'DAAP_enrolled_2nd_Round',
'Upload_on_Tracker',
'Work_Experience',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Training_Services',
'Dereja_Event_Services',
'Dereja_web_profile_completion',
'Dereja_Information_Source',
'Employment_Status',
'Employment_Company',
'Employment_Position',
'Remark' ),
'searchPanel' => true,
'fixedSearchPanel' => true,
'simpleSearchOptions' => true,
'searchSaving' => true ),
'fields' => array( 'gridFields' => array( 'Employment_Position',
'Employment_Company',
'Employment_Status',
'Dereja_Information_Source',
'Dereja_web_profile_completion',
'Dereja_Event_Services',
'Dereja_Training_Services',
'Dereja_Services',
'Joined_Dereja_Services',
'Work_Experience',
'Upload_on_Tracker',
'Minor',
'Department',
'Education_Level',
'Remark',
'Institution_Name',
'Institution_Type',
'Disability_Type_Other',
'Disability_Type',
'Email_Address',
'Phone_Number_Alternate',
'DAAP_enrolled_2nd_Round',
'Exit_Exam_Status',
'Phone_Number',
'Exit_Exam_Score',
'Job_Fair',
'Job_Fair_Clinic',
'DAAP_Completed_Courses',
'DAAP_Completed',
'House_No',
'Zone',
'Sub_City',
'City',
'DOB',
'Last_Name',
'Middle_Name',
'First_Name',
'StudentID',
'Intervention',
'Disability_Status',
'Year_of_graduation',
'Region',
'Sex',
'CandidateID',
'DAAP_enrolled_1st Round',
'Attend_Employability_Skill',
'Campaign',
'GPA',
'Field_Of_Study',
'Certifications',
'IT_Related_Skills',
'Industry_Specific_Skills',
'English_Proficiency_Level',
'Languages',
'Skills',
'Enrollement_Type',
'Major' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Attend_Employability_Skill',
'Zone',
'Year_of_graduation',
'Work_Experience',
'Upload_on_Tracker',
'Sub_City',
'StudentID',
'Skills',
'Sex',
'Remark',
'Region',
'Phone_Number_Alternate',
'Phone_Number',
'Minor',
'Middle_Name',
'Major',
'Last_Name',
'Languages',
'Joined_Dereja_Services',
'Job_Fair_Clinic',
'Job_Fair',
'Intervention',
'Institution_Type',
'Institution_Name',
'Industry_Specific_Skills',
'IT_Related_Skills',
'House_No',
'GPA',
'First_Name',
'Field_Of_Study',
'Exit_Exam_Status',
'Exit_Exam_Score',
'Enrollement_Type',
'English_Proficiency_Level',
'Employment_Status',
'Employment_Position',
'Employment_Company',
'Email_Address',
'Education_Level',
'Disability_Type_Other',
'Disability_Type',
'Disability_Status',
'Dereja_web_profile_completion',
'Dereja_Training_Services',
'Dereja_Services',
'Dereja_Information_Source',
'Dereja_Event_Services',
'Department',
'DOB',
'DAAP_enrolled_2nd_Round',
'DAAP_enrolled_1st Round',
'DAAP_Completed_Courses',
'DAAP_Completed',
'City',
'Certifications',
'CandidateID',
'Campaign' ),
'filterFields' => array(  ),
'fieldItems' => array( 'Employment_Position' => array( 'report_grid_field56' ),
'Employment_Company' => array( 'report_grid_field55' ),
'Employment_Status' => array( 'report_grid_field54' ),
'Dereja_Information_Source' => array( 'report_grid_field53' ),
'Dereja_web_profile_completion' => array( 'report_grid_field52' ),
'Dereja_Event_Services' => array( 'report_grid_field51' ),
'Dereja_Training_Services' => array( 'report_grid_field50' ),
'Dereja_Services' => array( 'report_grid_field49' ),
'Joined_Dereja_Services' => array( 'report_grid_field48' ),
'Work_Experience' => array( 'report_grid_field47' ),
'Upload_on_Tracker' => array( 'report_grid_field46' ),
'Minor' => array( 'report_grid_field25' ),
'Department' => array( 'report_grid_field24',
'report_group_field9' ),
'Education_Level' => array( 'report_grid_field23' ),
'Remark' => array( 'report_grid_field22' ),
'Institution_Name' => array( 'report_grid_field21' ),
'Institution_Type' => array( 'report_grid_field20' ),
'Disability_Type_Other' => array( 'report_grid_field19' ),
'Disability_Type' => array( 'report_grid_field18' ),
'Email_Address' => array( 'report_grid_field17' ),
'Phone_Number_Alternate' => array( 'report_grid_field16' ),
'DAAP_enrolled_2nd_Round' => array( 'report_grid_field45',
'report_group_field8' ),
'Exit_Exam_Status' => array( 'report_grid_field44',
'report_group_field13' ),
'Phone_Number' => array( 'report_grid_field15' ),
'Exit_Exam_Score' => array( 'report_grid_field43',
'report_group_field12' ),
'Job_Fair' => array( 'report_grid_field42',
'report_group_field16' ),
'Job_Fair_Clinic' => array( 'report_grid_field41',
'report_group_field17' ),
'DAAP_Completed_Courses' => array( 'report_grid_field40',
'report_group_field6' ),
'DAAP_Completed' => array( 'report_grid_field39',
'report_group_field5' ),
'House_No' => array( 'report_grid_field14' ),
'Zone' => array( 'report_grid_field13' ),
'Sub_City' => array( 'report_grid_field12' ),
'City' => array( 'report_grid_field11',
'report_group_field3' ),
'DOB' => array( 'report_grid_field10',
'report_group_field1' ),
'Last_Name' => array( 'report_grid_field9' ),
'Middle_Name' => array( 'report_grid_field8' ),
'First_Name' => array( 'report_grid_field7' ),
'StudentID' => array( 'report_grid_field6' ),
'Intervention' => array( 'report_grid_field5',
'report_group_field15' ),
'Disability_Status' => array( 'report_grid_field4' ),
'Year_of_graduation' => array( 'report_grid_field3',
'report_group_field18' ),
'Region' => array( 'report_grid_field2',
'report_group_field2' ),
'Sex' => array( 'report_grid_field1',
'report_group_field' ),
'CandidateID' => array( 'report_grid_field' ),
'GPA' => array( 'report_group_field14',
'report_grid_field35' ),
'Enrollement_Type' => array( 'report_group_field11',
'report_grid_field27' ),
'Field_Of_Study' => array( 'report_group_field10',
'report_grid_field34' ),
'DAAP_enrolled_1st Round' => array( 'report_group_field7',
'report_grid_field38' ),
'Languages' => array( 'report_group_field4',
'report_grid_field29' ),
'Attend_Employability_Skill' => array( 'report_grid_field37' ),
'Campaign' => array( 'report_grid_field36' ),
'Certifications' => array( 'report_grid_field33' ),
'IT_Related_Skills' => array( 'report_grid_field32' ),
'Industry_Specific_Skills' => array( 'report_grid_field31' ),
'English_Proficiency_Level' => array( 'report_grid_field30' ),
'Skills' => array( 'report_grid_field28' ),
'Major' => array( 'report_grid_field26' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_preview',
'grid_details_link',
'details_preview1',
'grid_details_link1',
'details_preview2',
'grid_details_link2',
'details_found',
'page_size',
'print_panel',
'text1' ),
'below-grid' => array( 'pagination',
'filter_panel',
'search_panel',
'text' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6',
'report_group_field7',
'report_group_field8',
'report_group_field9',
'report_group_field10',
'report_group_field11',
'report_group_field12',
'report_group_field13',
'report_group_field14',
'report_group_field15',
'report_group_field16',
'report_group_field17',
'report_group_field18',
'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'details_preview' => 'above-grid',
'grid_details_link' => 'above-grid',
'details_preview1' => 'above-grid',
'grid_details_link1' => 'above-grid',
'details_preview2' => 'above-grid',
'grid_details_link2' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'text1' => 'above-grid',
'pagination' => 'below-grid',
'filter_panel' => 'below-grid',
'search_panel' => 'below-grid',
'text' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search_field' => 'supertop',
'simple_search_option' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_group_field5' => 'grid',
'report_group_field6' => 'grid',
'report_group_field7' => 'grid',
'report_group_field8' => 'grid',
'report_group_field9' => 'grid',
'report_group_field10' => 'grid',
'report_group_field11' => 'grid',
'report_group_field12' => 'grid',
'report_group_field13' => 'grid',
'report_group_field14' => 'grid',
'report_group_field15' => 'grid',
'report_group_field16' => 'grid',
'report_group_field17' => 'grid',
'report_group_field18' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field14' => 'grid',
'report_grid_field15' => 'grid',
'report_grid_field16' => 'grid',
'report_grid_field17' => 'grid',
'report_grid_field18' => 'grid',
'report_grid_field19' => 'grid',
'report_grid_field20' => 'grid',
'report_grid_field21' => 'grid',
'report_grid_field22' => 'grid',
'report_grid_field23' => 'grid',
'report_grid_field24' => 'grid',
'report_grid_field25' => 'grid',
'report_grid_field26' => 'grid',
'report_grid_field27' => 'grid',
'report_grid_field28' => 'grid',
'report_grid_field29' => 'grid',
'report_grid_field30' => 'grid',
'report_grid_field31' => 'grid',
'report_grid_field32' => 'grid',
'report_grid_field33' => 'grid',
'report_grid_field34' => 'grid',
'report_grid_field35' => 'grid',
'report_grid_field36' => 'grid',
'report_grid_field37' => 'grid',
'report_grid_field38' => 'grid',
'report_grid_field39' => 'grid',
'report_grid_field40' => 'grid',
'report_grid_field41' => 'grid',
'report_grid_field42' => 'grid',
'report_grid_field43' => 'grid',
'report_grid_field44' => 'grid',
'report_grid_field45' => 'grid',
'report_grid_field46' => 'grid',
'report_grid_field47' => 'grid',
'report_grid_field48' => 'grid',
'report_grid_field49' => 'grid',
'report_grid_field50' => 'grid',
'report_grid_field51' => 'grid',
'report_grid_field52' => 'grid',
'report_grid_field53' => 'grid',
'report_grid_field54' => 'grid',
'report_grid_field55' => 'grid',
'report_grid_field56' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'search_panel' => array( 'search_panel' ),
'report_grid_field' => array( 'report_grid_field56',
'report_grid_field55',
'report_grid_field54',
'report_grid_field53',
'report_grid_field52',
'report_grid_field51',
'report_grid_field50',
'report_grid_field49',
'report_grid_field48',
'report_grid_field47',
'report_grid_field46',
'report_grid_field25',
'report_grid_field24',
'report_grid_field23',
'report_grid_field22',
'report_grid_field21',
'report_grid_field20',
'report_grid_field19',
'report_grid_field18',
'report_grid_field17',
'report_grid_field16',
'report_grid_field45',
'report_grid_field44',
'report_grid_field15',
'report_grid_field43',
'report_grid_field42',
'report_grid_field41',
'report_grid_field40',
'report_grid_field39',
'report_grid_field14',
'report_grid_field13',
'report_grid_field12',
'report_grid_field11',
'report_grid_field10',
'report_grid_field9',
'report_grid_field8',
'report_grid_field7',
'report_grid_field6',
'report_grid_field5',
'report_grid_field4',
'report_grid_field3',
'report_grid_field2',
'report_grid_field1',
'report_grid_field',
'report_grid_field38',
'report_grid_field37',
'report_grid_field36',
'report_grid_field35',
'report_grid_field34',
'report_grid_field33',
'report_grid_field32',
'report_grid_field31',
'report_grid_field30',
'report_grid_field29',
'report_grid_field28',
'report_grid_field27',
'report_grid_field26' ),
'-' => array( '-',
'-1',
'-3',
'-2' ),
'filter_panel' => array( 'filter_panel' ),
'advsearch_link' => array( 'advsearch_link' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'simple_search_field' => array( 'simple_search_field' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1',
'grid_details_link2' ),
'saved_searches' => array( 'saved_searches' ),
'save_search' => array( 'save_search' ),
'report_group_field' => array( 'report_group_field18',
'report_group_field17',
'report_group_field16',
'report_group_field15',
'report_group_field14',
'report_group_field13',
'report_group_field12',
'report_group_field11',
'report_group_field10',
'report_group_field9',
'report_group_field8',
'report_group_field7',
'report_group_field6',
'report_group_field5',
'report_group_field4',
'report_group_field3',
'report_group_field2',
'report_group_field1',
'report_group_field' ),
'export_report_pdf' => array( 'export_report_pdf' ),
'simple_search_option' => array( 'simple_search_option' ),
'text' => array( 'text',
'text1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Sex',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DOB',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Region',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'City',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Languages',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed_Courses',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_1st Round',
'color' => array( 'header' => 'd9d3bb',
'summary' => 'fff8dc' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'color' => array( 'header' => '93d928',
'summary' => 'adff2f' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Department',
'color' => array( 'header' => 'bed9d9',
'summary' => 'e0ffff' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Field_Of_Study',
'color' => array( 'header' => 'd98868',
'summary' => 'ffa07a' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Enrollement_Type',
'color' => array( 'header' => 'd9bd93',
'summary' => 'ffdead' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Score',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Status',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'GPA',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Intervention',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair_Clinic',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Year_of_graduation',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Region',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Intervention',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DOB',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sub_City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Zone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'House_No',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Remark',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Education_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Department',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Minor',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Major',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Languages',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Certifications',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'GPA',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Campaign',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Work_Experience',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Company',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Position',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'block',
'vertSummary' => true ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview',
'grid_details_link',
'details_preview1',
'grid_details_link1',
'details_preview2',
'grid_details_link2' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'filter_panel' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'search_panel' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'text' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-chart',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search_field',
'simple_search_option',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6',
'report_group_field7',
'report_group_field8',
'report_group_field9',
'report_group_field10',
'report_group_field11',
'report_group_field12',
'report_group_field13',
'report_group_field14',
'report_group_field15',
'report_group_field16',
'report_group_field17',
'report_group_field18' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26',
'report_grid_field27',
'report_grid_field28',
'report_grid_field29',
'report_grid_field30',
'report_grid_field31',
'report_grid_field32',
'report_grid_field33',
'report_grid_field34',
'report_grid_field35',
'report_grid_field36',
'report_grid_field37',
'report_grid_field38',
'report_grid_field39',
'report_grid_field40',
'report_grid_field41',
'report_grid_field42',
'report_grid_field43',
'report_grid_field44',
'report_grid_field45',
'report_grid_field46',
'report_grid_field47',
'report_grid_field48',
'report_grid_field49',
'report_grid_field50',
'report_grid_field51',
'report_grid_field52',
'report_grid_field53',
'report_grid_field54',
'report_grid_field55',
'report_grid_field56' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'field' => 'Sex',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DOB',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Region',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'City',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Languages',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_Completed_Courses',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_1st Round',
'color' => array( 'header' => 'd9d3bb',
'summary' => 'fff8dc' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'DAAP_enrolled_2nd_Round',
'color' => array( 'header' => '93d928',
'summary' => 'adff2f' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Department',
'color' => array( 'header' => 'bed9d9',
'summary' => 'e0ffff' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Field_Of_Study',
'color' => array( 'header' => 'd98868',
'summary' => 'ffa07a' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Enrollement_Type',
'color' => array( 'header' => 'd9bd93',
'summary' => 'ffdead' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Score',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Exit_Exam_Status',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'GPA',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Intervention',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Job_Fair_Clinic',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => true,
'field' => 'Year_of_graduation',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Region',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Year_of_graduation',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Intervention',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DOB',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sub_City',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Zone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'House_No',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone_Number_Alternate',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Institution_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Remark',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Education_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Department',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Minor',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Major',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Enrollement_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Languages',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'English_Proficiency_Level',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Industry_Specific_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'IT_Related_Skills',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Certifications',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Field_Of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'GPA',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Campaign',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Attend_Employability_Skill',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_1st Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_Completed_Courses',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair_Clinic',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Job_Fair',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Exit_Exam_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'DAAP_enrolled_2nd_Round',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Upload_on_Tracker',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Work_Experience',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Joined_Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Training_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Event_Services',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_web_profile_completion',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Dereja_Information_Source',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Company',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Employment_Position',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'block',
'vertSummary' => true ) ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'DerejaMenuSet' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word',
'export_report_pdf',
'-2',
'save_search',
'-3',
'saved_searches' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ),
'_flexiblePanel' => false ),
'report_grid_field56' => array( 'field' => 'Employment_Position',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'-' => array( 'type' => '-' ),
'report_grid_field55' => array( 'field' => 'Employment_Company',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field54' => array( 'field' => 'Employment_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field53' => array( 'field' => 'Dereja_Information_Source',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field52' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field51' => array( 'field' => 'Dereja_Event_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field50' => array( 'field' => 'Dereja_Training_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field49' => array( 'field' => 'Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field48' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field47' => array( 'field' => 'Work_Experience',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field46' => array( 'field' => 'Upload_on_Tracker',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field25' => array( 'field' => 'Minor',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field24' => array( 'field' => 'Department',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field23' => array( 'field' => 'Education_Level',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field22' => array( 'field' => 'Remark',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field21' => array( 'field' => 'Institution_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field20' => array( 'field' => 'Institution_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field19' => array( 'field' => 'Disability_Type_Other',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field18' => array( 'field' => 'Disability_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field17' => array( 'field' => 'Email_Address',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field16' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field45' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field44' => array( 'field' => 'Exit_Exam_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array(  ) ),
'report_grid_field15' => array( 'field' => 'Phone_Number',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field43' => array( 'field' => 'Exit_Exam_Score',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field1' => array( 'field' => 'Campaign',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field2' => array( 'field' => 'CandidateID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field3' => array( 'field' => 'Certifications',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field4' => array( 'field' => 'City',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field5' => array( 'field' => 'DAAP_Completed',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field6' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field7' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field8' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field9' => array( 'field' => 'DOB',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field10' => array( 'field' => 'Department',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field11' => array( 'field' => 'Dereja_Event_Services',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field12' => array( 'field' => 'Dereja_Information_Source',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field13' => array( 'field' => 'Dereja_Services',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field14' => array( 'field' => 'Dereja_Training_Services',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field15' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field16' => array( 'field' => 'Disability_Status',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field17' => array( 'field' => 'Disability_Type',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field18' => array( 'field' => 'Disability_Type_Other',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field19' => array( 'field' => 'Education_Level',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field20' => array( 'field' => 'Email_Address',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field21' => array( 'field' => 'Employment_Company',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field22' => array( 'field' => 'Employment_Position',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field23' => array( 'field' => 'Employment_Status',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field24' => array( 'field' => 'English_Proficiency_Level',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field25' => array( 'field' => 'Enrollement_Type',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field26' => array( 'field' => 'Exit_Exam_Score',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field27' => array( 'field' => 'Exit_Exam_Status',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field28' => array( 'field' => 'Field_Of_Study',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field29' => array( 'field' => 'First_Name',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field30' => array( 'field' => 'GPA',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field31' => array( 'field' => 'House_No',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field32' => array( 'field' => 'IT_Related_Skills',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field33' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field34' => array( 'field' => 'Institution_Name',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field35' => array( 'field' => 'Institution_Type',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field36' => array( 'field' => 'Intervention',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field37' => array( 'field' => 'Job_Fair',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field38' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field39' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field40' => array( 'field' => 'Languages',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field41' => array( 'field' => 'Last_Name',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field42' => array( 'field' => 'Major',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field43' => array( 'field' => 'Middle_Name',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field44' => array( 'field' => 'Minor',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field45' => array( 'field' => 'Phone_Number',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field46' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field47' => array( 'field' => 'Region',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field48' => array( 'field' => 'Remark',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field49' => array( 'field' => 'Sex',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field50' => array( 'field' => 'Skills',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field51' => array( 'field' => 'StudentID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field52' => array( 'field' => 'Sub_City',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field53' => array( 'field' => 'Upload_on_Tracker',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field54' => array( 'field' => 'Work_Experience',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field55' => array( 'field' => 'Year_of_graduation',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field56' => array( 'field' => 'Zone',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'Candidate_Employment_Tracker',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'simple_search_field' => array( 'type' => 'simple_search_field' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'Candidate_Employment_Tracker',
'badge' => false,
'hideIfNone' => false,
'showCount' => true ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'event_participants',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'event_participants',
'badge' => false,
'showCount' => true,
'hideIfNone' => false ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'training_participants',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'grid_details_link2' => array( 'type' => 'grid_details_link',
'table' => 'training_participants',
'badge' => false,
'showCount' => true,
'hideIfNone' => false ),
'report_grid_field42' => array( 'field' => 'Job_Fair',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field41' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field40' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field39' => array( 'field' => 'DAAP_Completed',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'-3' => array( 'type' => '-' ),
'saved_searches' => array( 'type' => 'saved_searches' ),
'-2' => array( 'type' => '-' ),
'save_search' => array( 'type' => 'save_search' ),
'report_grid_field14' => array( 'field' => 'House_No',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field13' => array( 'field' => 'Zone',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field12' => array( 'field' => 'Sub_City',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field11' => array( 'field' => 'City',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field10' => array( 'field' => 'DOB',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field9' => array( 'field' => 'Last_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field8' => array( 'field' => 'Middle_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field7' => array( 'field' => 'First_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field6' => array( 'field' => 'StudentID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field5' => array( 'field' => 'Intervention',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field4' => array( 'field' => 'Disability_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field3' => array( 'field' => 'Year_of_graduation',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field2' => array( 'field' => 'Region',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field1' => array( 'field' => 'Sex',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field' => array( 'field' => 'CandidateID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_group_field18' => array( 'field' => 'Year_of_graduation',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'report_group_field17' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field16' => array( 'field' => 'Job_Fair',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field15' => array( 'field' => 'Intervention',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field14' => array( 'field' => 'GPA',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field13' => array( 'field' => 'Exit_Exam_Status',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field12' => array( 'field' => 'Exit_Exam_Score',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field11' => array( 'field' => 'Enrollement_Type',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field10' => array( 'field' => 'Field_Of_Study',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field9' => array( 'field' => 'Department',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field8' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field7' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field6' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field5' => array( 'field' => 'DAAP_Completed',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field4' => array( 'field' => 'Languages',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'City',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'Region',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'DOB',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field' => array( 'field' => 'Sex',
'type' => 'report_group_field',
'summary' => true,
'axis' => 2,
'interval' => 0 ),
'export_report_pdf' => array( 'type' => 'export_report_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'simple_search_option' => array( 'type' => 'simple_search_option' ),
'report_grid_field38' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field37' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field36' => array( 'field' => 'Campaign',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field35' => array( 'field' => 'GPA',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field34' => array( 'field' => 'Field_Of_Study',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field33' => array( 'field' => 'Certifications',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field32' => array( 'field' => 'IT_Related_Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field31' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field30' => array( 'field' => 'English_Proficiency_Level',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field29' => array( 'field' => 'Languages',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field28' => array( 'field' => 'Skills',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field27' => array( 'field' => 'Enrollement_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field26' => array( 'field' => 'Major',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>Search to Filter Report using the Search Panel</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>Cross Tab Reports</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>