<?php
			$optionsArray = array( 'details' => array( 'event_participants' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'training_participants' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'Candidate_Employment_Tracker' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'Job_Fair' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'website_data' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'event_participants_view' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'training_participants_view' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'regions' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'event_participants_by_events' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'training_participants_by_trainings' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'candidates_by_gender' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'candidates_reports' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'candidates_by_region' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'Companies' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Date',
'Upload_on_Website',
'Intervention',
'Disability_Status',
'Attend_Employability_Skill',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Event_Services',
'Dereja_Training_Services',
'Dereja_Information_Source',
'Enrollement_Type',
'Year_of_graduation',
'Education_Level',
'Upload_on_Tracker',
'Major',
'Institution_Name',
'Minor',
'Dereja_web_profile_completion',
'Institution_Type',
'Field_Of_Study',
'GPA',
'DAAP_Completed',
'DAAP_enrolled_1st Round',
'Exit_Exam_Status',
'Department',
'DAAP_Completed_Courses',
'Exit_Exam_Score',
'House_No',
'Kebele',
'DAAP_enrolled_2nd_Round',
'Woreda',
'Zone',
'City',
'Sub_City',
'Region',
'Placement_Type',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Skills',
'Certifications',
'Languages',
'Employer_Sector',
'Work_Experience',
'Salary',
'Job_Fair',
'Job_Fair_Clinic',
'Remark',
'Employment_Company',
'Employment_Position',
'Employment_Status',
'Campaign',
'Phone_Number_Alternate',
'Phone_Number',
'Email_Address',
'DOB',
'Disability_Type',
'Sex',
'Middle_Name',
'Disability_Type_Other',
'StudentID',
'Last_Name',
'First_Name',
'Career_Level_Of_Payment',
'Placement_Duration' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array( 'Date',
'Upload_on_Website',
'Intervention',
'Disability_Status',
'Attend_Employability_Skill',
'Joined_Dereja_Services',
'Dereja_Services',
'Dereja_Event_Services',
'Dereja_Training_Services',
'Dereja_Information_Source',
'Enrollement_Type',
'Year_of_graduation',
'Education_Level',
'Upload_on_Tracker',
'Major',
'Institution_Name',
'Minor',
'Dereja_web_profile_completion',
'Institution_Type',
'Field_Of_Study',
'GPA',
'DAAP_Completed',
'DAAP_enrolled_1st Round',
'Exit_Exam_Status',
'Department',
'DAAP_Completed_Courses',
'Exit_Exam_Score',
'House_No',
'Kebele',
'DAAP_enrolled_2nd_Round',
'Woreda',
'Zone',
'City',
'Sub_City',
'Region',
'Placement_Type',
'English_Proficiency_Level',
'Industry_Specific_Skills',
'IT_Related_Skills',
'Skills',
'Certifications',
'Languages',
'Employer_Sector',
'Work_Experience',
'Salary',
'Job_Fair',
'Job_Fair_Clinic',
'Remark',
'Employment_Company',
'Employment_Position',
'Employment_Status',
'Campaign',
'Phone_Number_Alternate',
'Phone_Number',
'Email_Address',
'DOB',
'Disability_Type',
'Sex',
'Middle_Name',
'Disability_Type_Other',
'StudentID',
'Last_Name',
'First_Name',
'Career_Level_Of_Payment',
'Placement_Duration' ),
'fieldItems' => array( 'Date' => array( 'integrated_edit_field63' ),
'Upload_on_Website' => array( 'integrated_edit_field64' ),
'Intervention' => array( 'integrated_edit_field44' ),
'Disability_Status' => array( 'integrated_edit_field32' ),
'Attend_Employability_Skill' => array( 'integrated_edit_field46' ),
'Joined_Dereja_Services' => array( 'integrated_edit_field25' ),
'Dereja_Services' => array( 'integrated_edit_field26' ),
'Dereja_Event_Services' => array( 'integrated_edit_field28' ),
'Dereja_Training_Services' => array( 'integrated_edit_field27' ),
'Dereja_Information_Source' => array( 'integrated_edit_field30' ),
'Enrollement_Type' => array( 'integrated_edit_field43' ),
'Year_of_graduation' => array( 'integrated_edit_field23' ),
'Education_Level' => array( 'integrated_edit_field14' ),
'Upload_on_Tracker' => array( 'integrated_edit_field55' ),
'Major' => array( 'integrated_edit_field17' ),
'Institution_Name' => array( 'integrated_edit_field37' ),
'Minor' => array( 'integrated_edit_field16' ),
'Dereja_web_profile_completion' => array( 'integrated_edit_field29' ),
'Institution_Type' => array( 'integrated_edit_field13' ),
'Field_Of_Study' => array( 'integrated_edit_field35' ),
'GPA' => array( 'integrated_edit_field36' ),
'DAAP_Completed' => array( 'integrated_edit_field48' ),
'DAAP_enrolled_1st Round' => array( 'integrated_edit_field47' ),
'Exit_Exam_Status' => array( 'integrated_edit_field53' ),
'Department' => array( 'integrated_edit_field15' ),
'DAAP_Completed_Courses' => array( 'integrated_edit_field49' ),
'Exit_Exam_Score' => array( 'integrated_edit_field52' ),
'House_No' => array( 'integrated_edit_field9' ),
'Kebele' => array( 'integrated_edit_field57' ),
'DAAP_enrolled_2nd_Round' => array( 'integrated_edit_field54' ),
'Woreda' => array( 'integrated_edit_field56' ),
'Zone' => array( 'integrated_edit_field8' ),
'City' => array( 'integrated_edit_field6' ),
'Sub_City' => array( 'integrated_edit_field7' ),
'Region' => array( 'integrated_edit_field5' ),
'Placement_Type' => array( 'integrated_edit_field61' ),
'English_Proficiency_Level' => array( 'integrated_edit_field19' ),
'Industry_Specific_Skills' => array( 'integrated_edit_field20' ),
'IT_Related_Skills' => array( 'integrated_edit_field21' ),
'Skills' => array( 'integrated_edit_field18' ),
'Certifications' => array( 'integrated_edit_field22' ),
'Languages' => array( 'integrated_edit_field38' ),
'Employer_Sector' => array( 'integrated_edit_field58' ),
'Work_Experience' => array( 'integrated_edit_field24' ),
'Salary' => array( 'integrated_edit_field59' ),
'Job_Fair' => array( 'integrated_edit_field51' ),
'Job_Fair_Clinic' => array( 'integrated_edit_field50' ),
'Remark' => array( 'integrated_edit_field42' ),
'Employment_Company' => array( 'integrated_edit_field40' ),
'Employment_Position' => array( 'integrated_edit_field41' ),
'Employment_Status' => array( 'integrated_edit_field39' ),
'Campaign' => array( 'integrated_edit_field45' ),
'Phone_Number_Alternate' => array( 'integrated_edit_field11' ),
'Phone_Number' => array( 'integrated_edit_field10' ),
'Email_Address' => array( 'integrated_edit_field12' ),
'DOB' => array( 'integrated_edit_field4' ),
'Disability_Type' => array( 'integrated_edit_field33' ),
'Sex' => array( 'integrated_edit_field3' ),
'Middle_Name' => array( 'integrated_edit_field1' ),
'Disability_Type_Other' => array( 'integrated_edit_field34' ),
'StudentID' => array( 'integrated_edit_field31' ),
'Last_Name' => array( 'integrated_edit_field2' ),
'First_Name' => array( 'integrated_edit_field' ),
'Career_Level_Of_Payment' => array( 'integrated_edit_field60' ),
'Placement_Duration' => array( 'integrated_edit_field62' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'notifications',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'section',
'section4',
'section2',
'section5',
'section10',
'section7',
'section9',
'section3',
'section1',
'section8',
'section6',
'master_info',
'integrated_edit_field63' ),
'section' => array( 'integrated_edit_field31',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field34',
'integrated_edit_field1',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field4',
'integrated_edit_field12',
'integrated_edit_field10',
'integrated_edit_field11' ),
'section4' => array( 'integrated_edit_field44',
'integrated_edit_field30',
'integrated_edit_field46',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27' ),
'section2' => array( 'integrated_edit_field14',
'integrated_edit_field43',
'integrated_edit_field23',
'integrated_edit_field15',
'integrated_edit_field17',
'integrated_edit_field37',
'integrated_edit_field16',
'integrated_edit_field13',
'integrated_edit_field35',
'integrated_edit_field36' ),
'section5' => array( 'integrated_edit_field48',
'integrated_edit_field47',
'integrated_edit_field54',
'integrated_edit_field49',
'integrated_edit_field45',
'integrated_edit_field51',
'integrated_edit_field50' ),
'section10' => array( 'integrated_edit_field42' ),
'section7' => array( 'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field58',
'integrated_edit_field41',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field60',
'integrated_edit_field59',
'integrated_edit_field24' ),
'section9' => array( 'details_preview',
'details_preview1' ),
'section3' => array( 'integrated_edit_field38',
'integrated_edit_field22',
'integrated_edit_field18',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19' ),
'section1' => array( 'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field9' ),
'section8' => array( 'integrated_edit_field52',
'integrated_edit_field53' ),
'section6' => array( 'integrated_edit_field29',
'integrated_edit_field55',
'integrated_edit_field64' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'update_records' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'section' => 'grid',
'section4' => 'grid',
'section2' => 'grid',
'section5' => 'grid',
'section10' => 'grid',
'section7' => 'grid',
'section9' => 'grid',
'section3' => 'grid',
'section1' => 'grid',
'section8' => 'grid',
'section6' => 'grid',
'master_info' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field31' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field34' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field32' => 'section',
'integrated_edit_field33' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field44' => 'section4',
'integrated_edit_field30' => 'section4',
'integrated_edit_field46' => 'section4',
'integrated_edit_field25' => 'section4',
'integrated_edit_field26' => 'section4',
'integrated_edit_field28' => 'section4',
'integrated_edit_field27' => 'section4',
'integrated_edit_field14' => 'section2',
'integrated_edit_field43' => 'section2',
'integrated_edit_field23' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field37' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field35' => 'section2',
'integrated_edit_field36' => 'section2',
'integrated_edit_field48' => 'section5',
'integrated_edit_field47' => 'section5',
'integrated_edit_field54' => 'section5',
'integrated_edit_field49' => 'section5',
'integrated_edit_field45' => 'section5',
'integrated_edit_field51' => 'section5',
'integrated_edit_field50' => 'section5',
'integrated_edit_field42' => 'section10',
'integrated_edit_field39' => 'section7',
'integrated_edit_field40' => 'section7',
'integrated_edit_field58' => 'section7',
'integrated_edit_field41' => 'section7',
'integrated_edit_field61' => 'section7',
'integrated_edit_field62' => 'section7',
'integrated_edit_field60' => 'section7',
'integrated_edit_field59' => 'section7',
'integrated_edit_field24' => 'section7',
'details_preview' => 'section9',
'details_preview1' => 'section9',
'integrated_edit_field38' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field18' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field19' => 'section3',
'integrated_edit_field5' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field56' => 'section1',
'integrated_edit_field57' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field52' => 'section8',
'integrated_edit_field53' => 'section8',
'integrated_edit_field29' => 'section6',
'integrated_edit_field55' => 'section6',
'integrated_edit_field64' => 'section6' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'section5' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'section10' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'section7' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'section9' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'section8' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'section6' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'master_info' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field31' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field34' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field32' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field33' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field44' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field46' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'section2',
'cellId' => 'c8' ),
'integrated_edit_field23' => array( 'location' => 'section2',
'cellId' => 'c9' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c10' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c11' ),
'integrated_edit_field37' => array( 'location' => 'section2',
'cellId' => 'c12' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c13' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c17' ),
'integrated_edit_field35' => array( 'location' => 'section2',
'cellId' => 'c19' ),
'integrated_edit_field36' => array( 'location' => 'section2',
'cellId' => 'c20' ),
'integrated_edit_field48' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field49' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field45' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field51' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field50' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field42' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field58' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field61' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field62' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field60' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field59' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'section7',
'cellId' => 'c4' ),
'details_preview' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section9',
'cellId' => 'c2' ),
'integrated_edit_field38' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c7' ),
'integrated_edit_field19' => array( 'location' => 'section3',
'cellId' => 'c8' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field56' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field57' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field52' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field53' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field55' => array( 'location' => 'section6',
'cellId' => 'c' ),
'integrated_edit_field64' => array( 'location' => 'section6',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'menu' => array( 'menu' ),
'collapse_button' => array( 'collapse_button' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field44',
'integrated_edit_field32',
'integrated_edit_field46',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field30',
'integrated_edit_field43',
'integrated_edit_field23',
'integrated_edit_field14',
'integrated_edit_field55',
'integrated_edit_field17',
'integrated_edit_field37',
'integrated_edit_field16',
'integrated_edit_field29',
'integrated_edit_field13',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field48',
'integrated_edit_field47',
'integrated_edit_field53',
'integrated_edit_field15',
'integrated_edit_field49',
'integrated_edit_field52',
'integrated_edit_field9',
'integrated_edit_field57',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field8',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field5',
'integrated_edit_field61',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field18',
'integrated_edit_field22',
'integrated_edit_field38',
'integrated_edit_field58',
'integrated_edit_field24',
'integrated_edit_field59',
'integrated_edit_field51',
'integrated_edit_field50',
'integrated_edit_field42',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field39',
'integrated_edit_field45',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field4',
'integrated_edit_field33',
'integrated_edit_field3',
'integrated_edit_field1',
'integrated_edit_field34',
'integrated_edit_field31',
'integrated_edit_field2',
'integrated_edit_field',
'integrated_edit_field60',
'integrated_edit_field62' ),
'master_info' => array( 'master_info' ),
'section' => array( 'section4',
'section2',
'section6',
'section5',
'section8',
'section1',
'section3',
'section9',
'section10',
'section7',
'section' ),
'logo' => array( 'logo1' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ),
'update_records' => array( 'update_records' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'details_preview' => array( 'details_preview1',
'details_preview' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'section7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'section9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'section10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field63' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 9 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2,
3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44',
'integrated_edit_field30',
'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 3 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48',
'integrated_edit_field47',
'integrated_edit_field54',
'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45',
'integrated_edit_field51',
'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field58',
'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field60',
'integrated_edit_field59' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field56' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field57' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field52' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55',
'integrated_edit_field64' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array( 'update_records' => array( 'tag' => 'UPDATE_N_RECORDS',
'type' => 2 ) ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => true ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'notifications',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'update_records',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 4 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 3 ),
array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 3 ),
array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ),
array( 'cell' => 'c15',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ),
array( 'cell' => 'c16',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c22',
'colspan' => 4 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23',
'colspan' => 4 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section' ) ),
'c1' => array( 'model' => 'c3',
'items' => array( 'section4' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'section2' ),
'align' => 'center' ),
'c15' => array( 'model' => 'c3',
'items' => array( 'section5' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'section10' ),
'align' => 'center' ),
'c22' => array( 'model' => 'c3',
'items' => array( 'section7' ),
'align' => 'center' ),
'c23' => array( 'model' => 'c3',
'items' => array( 'section9' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c3',
'items' => array( 'section3' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'section1' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'section8' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'section6' ),
'align' => 'center' ),
'c' => array( 'model' => 'c3',
'items' => array( 'master_info' ) ),
'c7' => array( 'model' => 'c3',
'items' => array(  ) ),
'c8' => array( 'model' => 'c3',
'items' => array(  ) ),
'c9' => array( 'model' => 'c3',
'items' => array(  ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field63' ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'columnCount' => 4,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ),
array( 'cell' => 'c10',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c6',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field44',
'integrated_edit_field30',
'integrated_edit_field46' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field27' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c8' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17' ),
array( 'cell' => 'c19',
'colspan' => 2 ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ),
'c20' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48',
'integrated_edit_field47',
'integrated_edit_field54',
'integrated_edit_field49' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field45',
'integrated_edit_field51',
'integrated_edit_field50' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c5',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field58',
'integrated_edit_field41' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field60',
'integrated_edit_field59' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field56' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field57' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field52' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field53' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55',
'integrated_edit_field64' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'DerejaMenuSet' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field63' => array( 'field' => 'Date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'Companies' => 'true' ) ),
'integrated_edit_field64' => array( 'field' => 'Upload_on_Website',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section4' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Dereja Intervention and Services' ),
'location' => 'section4',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field44' => array( 'field' => 'Intervention',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field32' => array( 'field' => 'Disability_Status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field46' => array( 'field' => 'Attend_Employability_Skill',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field25' => array( 'field' => 'Joined_Dereja_Services',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field26' => array( 'field' => 'Dereja_Services',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field28' => array( 'field' => 'Dereja_Event_Services',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field27' => array( 'field' => 'Dereja_Training_Services',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section2' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Education' ),
'location' => 'section2',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field30' => array( 'field' => 'Dereja_Information_Source',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field43' => array( 'field' => 'Enrollement_Type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field23' => array( 'field' => 'Year_of_graduation',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field14' => array( 'field' => 'Education_Level',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field55' => array( 'field' => 'Upload_on_Tracker',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field17' => array( 'field' => 'Major',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field37' => array( 'field' => 'Institution_Name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field16' => array( 'field' => 'Minor',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field29' => array( 'field' => 'Dereja_web_profile_completion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field13' => array( 'field' => 'Institution_Type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field35' => array( 'field' => 'Field_Of_Study',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field36' => array( 'field' => 'GPA',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section6' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Profile Tracking ' ),
'location' => 'section6',
'bsStyle' => 'default',
'panelType' => 3 ),
'section5' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Participations' ),
'location' => 'section5',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field48' => array( 'field' => 'DAAP_Completed',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field47' => array( 'field' => 'DAAP_enrolled_1st Round',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field53' => array( 'field' => 'Exit_Exam_Status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field15' => array( 'field' => 'Department',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field49' => array( 'field' => 'DAAP_Completed_Courses',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'logo1' => array( 'type' => 'logo' ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'update_records' => array( 'type' => 'update_records' ),
'integrated_edit_field52' => array( 'field' => 'Exit_Exam_Score',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section8' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Examinations' ),
'location' => 'section8',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field9' => array( 'field' => 'House_No',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field57' => array( 'field' => 'Kebele',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field54' => array( 'field' => 'DAAP_enrolled_2nd_Round',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field56' => array( 'field' => 'Woreda',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'integrated_edit_field8' => array( 'field' => 'Zone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field6' => array( 'field' => 'City',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field7' => array( 'field' => 'Sub_City',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field5' => array( 'field' => 'Region',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Demography' ),
'location' => 'section1',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field61' => array( 'field' => 'Placement_Type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field19' => array( 'field' => 'English_Proficiency_Level',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field20' => array( 'field' => 'Industry_Specific_Skills',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field21' => array( 'field' => 'IT_Related_Skills',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field18' => array( 'field' => 'Skills',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field22' => array( 'field' => 'Certifications',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field38' => array( 'field' => 'Languages',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section3' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Skills' ),
'location' => 'section3',
'bsStyle' => 'default',
'panelType' => 3 ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'website_data',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'Job_Fair',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section9' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Details Website Data' ),
'location' => 'section9',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field58' => array( 'field' => 'Employer_Sector',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field24' => array( 'field' => 'Work_Experience',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field59' => array( 'field' => 'Salary',
'type' => 'integrated_edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'Salary',
'table' => 'candidates',
'type' => 4 ),
'updateOnEdit' => true ),
'notifications' => array( 'type' => 'notifications' ),
'integrated_edit_field51' => array( 'field' => 'Job_Fair',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field50' => array( 'field' => 'Job_Fair_Clinic',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section10' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Remarks' ),
'location' => 'section10',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field42' => array( 'field' => 'Remark',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field40' => array( 'field' => 'Employment_Company',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field41' => array( 'field' => 'Employment_Position',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section7' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Employment' ),
'location' => 'section7',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field39' => array( 'field' => 'Employment_Status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field45' => array( 'field' => 'Campaign',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field11' => array( 'field' => 'Phone_Number_Alternate',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field10' => array( 'field' => 'Phone_Number',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field12' => array( 'field' => 'Email_Address',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field4' => array( 'field' => 'DOB',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field33' => array( 'field' => 'Disability_Type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field3' => array( 'field' => 'Sex',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field1' => array( 'field' => 'Middle_Name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field34' => array( 'field' => 'Disability_Type_Other',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field31' => array( 'field' => 'StudentID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field2' => array( 'field' => 'Last_Name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field' => array( 'field' => 'First_Name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Candidate Profile' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'integrated_edit_field60' => array( 'field' => 'Career_Level_Of_Payment',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'integrated_edit_field62' => array( 'field' => 'Placement_Duration',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>