<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'EventID',
'First Name',
'Middle Name',
'Last Name',
'Sex',
'Event start date',
'Event end date',
'Event Name',
'Region',
'City',
'Participant Profession',
'Participant Field of Study',
'Participant Organization Type',
'Participant Organization Name',
'Participant Home Address',
'Phone Number',
'Email Address',
'Disablity Status',
'CandidateID',
'TrainingID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'EventID' => array( 'import_field' ),
'First Name' => array( 'import_field1' ),
'Middle Name' => array( 'import_field2' ),
'Last Name' => array( 'import_field3' ),
'Sex' => array( 'import_field4' ),
'Event start date' => array( 'import_field5' ),
'Event end date' => array( 'import_field6' ),
'Event Name' => array( 'import_field7' ),
'Region' => array( 'import_field8' ),
'City' => array( 'import_field9' ),
'Participant Profession' => array( 'import_field10' ),
'Participant Field of Study' => array( 'import_field11' ),
'Participant Organization Type' => array( 'import_field12' ),
'Participant Organization Name' => array( 'import_field13' ),
'Participant Home Address' => array( 'import_field14' ),
'Phone Number' => array( 'import_field15' ),
'Email Address' => array( 'import_field16' ),
'Disablity Status' => array( 'import_field17' ),
'CandidateID' => array( 'import_field18' ),
'TrainingID' => array( 'import_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field',
'import_field18',
'import_field19' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field',
'import_field18',
'import_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'EventID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'First Name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Middle Name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Last Name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Sex',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Event start date',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Event end date',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Event Name',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Region',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'City',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Participant Profession',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Participant Field of Study',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Participant Organization Type',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Participant Organization Name',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Participant Home Address',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Phone Number',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Email Address',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Disablity Status',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'CandidateID',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'TrainingID',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>