<?php
			$optionsArray = array( 'totals' => array( 'EventID' => array( 'totalsType' => '' ),
'CandidateID' => array( 'totalsType' => '' ),
'StudentID' => array( 'totalsType' => '' ),
'Event_Start_Date' => array( 'totalsType' => '' ),
'Event_End_Date' => array( 'totalsType' => '' ),
'Event_Round' => array( 'totalsType' => '' ),
'Event_Organizer' => array( 'totalsType' => '' ),
'Event_Location' => array( 'totalsType' => '' ),
'Event_Note' => array( 'totalsType' => '' ),
'First_Name' => array( 'totalsType' => '' ),
'Middle_Name' => array( 'totalsType' => '' ),
'Last_Name' => array( 'totalsType' => '' ),
'Sex' => array( 'totalsType' => '' ),
'Phone' => array( 'totalsType' => '' ),
'Email' => array( 'totalsType' => '' ),
'Disability_Status' => array( 'totalsType' => '' ),
'Disability_Type' => array( 'totalsType' => '' ),
'Disability_Type_Other' => array( 'totalsType' => '' ),
'Participant_Type' => array( 'totalsType' => '' ),
'Participant_Field_of_Study' => array( 'totalsType' => '' ),
'Participant_Organization_Type' => array( 'totalsType' => '' ),
'Participant_Organization_Name' => array( 'totalsType' => '' ),
'Participant_Home_Address' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'EventID',
'CandidateID',
'Event_Start_Date',
'Event_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Phone',
'Email',
'StudentID',
'Sex',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Type',
'Participant_Field_of_Study',
'Participant_Organization_Type',
'Participant_Organization_Name',
'Participant_Home_Address',
'Event_Round',
'Event_Organizer',
'Event_Location',
'Event_Note' ),
'exportFields' => array( 'EventID',
'CandidateID',
'Event_Start_Date',
'Event_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Phone',
'Email',
'StudentID',
'Sex',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Type',
'Participant_Field_of_Study',
'Participant_Organization_Type',
'Participant_Organization_Name',
'Participant_Home_Address',
'Event_Round',
'Event_Organizer',
'Event_Location',
'Event_Note' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'EventID' => array( 'export_field' ),
'CandidateID' => array( 'export_field1' ),
'Event_Start_Date' => array( 'export_field2' ),
'Event_End_Date' => array( 'export_field3' ),
'First_Name' => array( 'export_field4' ),
'Middle_Name' => array( 'export_field5' ),
'Last_Name' => array( 'export_field6' ),
'Phone' => array( 'export_field7' ),
'Email' => array( 'export_field8' ),
'StudentID' => array( 'export_field9' ),
'Sex' => array( 'export_field10' ),
'Disability_Status' => array( 'export_field11' ),
'Disability_Type' => array( 'export_field12' ),
'Disability_Type_Other' => array( 'export_field13' ),
'Participant_Type' => array( 'export_field14' ),
'Participant_Field_of_Study' => array( 'export_field15' ),
'Participant_Organization_Type' => array( 'export_field16' ),
'Participant_Organization_Name' => array( 'export_field17' ),
'Participant_Home_Address' => array( 'export_field18' ),
'Event_Round' => array( 'export_field19' ),
'Event_Organizer' => array( 'export_field20' ),
'Event_Location' => array( 'export_field21' ),
'Event_Note' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'EventID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CandidateID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Event_Start_Date',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Event_End_Date',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'First_Name',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Middle_Name',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Last_Name',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Phone',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Email',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'StudentID',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Sex',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Disability_Status',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Disability_Type',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Disability_Type_Other',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Participant_Type',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Participant_Field_of_Study',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Participant_Organization_Type',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Participant_Organization_Name',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Participant_Home_Address',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Event_Round',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Event_Organizer',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Event_Location',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Event_Note',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>