<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item2',
'dashboard-item1',
'dashboard-item3',
'dashboard-item7',
'dashboard-item',
'dashboard-item5',
'dashboard-item4',
'dashboard-item8' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'notifications',
'username_button',
'loginform_register' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item2' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item7' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item5' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item8' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'username_button' => 'supertop',
'loginform_register' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5',
'dashboard-item7',
'dashboard-item8' ),
'loginform_register' => array( 'loginform_register' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates_reports',
'dashType' => 1,
'dashName' => 'candidates_reports_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'table' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_reports_chart',
'table' => 'candidates_reports',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'training_participants_by_trainings',
'dashType' => 1,
'dashName' => 'training_participants_by_trainings_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'linode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'training_participants_by_trainings_chart',
'table' => 'training_participants_by_trainings',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'event_participants_by_events',
'dashType' => 1,
'dashName' => 'event_participants_by_events_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'calendar' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'event_participants_by_events_chart',
'table' => 'event_participants_by_events',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_gender',
'dashType' => 1,
'dashName' => 'candidates_by_gender_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'transgender-alt' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_by_gender_chart',
'table' => 'candidates_by_gender',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_sex_age_disability',
'dashType' => 1,
'dashName' => 'candidates_by_sex_age_disability_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_by_sex_age_disability_chart',
'table' => 'candidates_by_sex_age_disability',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_region',
'dashType' => 1,
'dashName' => 'candidates_by_region_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bar-chart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_by_region_chart',
'table' => 'candidates_by_region',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'indicator_targets',
'dashType' => 0,
'dashName' => 'indicator_targets_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'info-circle' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '#FB7409',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'indicator_targets_grid',
'table' => 'indicator_targets',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 0,
'dashName' => 'candidates_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_grid',
'table' => 'candidates',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'event_participants_by_events_EventID' => array( array( 'field' => 'EventID',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Event_Start_Date' => array( array( 'field' => 'Event_Start_Date',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Event_End_Date' => array( array( 'field' => 'Event_End_Date',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Sex' => array( array( 'field' => 'Sex',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Phone' => array( array( 'field' => 'Phone',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Email' => array( array( 'field' => 'Email',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Participant_Type' => array( array( 'field' => 'Participant_Type',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Participant_Field_of_Study' => array( array( 'field' => 'Participant_Field_of_Study',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Participant_Organization_Type' => array( array( 'field' => 'Participant_Organization_Type',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Participant_Organization_Name' => array( array( 'field' => 'Participant_Organization_Name',
'table' => 'event_participants_by_events' ) ),
'event_participants_by_events_Participant_Home_Address' => array( array( 'field' => 'Participant_Home_Address',
'table' => 'event_participants_by_events' ) ),
'training_participants_by_trainings_TrainingID' => array( array( 'field' => 'TrainingID',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_Organizer' => array( array( 'field' => 'Training_Organizer',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_Type' => array( array( 'field' => 'Training_Type',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Program_Area' => array( array( 'field' => 'Program_Area',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_City_Town' => array( array( 'field' => 'Training_City_Town',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_Venue' => array( array( 'field' => 'Training_Venue',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_Start_Date' => array( array( 'field' => 'Training_Start_Date',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Training_End_Date' => array( array( 'field' => 'Training_End_Date',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Sex' => array( array( 'field' => 'Sex',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Email' => array( array( 'field' => 'Email',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Phone' => array( array( 'field' => 'Phone',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Participant_Profession' => array( array( 'field' => 'Participant_Profession',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Participant_Field_of_Study' => array( array( 'field' => 'Participant_Field_of_Study',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Participant_Facility_Organization_Type' => array( array( 'field' => 'Participant_Facility_Organization_Type',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Participant_Organization_Name' => array( array( 'field' => 'Participant_Organization_Name',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Participants_Home_Address' => array( array( 'field' => 'Participants_Home_Address',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_PreTest_Score' => array( array( 'field' => 'PreTest_Score',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Skill_Test' => array( array( 'field' => 'Skill_Test',
'table' => 'training_participants_by_trainings' ) ),
'training_participants_by_trainings_Post_Test_Score' => array( array( 'field' => 'Post_Test_Score',
'table' => 'training_participants_by_trainings' ) ),
'candidates_reports_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'candidates_reports' ) ),
'candidates_reports_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'candidates_reports' ) ),
'candidates_reports_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'candidates_reports' ) ),
'candidates_reports_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'candidates_reports' ) ),
'candidates_reports_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'candidates_reports' ) ),
'candidates_reports_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates_reports' ) ),
'candidates_reports_DOB' => array( array( 'field' => 'DOB',
'table' => 'candidates_reports' ) ),
'candidates_reports_Region' => array( array( 'field' => 'Region',
'table' => 'candidates_reports' ) ),
'candidates_reports_City' => array( array( 'field' => 'City',
'table' => 'candidates_reports' ) ),
'candidates_reports_Sub_City' => array( array( 'field' => 'Sub_City',
'table' => 'candidates_reports' ) ),
'candidates_reports_Zone' => array( array( 'field' => 'Zone',
'table' => 'candidates_reports' ) ),
'candidates_reports_House_No' => array( array( 'field' => 'House_No',
'table' => 'candidates_reports' ) ),
'candidates_reports_Phone_Number' => array( array( 'field' => 'Phone_Number',
'table' => 'candidates_reports' ) ),
'candidates_reports_Phone_Number_Alternate' => array( array( 'field' => 'Phone_Number_Alternate',
'table' => 'candidates_reports' ) ),
'candidates_reports_Email_Address' => array( array( 'field' => 'Email_Address',
'table' => 'candidates_reports' ) ),
'candidates_reports_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'candidates_reports' ) ),
'candidates_reports_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'candidates_reports' ) ),
'candidates_reports_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'candidates_reports' ) ),
'candidates_reports_Institution_Type' => array( array( 'field' => 'Institution_Type',
'table' => 'candidates_reports' ) ),
'candidates_reports_Institution_Name' => array( array( 'field' => 'Institution_Name',
'table' => 'candidates_reports' ) ),
'candidates_reports_Education_Level' => array( array( 'field' => 'Education_Level',
'table' => 'candidates_reports' ) ),
'candidates_reports_Department' => array( array( 'field' => 'Department',
'table' => 'candidates_reports' ) ),
'candidates_reports_Minor' => array( array( 'field' => 'Minor',
'table' => 'candidates_reports' ) ),
'candidates_reports_Major' => array( array( 'field' => 'Major',
'table' => 'candidates_reports' ) ),
'candidates_reports_Enrollement_Type' => array( array( 'field' => 'Enrollement_Type',
'table' => 'candidates_reports' ) ),
'candidates_reports_Skills' => array( array( 'field' => 'Skills',
'table' => 'candidates_reports' ) ),
'candidates_reports_Languages' => array( array( 'field' => 'Languages',
'table' => 'candidates_reports' ) ),
'candidates_reports_English_Proficiency_Level' => array( array( 'field' => 'English_Proficiency_Level',
'table' => 'candidates_reports' ) ),
'candidates_reports_Industry_Specific_Skills' => array( array( 'field' => 'Industry_Specific_Skills',
'table' => 'candidates_reports' ) ),
'candidates_reports_IT_Related_Skills' => array( array( 'field' => 'IT_Related_Skills',
'table' => 'candidates_reports' ) ),
'candidates_reports_Certifications' => array( array( 'field' => 'Certifications',
'table' => 'candidates_reports' ) ),
'candidates_reports_Year_of_graduation' => array( array( 'field' => 'Year_of_graduation',
'table' => 'candidates_reports' ) ),
'candidates_reports_Field_Of_Study' => array( array( 'field' => 'Field_Of_Study',
'table' => 'candidates_reports' ) ),
'candidates_reports_GPA' => array( array( 'field' => 'GPA',
'table' => 'candidates_reports' ) ),
'candidates_reports_Intervention' => array( array( 'field' => 'Intervention',
'table' => 'candidates_reports' ) ),
'candidates_reports_Campaign' => array( array( 'field' => 'Campaign',
'table' => 'candidates_reports' ) ),
'candidates_reports_Attend_Employability_Skill' => array( array( 'field' => 'Attend_Employability_Skill',
'table' => 'candidates_reports' ) ),
'candidates_reports_DAAP_enrolled_1st_Round' => array( array( 'field' => 'DAAP_enrolled_1st Round',
'table' => 'candidates_reports' ) ),
'candidates_reports_DAAP_Completed' => array( array( 'field' => 'DAAP_Completed',
'table' => 'candidates_reports' ) ),
'candidates_reports_DAAP_Completed_Courses' => array( array( 'field' => 'DAAP_Completed_Courses',
'table' => 'candidates_reports' ) ),
'candidates_reports_Job_Fair_Clinic' => array( array( 'field' => 'Job_Fair_Clinic',
'table' => 'candidates_reports' ) ),
'candidates_reports_Job_Fair' => array( array( 'field' => 'Job_Fair',
'table' => 'candidates_reports' ) ),
'candidates_reports_Exit_Exam_Score' => array( array( 'field' => 'Exit_Exam_Score',
'table' => 'candidates_reports' ) ),
'candidates_reports_Exit_Exam_Status' => array( array( 'field' => 'Exit_Exam_Status',
'table' => 'candidates_reports' ) ),
'candidates_reports_DAAP_enrolled_2nd_Round' => array( array( 'field' => 'DAAP_enrolled_2nd_Round',
'table' => 'candidates_reports' ) ),
'candidates_reports_Upload_on_Tracker' => array( array( 'field' => 'Upload_on_Tracker',
'table' => 'candidates_reports' ) ),
'candidates_reports_Work_Experience' => array( array( 'field' => 'Work_Experience',
'table' => 'candidates_reports' ) ),
'candidates_reports_Joined_Dereja_Services' => array( array( 'field' => 'Joined_Dereja_Services',
'table' => 'candidates_reports' ) ),
'candidates_reports_Dereja_Services' => array( array( 'field' => 'Dereja_Services',
'table' => 'candidates_reports' ) ),
'candidates_reports_Dereja_Training_Services' => array( array( 'field' => 'Dereja_Training_Services',
'table' => 'candidates_reports' ) ),
'candidates_reports_Dereja_Event_Services' => array( array( 'field' => 'Dereja_Event_Services',
'table' => 'candidates_reports' ) ),
'candidates_reports_Dereja_web_profile_completion' => array( array( 'field' => 'Dereja_web_profile_completion',
'table' => 'candidates_reports' ) ),
'candidates_reports_Dereja_Information_Source' => array( array( 'field' => 'Dereja_Information_Source',
'table' => 'candidates_reports' ) ),
'candidates_reports_Employment_Status' => array( array( 'field' => 'Employment_Status',
'table' => 'candidates_reports' ) ),
'candidates_reports_Employment_Company' => array( array( 'field' => 'Employment_Company',
'table' => 'candidates_reports' ) ),
'candidates_reports_Employment_Position' => array( array( 'field' => 'Employment_Position',
'table' => 'candidates_reports' ) ),
'candidates_reports_Remark' => array( array( 'field' => 'Remark',
'table' => 'candidates_reports' ) ),
'candidates_by_gender_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_DOB' => array( array( 'field' => 'DOB',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Region' => array( array( 'field' => 'Region',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_City' => array( array( 'field' => 'City',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Sub_City' => array( array( 'field' => 'Sub_City',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Zone' => array( array( 'field' => 'Zone',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_House_No' => array( array( 'field' => 'House_No',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Phone_Number' => array( array( 'field' => 'Phone_Number',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Phone_Number_Alternate' => array( array( 'field' => 'Phone_Number_Alternate',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Email_Address' => array( array( 'field' => 'Email_Address',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Institution_Type' => array( array( 'field' => 'Institution_Type',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Institution_Name' => array( array( 'field' => 'Institution_Name',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Education_Level' => array( array( 'field' => 'Education_Level',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Department' => array( array( 'field' => 'Department',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Minor' => array( array( 'field' => 'Minor',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Major' => array( array( 'field' => 'Major',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Enrollement_Type' => array( array( 'field' => 'Enrollement_Type',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Skills' => array( array( 'field' => 'Skills',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Languages' => array( array( 'field' => 'Languages',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_English_Proficiency_Level' => array( array( 'field' => 'English_Proficiency_Level',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Industry_Specific_Skills' => array( array( 'field' => 'Industry_Specific_Skills',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_IT_Related_Skills' => array( array( 'field' => 'IT_Related_Skills',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Certifications' => array( array( 'field' => 'Certifications',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Year_of_graduation' => array( array( 'field' => 'Year_of_graduation',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Field_Of_Study' => array( array( 'field' => 'Field_Of_Study',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_GPA' => array( array( 'field' => 'GPA',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Intervention' => array( array( 'field' => 'Intervention',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Campaign' => array( array( 'field' => 'Campaign',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Attend_Employability_Skill' => array( array( 'field' => 'Attend_Employability_Skill',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_DAAP_enrolled_1st_Round' => array( array( 'field' => 'DAAP_enrolled_1st Round',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_DAAP_Completed' => array( array( 'field' => 'DAAP_Completed',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_DAAP_Completed_Courses' => array( array( 'field' => 'DAAP_Completed_Courses',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Job_Fair_Clinic' => array( array( 'field' => 'Job_Fair_Clinic',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Job_Fair' => array( array( 'field' => 'Job_Fair',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Exit_Exam_Score' => array( array( 'field' => 'Exit_Exam_Score',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Exit_Exam_Status' => array( array( 'field' => 'Exit_Exam_Status',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_DAAP_enrolled_2nd_Round' => array( array( 'field' => 'DAAP_enrolled_2nd_Round',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Upload_on_Tracker' => array( array( 'field' => 'Upload_on_Tracker',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Work_Experience' => array( array( 'field' => 'Work_Experience',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Joined_Dereja_Services' => array( array( 'field' => 'Joined_Dereja_Services',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Dereja_Services' => array( array( 'field' => 'Dereja_Services',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Dereja_Training_Services' => array( array( 'field' => 'Dereja_Training_Services',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Dereja_Event_Services' => array( array( 'field' => 'Dereja_Event_Services',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Dereja_web_profile_completion' => array( array( 'field' => 'Dereja_web_profile_completion',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Dereja_Information_Source' => array( array( 'field' => 'Dereja_Information_Source',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Employment_Status' => array( array( 'field' => 'Employment_Status',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Employment_Company' => array( array( 'field' => 'Employment_Company',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Employment_Position' => array( array( 'field' => 'Employment_Position',
'table' => 'candidates_by_gender' ) ),
'candidates_by_gender_Remark' => array( array( 'field' => 'Remark',
'table' => 'candidates_by_gender' ) ),
'candidates_by_region_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_DOB' => array( array( 'field' => 'DOB',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Region' => array( array( 'field' => 'Region',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_City' => array( array( 'field' => 'City',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Sub_City' => array( array( 'field' => 'Sub_City',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Zone' => array( array( 'field' => 'Zone',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_House_No' => array( array( 'field' => 'House_No',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Phone_Number' => array( array( 'field' => 'Phone_Number',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Phone_Number_Alternate' => array( array( 'field' => 'Phone_Number_Alternate',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Email_Address' => array( array( 'field' => 'Email_Address',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Institution_Type' => array( array( 'field' => 'Institution_Type',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Institution_Name' => array( array( 'field' => 'Institution_Name',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Education_Level' => array( array( 'field' => 'Education_Level',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Department' => array( array( 'field' => 'Department',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Minor' => array( array( 'field' => 'Minor',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Major' => array( array( 'field' => 'Major',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Enrollement_Type' => array( array( 'field' => 'Enrollement_Type',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Skills' => array( array( 'field' => 'Skills',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Languages' => array( array( 'field' => 'Languages',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_English_Proficiency_Level' => array( array( 'field' => 'English_Proficiency_Level',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Industry_Specific_Skills' => array( array( 'field' => 'Industry_Specific_Skills',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_IT_Related_Skills' => array( array( 'field' => 'IT_Related_Skills',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Certifications' => array( array( 'field' => 'Certifications',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Year_of_graduation' => array( array( 'field' => 'Year_of_graduation',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Field_Of_Study' => array( array( 'field' => 'Field_Of_Study',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_GPA' => array( array( 'field' => 'GPA',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Intervention' => array( array( 'field' => 'Intervention',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Campaign' => array( array( 'field' => 'Campaign',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Attend_Employability_Skill' => array( array( 'field' => 'Attend_Employability_Skill',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_DAAP_enrolled_1st_Round' => array( array( 'field' => 'DAAP_enrolled_1st Round',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_DAAP_Completed' => array( array( 'field' => 'DAAP_Completed',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_DAAP_Completed_Courses' => array( array( 'field' => 'DAAP_Completed_Courses',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Job_Fair_Clinic' => array( array( 'field' => 'Job_Fair_Clinic',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Job_Fair' => array( array( 'field' => 'Job_Fair',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Exit_Exam_Score' => array( array( 'field' => 'Exit_Exam_Score',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Exit_Exam_Status' => array( array( 'field' => 'Exit_Exam_Status',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_DAAP_enrolled_2nd_Round' => array( array( 'field' => 'DAAP_enrolled_2nd_Round',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Upload_on_Tracker' => array( array( 'field' => 'Upload_on_Tracker',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Work_Experience' => array( array( 'field' => 'Work_Experience',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Joined_Dereja_Services' => array( array( 'field' => 'Joined_Dereja_Services',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Dereja_Services' => array( array( 'field' => 'Dereja_Services',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Dereja_Training_Services' => array( array( 'field' => 'Dereja_Training_Services',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Dereja_Event_Services' => array( array( 'field' => 'Dereja_Event_Services',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Dereja_web_profile_completion' => array( array( 'field' => 'Dereja_web_profile_completion',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Dereja_Information_Source' => array( array( 'field' => 'Dereja_Information_Source',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Employment_Status' => array( array( 'field' => 'Employment_Status',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Employment_Company' => array( array( 'field' => 'Employment_Company',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Employment_Position' => array( array( 'field' => 'Employment_Position',
'table' => 'candidates_by_region' ) ),
'candidates_by_region_Remark' => array( array( 'field' => 'Remark',
'table' => 'candidates_by_region' ) ),
'candidates_by_sex_age_disability_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates_by_sex_age_disability' ) ),
'candidates_by_sex_age_disability_Disabled' => array( array( 'field' => 'Disabled',
'table' => 'candidates_by_sex_age_disability' ) ),
'candidates_by_sex_age_disability_Not_Disabled' => array( array( 'field' => 'Not_Disabled',
'table' => 'candidates_by_sex_age_disability' ) ),
'candidates_by_sex_age_disability_Age_18_and_Above' => array( array( 'field' => 'Age_18_and_Above',
'table' => 'candidates_by_sex_age_disability' ) ),
'candidates_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'candidates' ) ),
'candidates_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'candidates' ) ),
'candidates_Full_Name' => array( array( 'field' => 'Full_Name',
'table' => 'candidates' ) ),
'candidates_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'candidates' ) ),
'candidates_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'candidates' ) ),
'candidates_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'candidates' ) ),
'candidates_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates' ) ),
'candidates_DOB' => array( array( 'field' => 'DOB',
'table' => 'candidates' ) ),
'candidates_Age' => array( array( 'field' => 'Age',
'table' => 'candidates' ) ),
'candidates_Region' => array( array( 'field' => 'Region',
'table' => 'candidates' ) ),
'candidates_City' => array( array( 'field' => 'City',
'table' => 'candidates' ) ),
'candidates_Sub_City' => array( array( 'field' => 'Sub_City',
'table' => 'candidates' ) ),
'candidates_Zone' => array( array( 'field' => 'Zone',
'table' => 'candidates' ) ),
'candidates_House_No' => array( array( 'field' => 'House_No',
'table' => 'candidates' ) ),
'candidates_Phone_Number' => array( array( 'field' => 'Phone_Number',
'table' => 'candidates' ) ),
'candidates_Phone_Number_Alternate' => array( array( 'field' => 'Phone_Number_Alternate',
'table' => 'candidates' ) ),
'candidates_Email_Address' => array( array( 'field' => 'Email_Address',
'table' => 'candidates' ) ),
'candidates_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'candidates' ) ),
'candidates_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'candidates' ) ),
'candidates_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'candidates' ) ),
'candidates_Institution_Type' => array( array( 'field' => 'Institution_Type',
'table' => 'candidates' ) ),
'candidates_Institution_Name' => array( array( 'field' => 'Institution_Name',
'table' => 'candidates' ) ),
'candidates_Education_Level' => array( array( 'field' => 'Education_Level',
'table' => 'candidates' ) ),
'candidates_Department' => array( array( 'field' => 'Department',
'table' => 'candidates' ) ),
'candidates_Minor' => array( array( 'field' => 'Minor',
'table' => 'candidates' ) ),
'candidates_Major' => array( array( 'field' => 'Major',
'table' => 'candidates' ) ),
'candidates_Enrollement_Type' => array( array( 'field' => 'Enrollement_Type',
'table' => 'candidates' ) ),
'candidates_Skills' => array( array( 'field' => 'Skills',
'table' => 'candidates' ) ),
'candidates_Languages' => array( array( 'field' => 'Languages',
'table' => 'candidates' ) ),
'candidates_English_Proficiency_Level' => array( array( 'field' => 'English_Proficiency_Level',
'table' => 'candidates' ) ),
'candidates_Industry_Specific_Skills' => array( array( 'field' => 'Industry_Specific_Skills',
'table' => 'candidates' ) ),
'candidates_IT_Related_Skills' => array( array( 'field' => 'IT_Related_Skills',
'table' => 'candidates' ) ),
'candidates_Certifications' => array( array( 'field' => 'Certifications',
'table' => 'candidates' ) ),
'candidates_Year_of_graduation' => array( array( 'field' => 'Year_of_graduation',
'table' => 'candidates' ) ),
'candidates_Field_Of_Study' => array( array( 'field' => 'Field_Of_Study',
'table' => 'candidates' ) ),
'candidates_GPA' => array( array( 'field' => 'GPA',
'table' => 'candidates' ) ),
'candidates_Intervention' => array( array( 'field' => 'Intervention',
'table' => 'candidates' ) ),
'candidates_Campaign' => array( array( 'field' => 'Campaign',
'table' => 'candidates' ) ),
'candidates_Attend_Employability_Skill' => array( array( 'field' => 'Attend_Employability_Skill',
'table' => 'candidates' ) ),
'candidates_DAAP_enrolled_1st_Round' => array( array( 'field' => 'DAAP_enrolled_1st Round',
'table' => 'candidates' ) ),
'candidates_DAAP_Completed' => array( array( 'field' => 'DAAP_Completed',
'table' => 'candidates' ) ),
'candidates_DAAP_Completed_Courses' => array( array( 'field' => 'DAAP_Completed_Courses',
'table' => 'candidates' ) ),
'candidates_Job_Fair_Clinic' => array( array( 'field' => 'Job_Fair_Clinic',
'table' => 'candidates' ) ),
'candidates_Job_Fair' => array( array( 'field' => 'Job_Fair',
'table' => 'candidates' ) ),
'candidates_Exit_Exam_Score' => array( array( 'field' => 'Exit_Exam_Score',
'table' => 'candidates' ) ),
'candidates_Exit_Exam_Status' => array( array( 'field' => 'Exit_Exam_Status',
'table' => 'candidates' ) ),
'candidates_DAAP_enrolled_2nd_Round' => array( array( 'field' => 'DAAP_enrolled_2nd_Round',
'table' => 'candidates' ) ),
'candidates_Upload_on_Tracker' => array( array( 'field' => 'Upload_on_Tracker',
'table' => 'candidates' ) ),
'candidates_Work_Experience' => array( array( 'field' => 'Work_Experience',
'table' => 'candidates' ) ),
'candidates_Joined_Dereja_Services' => array( array( 'field' => 'Joined_Dereja_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Services' => array( array( 'field' => 'Dereja_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Training_Services' => array( array( 'field' => 'Dereja_Training_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Event_Services' => array( array( 'field' => 'Dereja_Event_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_web_profile_completion' => array( array( 'field' => 'Dereja_web_profile_completion',
'table' => 'candidates' ) ),
'candidates_Dereja_Information_Source' => array( array( 'field' => 'Dereja_Information_Source',
'table' => 'candidates' ) ),
'candidates_Employment_Status' => array( array( 'field' => 'Employment_Status',
'table' => 'candidates' ) ),
'candidates_Employment_Company' => array( array( 'field' => 'Employment_Company',
'table' => 'candidates' ) ),
'candidates_Employment_Position' => array( array( 'field' => 'Employment_Position',
'table' => 'candidates' ) ),
'candidates_Remark' => array( array( 'field' => 'Remark',
'table' => 'candidates' ) ),
'indicator_targets_IndicatorID' => array( array( 'field' => 'IndicatorID',
'table' => 'indicator_targets' ) ),
'indicator_targets_IndicatorName' => array( array( 'field' => 'IndicatorName',
'table' => 'indicator_targets' ) ),
'indicator_targets_IndicatorDescription' => array( array( 'field' => 'IndicatorDescription',
'table' => 'indicator_targets' ) ),
'indicator_targets_IndicatorValue' => array( array( 'field' => 'IndicatorValue',
'table' => 'indicator_targets' ) ),
'indicator_targets_IndicatorTarget' => array( array( 'field' => 'IndicatorTarget',
'table' => 'indicator_targets' ) ) ),
'allSearchFields' => array( 'event_participants_by_events_EventID',
'event_participants_by_events_CandidateID',
'event_participants_by_events_StudentID',
'event_participants_by_events_Event_Start_Date',
'event_participants_by_events_Event_End_Date',
'event_participants_by_events_First_Name',
'event_participants_by_events_Middle_Name',
'event_participants_by_events_Last_Name',
'event_participants_by_events_Sex',
'event_participants_by_events_Phone',
'event_participants_by_events_Email',
'event_participants_by_events_Disability_Status',
'event_participants_by_events_Disability_Type',
'event_participants_by_events_Disability_Type_Other',
'event_participants_by_events_Participant_Type',
'event_participants_by_events_Participant_Field_of_Study',
'event_participants_by_events_Participant_Organization_Type',
'event_participants_by_events_Participant_Organization_Name',
'event_participants_by_events_Participant_Home_Address',
'training_participants_by_trainings_TrainingID',
'training_participants_by_trainings_CandidateID',
'training_participants_by_trainings_StudentID',
'training_participants_by_trainings_Training_Organizer',
'training_participants_by_trainings_Training_Type',
'training_participants_by_trainings_Program_Area',
'training_participants_by_trainings_Training_City_Town',
'training_participants_by_trainings_Training_Venue',
'training_participants_by_trainings_Training_Start_Date',
'training_participants_by_trainings_Training_End_Date',
'training_participants_by_trainings_First_Name',
'training_participants_by_trainings_Middle_Name',
'training_participants_by_trainings_Last_Name',
'training_participants_by_trainings_Sex',
'training_participants_by_trainings_Email',
'training_participants_by_trainings_Phone',
'training_participants_by_trainings_Disability_Status',
'training_participants_by_trainings_Disability_Type',
'training_participants_by_trainings_Disability_Type_Other',
'training_participants_by_trainings_Participant_Profession',
'training_participants_by_trainings_Participant_Field_of_Study',
'training_participants_by_trainings_Participant_Facility_Organization_Type',
'training_participants_by_trainings_Participant_Organization_Name',
'training_participants_by_trainings_Participants_Home_Address',
'training_participants_by_trainings_PreTest_Score',
'training_participants_by_trainings_Skill_Test',
'training_participants_by_trainings_Post_Test_Score',
'candidates_reports_CandidateID',
'candidates_reports_StudentID',
'candidates_reports_First_Name',
'candidates_reports_Middle_Name',
'candidates_reports_Last_Name',
'candidates_reports_Sex',
'candidates_reports_DOB',
'candidates_reports_Region',
'candidates_reports_City',
'candidates_reports_Sub_City',
'candidates_reports_Zone',
'candidates_reports_House_No',
'candidates_reports_Phone_Number',
'candidates_reports_Phone_Number_Alternate',
'candidates_reports_Email_Address',
'candidates_reports_Disability_Status',
'candidates_reports_Disability_Type',
'candidates_reports_Disability_Type_Other',
'candidates_reports_Institution_Type',
'candidates_reports_Institution_Name',
'candidates_reports_Education_Level',
'candidates_reports_Department',
'candidates_reports_Minor',
'candidates_reports_Major',
'candidates_reports_Enrollement_Type',
'candidates_reports_Skills',
'candidates_reports_Languages',
'candidates_reports_English_Proficiency_Level',
'candidates_reports_Industry_Specific_Skills',
'candidates_reports_IT_Related_Skills',
'candidates_reports_Certifications',
'candidates_reports_Year_of_graduation',
'candidates_reports_Field_Of_Study',
'candidates_reports_GPA',
'candidates_reports_Intervention',
'candidates_reports_Campaign',
'candidates_reports_Attend_Employability_Skill',
'candidates_reports_DAAP_enrolled_1st_Round',
'candidates_reports_DAAP_Completed',
'candidates_reports_DAAP_Completed_Courses',
'candidates_reports_Job_Fair_Clinic',
'candidates_reports_Job_Fair',
'candidates_reports_Exit_Exam_Score',
'candidates_reports_Exit_Exam_Status',
'candidates_reports_DAAP_enrolled_2nd_Round',
'candidates_reports_Upload_on_Tracker',
'candidates_reports_Work_Experience',
'candidates_reports_Joined_Dereja_Services',
'candidates_reports_Dereja_Services',
'candidates_reports_Dereja_Training_Services',
'candidates_reports_Dereja_Event_Services',
'candidates_reports_Dereja_web_profile_completion',
'candidates_reports_Dereja_Information_Source',
'candidates_reports_Employment_Status',
'candidates_reports_Employment_Company',
'candidates_reports_Employment_Position',
'candidates_reports_Remark',
'candidates_by_gender_CandidateID',
'candidates_by_gender_StudentID',
'candidates_by_gender_First_Name',
'candidates_by_gender_Middle_Name',
'candidates_by_gender_Last_Name',
'candidates_by_gender_Sex',
'candidates_by_gender_DOB',
'candidates_by_gender_Region',
'candidates_by_gender_City',
'candidates_by_gender_Sub_City',
'candidates_by_gender_Zone',
'candidates_by_gender_House_No',
'candidates_by_gender_Phone_Number',
'candidates_by_gender_Phone_Number_Alternate',
'candidates_by_gender_Email_Address',
'candidates_by_gender_Disability_Status',
'candidates_by_gender_Disability_Type',
'candidates_by_gender_Disability_Type_Other',
'candidates_by_gender_Institution_Type',
'candidates_by_gender_Institution_Name',
'candidates_by_gender_Education_Level',
'candidates_by_gender_Department',
'candidates_by_gender_Minor',
'candidates_by_gender_Major',
'candidates_by_gender_Enrollement_Type',
'candidates_by_gender_Skills',
'candidates_by_gender_Languages',
'candidates_by_gender_English_Proficiency_Level',
'candidates_by_gender_Industry_Specific_Skills',
'candidates_by_gender_IT_Related_Skills',
'candidates_by_gender_Certifications',
'candidates_by_gender_Year_of_graduation',
'candidates_by_gender_Field_Of_Study',
'candidates_by_gender_GPA',
'candidates_by_gender_Intervention',
'candidates_by_gender_Campaign',
'candidates_by_gender_Attend_Employability_Skill',
'candidates_by_gender_DAAP_enrolled_1st_Round',
'candidates_by_gender_DAAP_Completed',
'candidates_by_gender_DAAP_Completed_Courses',
'candidates_by_gender_Job_Fair_Clinic',
'candidates_by_gender_Job_Fair',
'candidates_by_gender_Exit_Exam_Score',
'candidates_by_gender_Exit_Exam_Status',
'candidates_by_gender_DAAP_enrolled_2nd_Round',
'candidates_by_gender_Upload_on_Tracker',
'candidates_by_gender_Work_Experience',
'candidates_by_gender_Joined_Dereja_Services',
'candidates_by_gender_Dereja_Services',
'candidates_by_gender_Dereja_Training_Services',
'candidates_by_gender_Dereja_Event_Services',
'candidates_by_gender_Dereja_web_profile_completion',
'candidates_by_gender_Dereja_Information_Source',
'candidates_by_gender_Employment_Status',
'candidates_by_gender_Employment_Company',
'candidates_by_gender_Employment_Position',
'candidates_by_gender_Remark',
'candidates_by_region_CandidateID',
'candidates_by_region_StudentID',
'candidates_by_region_First_Name',
'candidates_by_region_Middle_Name',
'candidates_by_region_Last_Name',
'candidates_by_region_Sex',
'candidates_by_region_DOB',
'candidates_by_region_Region',
'candidates_by_region_City',
'candidates_by_region_Sub_City',
'candidates_by_region_Zone',
'candidates_by_region_House_No',
'candidates_by_region_Phone_Number',
'candidates_by_region_Phone_Number_Alternate',
'candidates_by_region_Email_Address',
'candidates_by_region_Disability_Status',
'candidates_by_region_Disability_Type',
'candidates_by_region_Disability_Type_Other',
'candidates_by_region_Institution_Type',
'candidates_by_region_Institution_Name',
'candidates_by_region_Education_Level',
'candidates_by_region_Department',
'candidates_by_region_Minor',
'candidates_by_region_Major',
'candidates_by_region_Enrollement_Type',
'candidates_by_region_Skills',
'candidates_by_region_Languages',
'candidates_by_region_English_Proficiency_Level',
'candidates_by_region_Industry_Specific_Skills',
'candidates_by_region_IT_Related_Skills',
'candidates_by_region_Certifications',
'candidates_by_region_Year_of_graduation',
'candidates_by_region_Field_Of_Study',
'candidates_by_region_GPA',
'candidates_by_region_Intervention',
'candidates_by_region_Campaign',
'candidates_by_region_Attend_Employability_Skill',
'candidates_by_region_DAAP_enrolled_1st_Round',
'candidates_by_region_DAAP_Completed',
'candidates_by_region_DAAP_Completed_Courses',
'candidates_by_region_Job_Fair_Clinic',
'candidates_by_region_Job_Fair',
'candidates_by_region_Exit_Exam_Score',
'candidates_by_region_Exit_Exam_Status',
'candidates_by_region_DAAP_enrolled_2nd_Round',
'candidates_by_region_Upload_on_Tracker',
'candidates_by_region_Work_Experience',
'candidates_by_region_Joined_Dereja_Services',
'candidates_by_region_Dereja_Services',
'candidates_by_region_Dereja_Training_Services',
'candidates_by_region_Dereja_Event_Services',
'candidates_by_region_Dereja_web_profile_completion',
'candidates_by_region_Dereja_Information_Source',
'candidates_by_region_Employment_Status',
'candidates_by_region_Employment_Company',
'candidates_by_region_Employment_Position',
'candidates_by_region_Remark',
'candidates_by_sex_age_disability_Sex',
'candidates_by_sex_age_disability_Disabled',
'candidates_by_sex_age_disability_Not_Disabled',
'candidates_by_sex_age_disability_Age_18_and_Above',
'candidates_CandidateID',
'candidates_StudentID',
'candidates_Full_Name',
'candidates_First_Name',
'candidates_Middle_Name',
'candidates_Last_Name',
'candidates_Sex',
'candidates_DOB',
'candidates_Age',
'candidates_Region',
'candidates_City',
'candidates_Sub_City',
'candidates_Zone',
'candidates_House_No',
'candidates_Phone_Number',
'candidates_Phone_Number_Alternate',
'candidates_Email_Address',
'candidates_Disability_Status',
'candidates_Disability_Type',
'candidates_Disability_Type_Other',
'candidates_Institution_Type',
'candidates_Institution_Name',
'candidates_Education_Level',
'candidates_Department',
'candidates_Minor',
'candidates_Major',
'candidates_Enrollement_Type',
'candidates_Skills',
'candidates_Languages',
'candidates_English_Proficiency_Level',
'candidates_Industry_Specific_Skills',
'candidates_IT_Related_Skills',
'candidates_Certifications',
'candidates_Year_of_graduation',
'candidates_Field_Of_Study',
'candidates_GPA',
'candidates_Intervention',
'candidates_Campaign',
'candidates_Attend_Employability_Skill',
'candidates_DAAP_enrolled_1st_Round',
'candidates_DAAP_Completed',
'candidates_DAAP_Completed_Courses',
'candidates_Job_Fair_Clinic',
'candidates_Job_Fair',
'candidates_Exit_Exam_Score',
'candidates_Exit_Exam_Status',
'candidates_DAAP_enrolled_2nd_Round',
'candidates_Upload_on_Tracker',
'candidates_Work_Experience',
'candidates_Joined_Dereja_Services',
'candidates_Dereja_Services',
'candidates_Dereja_Training_Services',
'candidates_Dereja_Event_Services',
'candidates_Dereja_web_profile_completion',
'candidates_Dereja_Information_Source',
'candidates_Employment_Status',
'candidates_Employment_Company',
'candidates_Employment_Position',
'candidates_Remark',
'indicator_targets_IndicatorID',
'indicator_targets_IndicatorName',
'indicator_targets_IndicatorDescription',
'indicator_targets_IndicatorValue',
'indicator_targets_IndicatorTarget' ),
'googleLikeFields' => array(  ) ) );
			$pageArray = array( 'id' => 'Home',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 1,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item7' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'dashboard-item8' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'username_button',
'loginform_register' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c4',
'items' => array(  ),
'align' => 'right' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'DerejaMenuSet' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'event_participants_by_events',
'dashType' => 1,
'dashName' => 'event_participants_by_events_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'calendar' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'training_participants_by_trainings',
'dashType' => 1,
'dashName' => 'training_participants_by_trainings_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'linode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'candidates_reports',
'dashType' => 1,
'dashName' => 'candidates_reports_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'table' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_gender',
'dashType' => 1,
'dashName' => 'candidates_by_gender_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'transgender-alt' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'indicator_targets',
'dashType' => 0,
'dashName' => 'indicator_targets_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'info-circle' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '#FB7409',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_region',
'dashType' => 1,
'dashName' => 'candidates_by_region_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bar-chart' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item7' => array( 'type' => 'dashboard-item',
'table' => 'candidates_by_sex_age_disability',
'dashType' => 1,
'dashName' => 'candidates_by_sex_age_disability_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'users' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item8' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 0,
'dashName' => 'candidates_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => '0',
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'loginform_register' => array( 'type' => 'loginform_register' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>