<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 2 ),
'details' => array( 'kbcomments' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => false,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'ArticleID' => array( 'totalsType' => '' ),
'ArticleID2' => array( 'totalsType' => '' ),
'ArticleIDedit' => array( 'totalsType' => '' ),
'Category' => array( 'totalsType' => '' ),
'DateCreated' => array( 'totalsType' => '' ),
'Problem' => array( 'totalsType' => '' ),
'Solution' => array( 'totalsType' => '' ),
'Title' => array( 'totalsType' => '' ),
'Views' => array( 'totalsType' => '' ),
'helpfullblock' => array( 'totalsType' => '' ),
'likecount' => array( 'totalsType' => '' ),
'dislikecount' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Title',
'Category',
'Problem',
'Views',
'helpfullblock',
'Solution',
'DateCreated' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Title' => array( 'simple_grid_field6' ),
'Category' => array( 'grid_field3',
'grid_field_label1' ),
'Problem' => array( 'grid_field' ),
'Views' => array( 'grid_field1' ),
'helpfullblock' => array( 'grid_field_label',
'grid_field2' ),
'Solution' => array( 'grid_field_label2',
'grid_field4' ),
'DateCreated' => array( 'grid_field_label3',
'grid_field5' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => true,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'category_title',
'text',
'snippet',
'add' ),
'below-grid' => array(  ),
'left' => array( 'menu',
'logo',
'expand_button' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ),
'grid' => array( 'simple_grid_field6',
'grid_field3',
'grid_field',
'grid_field1',
'grid_field_label',
'grid_field2',
'grid_field_label1',
'grid_field_label2',
'grid_field4',
'grid_field_label3',
'grid_field5' ),
'top' => array(  ) ),
'formXtTags' => array( 'below-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'category_title' => 'above-grid',
'text' => 'above-grid',
'snippet' => 'above-grid',
'add' => 'above-grid',
'menu' => 'left',
'logo' => 'left',
'expand_button' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field6' => 'grid',
'grid_field3' => 'grid',
'grid_field' => 'grid',
'grid_field1' => 'grid',
'grid_field_label' => 'grid',
'grid_field2' => 'grid',
'grid_field_label1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field4' => 'grid',
'grid_field_label3' => 'grid',
'grid_field5' => 'grid' ),
'itemLocations' => array( 'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'snippet' => array( 'category_title',
'snippet' ),
'add' => array( 'add' ),
'grid_field' => array( 'simple_grid_field6',
'grid_field3',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field4',
'grid_field5' ),
'grid_field_label' => array( 'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3' ),
'export_selected' => array( 'export_selected' ),
'-' => array( '-1',
'-' ),
'advsearch_link' => array( 'advsearch_link' ),
'export' => array( 'export' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'list_options' => array( 'list_options' ),
'loginform_login' => array( 'loginform_login' ),
'username_button' => array( 'username_button' ),
'logo' => array( 'logo' ),
'text' => array( 'text' ),
'breadcrumb' => array( 'breadcrumb' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array( 'Title_fieldcolumn',
'Category_fieldcolumn' ),
'items' => array( 'simple_grid_field6',
'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array( 'Problem_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array( 'Views_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'helpfullblock_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'helpfullblock_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'Solution_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'Solution_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'Category_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'DateCreated_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'DateCreated_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 9 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 1,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'category',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'category_title',
'text',
'snippet' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'add' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ),
'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'vertical-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 2 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_field',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_field1',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_field2',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field4' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field6' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 2 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6',
'grid_field3' ),
'field' => 'Title',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'Problem',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'Views',
'columnName' => 'field' ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'helpfullblock',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'helpfullblock',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'Category',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'Solution',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'Solution',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label3' ),
'field' => 'DateCreated',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'DateCreated',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'category_title' => array( 'eventId' => 'category_title',
'label' => array( 'text' => 'category_title',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => '/* Put  your custom CSS code here */

:host {
    font-family: "Montserrat",sans-serif;
    color: #1b1b1b;
        font-size: 20px;
}
' ),
'add' => array( 'type' => 'add' ),
'simple_grid_field6' => array( 'field' => 'Title',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host a {
  font-size: 18px;
}
:host a:before{
    margin-right:5px;
}
' ),
'grid_field3' => array( 'field' => 'Category',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field' => array( 'field' => 'Problem',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field1' => array( 'field' => 'Views',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'helpfullblock' ),
'grid_field2' => array( 'field' => 'helpfullblock',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Category' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Solution' ),
'grid_field4' => array( 'field' => 'Solution',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'DateCreated' ),
'grid_field5' => array( 'field' => 'DateCreated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-' => array( 'type' => '-' ),
'export' => array( 'type' => 'export' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'DerejaMenuSet' ),
'simple_search' => array( 'type' => 'simple_search' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'-1',
'advsearch_link',
'-',
'export' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'logo' => array( 'type' => 'logo' ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'How can we help you?',
'type' => 0 ),
'editedByRte' => false,
'customCSS' => ':host {
    font-size: 34px;
    line-height: 40px;
    font-weight: 600;
    color: #ffffff;
    margin-top: 40px;
    margin-bottom: 40px;
}
' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'snippet' => array( 'eventId' => 'category_select',
'label' => array( 'text' => 'category_select',
'type' => 0 ),
'type' => 'snippet' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'standard',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>