<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'First Name',
'Middle Name',
'Last Name',
'Sex',
'Training Organizer',
'Training Type',
'Program Area',
'Region',
'City',
'Participant Profession',
'Participant Field of Study',
'Training City Town',
'Participant Organization Name',
'Participant Home Address',
'Phone Number',
'Email Address',
'Disablity Status',
'Training Venue',
'Training start date',
'Training end date',
'Training Title',
'Zone',
'Sub City',
'Participant Facility or Organization Type',
'Pre-Test Score',
'Skill Test',
'Post-Test Score' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'import_field' ),
'First Name' => array( 'import_field1' ),
'Middle Name' => array( 'import_field2' ),
'Last Name' => array( 'import_field3' ),
'Sex' => array( 'import_field4' ),
'Training Organizer' => array( 'import_field5' ),
'Training Type' => array( 'import_field6' ),
'Program Area' => array( 'import_field7' ),
'Region' => array( 'import_field8' ),
'City' => array( 'import_field9' ),
'Participant Profession' => array( 'import_field10' ),
'Participant Field of Study' => array( 'import_field11' ),
'Training City Town' => array( 'import_field12' ),
'Participant Organization Name' => array( 'import_field13' ),
'Participant Home Address' => array( 'import_field14' ),
'Phone Number' => array( 'import_field15' ),
'Email Address' => array( 'import_field16' ),
'Disablity Status' => array( 'import_field17' ),
'Training Venue' => array( 'import_field18' ),
'Training start date' => array( 'import_field19' ),
'Training end date' => array( 'import_field20' ),
'Training Title' => array( 'import_field21' ),
'Zone' => array( 'import_field22' ),
'Sub City' => array( 'import_field23' ),
'Participant Facility or Organization Type' => array( 'import_field24' ),
'Pre-Test Score' => array( 'import_field25' ),
'Skill Test' => array( 'import_field26' ),
'Post-Test Score' => array( 'import_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field5',
'import_field6',
'import_field7',
'import_field12',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field12' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field5',
'import_field6',
'import_field7',
'import_field12',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'First Name',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Middle Name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Last Name',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Sex',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Training Organizer',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Training Type',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Program Area',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Region',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'City',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Participant Profession',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Participant Field of Study',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Training City Town',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Participant Organization Name',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Participant Home Address',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Phone Number',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Email Address',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Disablity Status',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Training Venue',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Training start date',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Training end date',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Training Title',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Zone',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Sub City',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'Participant Facility or Organization Type',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Pre-Test Score',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Skill Test',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Post-Test Score',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>