<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'TrainingID',
'TrainingTitle',
'Training_Start_Date',
'Training_End_Date',
'TypeName',
'OrganizerName',
'CityTownName',
'VenueName',
'Trainer_FullName',
'TrainingRound',
'TrainingNote',
'program_areas' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TrainingID' => array( 'import_field' ),
'TrainingTitle' => array( 'import_field1' ),
'Training_Start_Date' => array( 'import_field2' ),
'Training_End_Date' => array( 'import_field3' ),
'TypeName' => array( 'import_field4' ),
'OrganizerName' => array( 'import_field5' ),
'CityTownName' => array( 'import_field6' ),
'VenueName' => array( 'import_field7' ),
'Trainer_FullName' => array( 'import_field8' ),
'TrainingRound' => array( 'import_field9' ),
'TrainingNote' => array( 'import_field10' ),
'program_areas' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'TrainingID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'TrainingTitle',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Training_Start_Date',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Training_End_Date',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'TypeName',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'OrganizerName',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'CityTownName',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'VenueName',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Trainer_FullName',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'TrainingRound',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'TrainingNote',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'program_areas',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>