<?php
			$optionsArray = array( 'totals' => array( 'ID' => array( 'totalsType' => '' ),
'First Name' => array( 'totalsType' => '' ),
'Middle Name' => array( 'totalsType' => '' ),
'Last Name' => array( 'totalsType' => '' ),
'Sex' => array( 'totalsType' => '' ),
'Training Organizer' => array( 'totalsType' => '' ),
'Training Type' => array( 'totalsType' => '' ),
'Program Area' => array( 'totalsType' => '' ),
'Training City Town' => array( 'totalsType' => '' ),
'Training Venue' => array( 'totalsType' => '' ),
'Training start date' => array( 'totalsType' => '' ),
'Training end date' => array( 'totalsType' => '' ),
'Training Title' => array( 'totalsType' => '' ),
'Region' => array( 'totalsType' => '' ),
'City' => array( 'totalsType' => '' ),
'Zone' => array( 'totalsType' => '' ),
'Sub City' => array( 'totalsType' => '' ),
'Participant Profession' => array( 'totalsType' => '' ),
'Participant Field of Study' => array( 'totalsType' => '' ),
'Participant Facility or Organization Type' => array( 'totalsType' => '' ),
'Participant Organization Name' => array( 'totalsType' => '' ),
'Participant Home Address' => array( 'totalsType' => '' ),
'Phone Number' => array( 'totalsType' => '' ),
'Email Address' => array( 'totalsType' => '' ),
'Disablity Status' => array( 'totalsType' => '' ),
'Pre-Test Score' => array( 'totalsType' => '' ),
'Skill Test' => array( 'totalsType' => '' ),
'Post-Test Score' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ID',
'First Name',
'Middle Name',
'Last Name',
'Sex',
'Training Organizer',
'Training Type',
'Program Area',
'Region',
'City',
'Participant Profession',
'Participant Field of Study',
'Training City Town',
'Participant Organization Name',
'Participant Home Address',
'Phone Number',
'Email Address',
'Disablity Status',
'Training Venue',
'Training start date',
'Training end date',
'Training Title',
'Zone',
'Sub City',
'Participant Facility or Organization Type',
'Pre-Test Score',
'Skill Test',
'Post-Test Score' ),
'exportFields' => array( 'ID',
'First Name',
'Middle Name',
'Last Name',
'Sex',
'Region',
'City',
'Participant Profession',
'Participant Field of Study',
'Participant Organization Name',
'Participant Home Address',
'Phone Number',
'Email Address',
'Disablity Status',
'Training Organizer',
'Training Type',
'Program Area',
'Training City Town',
'Training Venue',
'Training start date',
'Training end date',
'Training Title',
'Zone',
'Sub City',
'Participant Facility or Organization Type',
'Pre-Test Score',
'Skill Test',
'Post-Test Score' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'export_field' ),
'First Name' => array( 'export_field1' ),
'Middle Name' => array( 'export_field2' ),
'Last Name' => array( 'export_field3' ),
'Sex' => array( 'export_field4' ),
'Training Organizer' => array( 'export_field5' ),
'Training Type' => array( 'export_field6' ),
'Program Area' => array( 'export_field7' ),
'Region' => array( 'export_field8' ),
'City' => array( 'export_field9' ),
'Participant Profession' => array( 'export_field10' ),
'Participant Field of Study' => array( 'export_field11' ),
'Training City Town' => array( 'export_field12' ),
'Participant Organization Name' => array( 'export_field13' ),
'Participant Home Address' => array( 'export_field14' ),
'Phone Number' => array( 'export_field15' ),
'Email Address' => array( 'export_field16' ),
'Disablity Status' => array( 'export_field17' ),
'Training Venue' => array( 'export_field18' ),
'Training start date' => array( 'export_field19' ),
'Training end date' => array( 'export_field20' ),
'Training Title' => array( 'export_field21' ),
'Zone' => array( 'export_field22' ),
'Sub City' => array( 'export_field23' ),
'Participant Facility or Organization Type' => array( 'export_field24' ),
'Pre-Test Score' => array( 'export_field25' ),
'Skill Test' => array( 'export_field26' ),
'Post-Test Score' => array( 'export_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field5',
'export_field6',
'export_field7',
'export_field12',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field12' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field5',
'export_field6',
'export_field7',
'export_field12',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'First Name',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Middle Name',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Last Name',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Sex',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Training Organizer',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Training Type',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Program Area',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Region',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'City',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Participant Profession',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Participant Field of Study',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Training City Town',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Participant Organization Name',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Participant Home Address',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Phone Number',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Email Address',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Disablity Status',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Training Venue',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Training start date',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Training end date',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Training Title',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Zone',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Sub City',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Participant Facility or Organization Type',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Pre-Test Score',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Skill Test',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Post-Test Score',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>