<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'master' => array( 'candidates' => array( 'preview' => true ),
'trainings' => array( 'preview' => true ) ),
'fields' => array( 'gridFields' => array( 'TrainingID',
'CandidateID',
'Sex',
'StudentID',
'Training_Organizer',
'Training_Type',
'Program_Area',
'Training_City_Town',
'Training_Venue',
'Training_Start_Date',
'Training_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Email',
'Phone',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Profession',
'Participant_Field_of_Study',
'Participant_Facility_Organization_Type',
'Participant_Organization_Name',
'Participants_Home_Address',
'PreTest_Score',
'Skill_Test',
'Post_Test_Score' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TrainingID' => array( 'report_grid_field',
'report_group_field' ),
'CandidateID' => array( 'report_grid_field1' ),
'Sex' => array( 'report_grid_field2',
'report_group_field1' ),
'StudentID' => array( 'report_grid_field3' ),
'Training_Organizer' => array( 'report_grid_field4' ),
'Training_Type' => array( 'report_grid_field5',
'report_group_field3' ),
'Program_Area' => array( 'report_grid_field6',
'report_group_field4' ),
'Training_City_Town' => array( 'report_grid_field7' ),
'Training_Venue' => array( 'report_grid_field8' ),
'Training_Start_Date' => array( 'report_grid_field9' ),
'Training_End_Date' => array( 'report_grid_field10' ),
'First_Name' => array( 'report_grid_field11' ),
'Middle_Name' => array( 'report_grid_field12' ),
'Last_Name' => array( 'report_grid_field13' ),
'Email' => array( 'report_grid_field14' ),
'Phone' => array( 'report_grid_field15' ),
'Disability_Status' => array( 'report_grid_field16',
'report_group_field2' ),
'Disability_Type' => array( 'report_grid_field17' ),
'Disability_Type_Other' => array( 'report_grid_field18' ),
'Participant_Profession' => array( 'report_grid_field19' ),
'Participant_Field_of_Study' => array( 'report_grid_field20' ),
'Participant_Facility_Organization_Type' => array( 'report_grid_field21' ),
'Participant_Organization_Name' => array( 'report_grid_field22' ),
'Participants_Home_Address' => array( 'report_grid_field23' ),
'PreTest_Score' => array( 'report_grid_field24',
'report_group_field5' ),
'Skill_Test' => array( 'report_grid_field25' ),
'Post_Test_Score' => array( 'report_grid_field26',
'report_group_field6' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'master_info',
'print_pdf' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6',
'report_grid_field1',
'report_grid_field',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pdf' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_group_field5' => 'grid',
'report_group_field6' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field4' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field10' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field12' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field14' => 'grid',
'report_grid_field15' => 'grid',
'report_grid_field16' => 'grid',
'report_grid_field17' => 'grid',
'report_grid_field18' => 'grid',
'report_grid_field19' => 'grid',
'report_grid_field20' => 'grid',
'report_grid_field21' => 'grid',
'report_grid_field22' => 'grid',
'report_grid_field23' => 'grid',
'report_grid_field24' => 'grid',
'report_grid_field25' => 'grid',
'report_grid_field26' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field',
'report_grid_field1',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26' ),
'master_info' => array( 'master_info' ),
'print_pdf' => array( 'print_pdf' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => false,
'field' => 'TrainingID',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Sex',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Disability_Status',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Training_Type',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Program_Area',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'PreTest_Score',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Post_Test_Score',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'TrainingID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Organizer',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Program_Area',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_City_Town',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Venue',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Start_Date',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_End_Date',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Profession',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Field_of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Facility_Organization_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Organization_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participants_Home_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'PreTest_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skill_Test',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Post_Test_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'plain',
'vertSummary' => true ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_group_field5',
'report_group_field6' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field1',
'report_grid_field',
'report_grid_field2',
'report_grid_field3',
'report_grid_field4',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field10',
'report_grid_field11',
'report_grid_field12',
'report_grid_field13',
'report_grid_field14',
'report_grid_field15',
'report_grid_field16',
'report_grid_field17',
'report_grid_field18',
'report_grid_field19',
'report_grid_field20',
'report_grid_field21',
'report_grid_field22',
'report_grid_field23',
'report_grid_field24',
'report_grid_field25',
'report_grid_field26' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => false,
'field' => 'TrainingID',
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Sex',
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Disability_Status',
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Training_Type',
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Program_Area',
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'PreTest_Score',
'color' => array( 'header' => '96bec4',
'summary' => 'b0e0e6' ),
'axis' => 2 ),
array( 'interval' => 0,
'summary' => false,
'field' => 'Post_Test_Score',
'color' => array( 'header' => 'd56d61',
'summary' => 'fa8072' ),
'axis' => 2 ) ),
'fields' => array( array( 'avg' => true,
'field' => 'CandidateID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'TrainingID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Sex',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'StudentID',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Organizer',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Program_Area',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_City_Town',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Venue',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_Start_Date',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Training_End_Date',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'First_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Middle_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Last_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Email',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Phone',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Status',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Disability_Type_Other',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Profession',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Field_of_Study',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Facility_Organization_Type',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participant_Organization_Name',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Participants_Home_Address',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'PreTest_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Skill_Test',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ),
array( 'avg' => true,
'field' => 'Post_Test_Score',
'grid' => true,
'max' => true,
'min' => true,
'sum' => true ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => true,
'colors' => array(  ),
'horizSummary' => true,
'layout' => 'plain',
'vertSummary' => true ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field' => array( 'field' => 'TrainingID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field1' => array( 'field' => 'CandidateID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field2' => array( 'field' => 'Sex',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field3' => array( 'field' => 'StudentID',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field4' => array( 'field' => 'Training_Organizer',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field5' => array( 'field' => 'Training_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field6' => array( 'field' => 'Program_Area',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field7' => array( 'field' => 'Training_City_Town',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field8' => array( 'field' => 'Training_Venue',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field9' => array( 'field' => 'Training_Start_Date',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field10' => array( 'field' => 'Training_End_Date',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field11' => array( 'field' => 'First_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field12' => array( 'field' => 'Middle_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field13' => array( 'field' => 'Last_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field14' => array( 'field' => 'Email',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field15' => array( 'field' => 'Phone',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field16' => array( 'field' => 'Disability_Status',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field17' => array( 'field' => 'Disability_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field18' => array( 'field' => 'Disability_Type_Other',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field19' => array( 'field' => 'Participant_Profession',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field20' => array( 'field' => 'Participant_Field_of_Study',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field21' => array( 'field' => 'Participant_Facility_Organization_Type',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field22' => array( 'field' => 'Participant_Organization_Name',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field23' => array( 'field' => 'Participants_Home_Address',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field24' => array( 'field' => 'PreTest_Score',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field25' => array( 'field' => 'Skill_Test',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'report_grid_field26' => array( 'field' => 'Post_Test_Score',
'type' => 'report_grid_field',
'reportAvg' => true,
'reportMin' => true,
'reportMax' => true,
'reportSum' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'candidates' => 'true',
'trainings' => 'true' ) ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'report_group_field' => array( 'field' => 'TrainingID',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'Sex',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'Disability_Status',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'Training_Type',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field4' => array( 'field' => 'Program_Area',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field5' => array( 'field' => 'PreTest_Score',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ),
'report_group_field6' => array( 'field' => 'Post_Test_Score',
'type' => 'report_group_field',
'summary' => false,
'axis' => 2,
'interval' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>