<?php
			$optionsArray = array( 'totals' => array( 'TrainingID' => array( 'totalsType' => '' ),
'CandidateID' => array( 'totalsType' => '' ),
'StudentID' => array( 'totalsType' => '' ),
'Training_Organizer' => array( 'totalsType' => '' ),
'Training_Type' => array( 'totalsType' => '' ),
'Program_Area' => array( 'totalsType' => '' ),
'Training_City_Town' => array( 'totalsType' => '' ),
'Training_Venue' => array( 'totalsType' => '' ),
'Training_Start_Date' => array( 'totalsType' => '' ),
'Training_End_Date' => array( 'totalsType' => '' ),
'First_Name' => array( 'totalsType' => '' ),
'Middle_Name' => array( 'totalsType' => '' ),
'Last_Name' => array( 'totalsType' => '' ),
'Full_Name' => array( 'totalsType' => '' ),
'Sex' => array( 'totalsType' => '' ),
'Email' => array( 'totalsType' => '' ),
'Phone' => array( 'totalsType' => '' ),
'Disability_Status' => array( 'totalsType' => '' ),
'Disability_Type' => array( 'totalsType' => '' ),
'Disability_Type_Other' => array( 'totalsType' => '' ),
'Participant_Profession' => array( 'totalsType' => '' ),
'Participant_Field_of_Study' => array( 'totalsType' => '' ),
'Participant_Facility_Organization_Type' => array( 'totalsType' => '' ),
'Participant_Organization_Name' => array( 'totalsType' => '' ),
'Participants_Home_Address' => array( 'totalsType' => '' ),
'PreTest_Score' => array( 'totalsType' => '' ),
'Skill_Test' => array( 'totalsType' => '' ),
'Post_Test_Score' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'TrainingID',
'CandidateID',
'Training_Organizer',
'Training_Type',
'Program_Area',
'Training_City_Town',
'Training_Venue',
'Training_Start_Date',
'Training_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Email',
'Phone',
'StudentID',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Profession',
'Participant_Field_of_Study',
'Participant_Facility_Organization_Type',
'Participant_Organization_Name',
'Participants_Home_Address',
'PreTest_Score',
'Skill_Test',
'Post_Test_Score',
'Sex',
'Full_Name' ),
'exportFields' => array( 'TrainingID',
'CandidateID',
'Training_Organizer',
'Training_Type',
'Program_Area',
'Training_City_Town',
'Training_Venue',
'Training_Start_Date',
'Training_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Email',
'Phone',
'StudentID',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Profession',
'Participant_Field_of_Study',
'Participant_Facility_Organization_Type',
'Participant_Organization_Name',
'Participants_Home_Address',
'PreTest_Score',
'Skill_Test',
'Post_Test_Score',
'Sex',
'Full_Name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TrainingID' => array( 'export_field' ),
'CandidateID' => array( 'export_field1' ),
'Training_Organizer' => array( 'export_field2' ),
'Training_Type' => array( 'export_field3' ),
'Program_Area' => array( 'export_field4' ),
'Training_City_Town' => array( 'export_field5' ),
'Training_Venue' => array( 'export_field6' ),
'Training_Start_Date' => array( 'export_field7' ),
'Training_End_Date' => array( 'export_field8' ),
'First_Name' => array( 'export_field9' ),
'Middle_Name' => array( 'export_field10' ),
'Last_Name' => array( 'export_field11' ),
'Email' => array( 'export_field12' ),
'Phone' => array( 'export_field13' ),
'StudentID' => array( 'export_field14' ),
'Disability_Status' => array( 'export_field15' ),
'Disability_Type' => array( 'export_field16' ),
'Disability_Type_Other' => array( 'export_field17' ),
'Participant_Profession' => array( 'export_field18' ),
'Participant_Field_of_Study' => array( 'export_field19' ),
'Participant_Facility_Organization_Type' => array( 'export_field20' ),
'Participant_Organization_Name' => array( 'export_field21' ),
'Participants_Home_Address' => array( 'export_field22' ),
'PreTest_Score' => array( 'export_field23' ),
'Skill_Test' => array( 'export_field24' ),
'Post_Test_Score' => array( 'export_field25' ),
'Sex' => array( 'export_field26' ),
'Full_Name' => array( 'export_field27' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'TrainingID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CandidateID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Training_Organizer',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Training_Type',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Program_Area',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Training_City_Town',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Training_Venue',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Training_Start_Date',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Training_End_Date',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'First_Name',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Middle_Name',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Last_Name',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Email',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Phone',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'StudentID',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Disability_Status',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Disability_Type',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Disability_Type_Other',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Participant_Profession',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Participant_Field_of_Study',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Participant_Facility_Organization_Type',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Participant_Organization_Name',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Participants_Home_Address',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'PreTest_Score',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Skill_Test',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Post_Test_Score',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Sex',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Full_Name',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>