<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'TrainingID',
'StudentID',
'Training_Organizer',
'Training_Type',
'Program_Area',
'Training_City_Town',
'Training_Venue',
'Training_Start_Date',
'Training_End_Date',
'First_Name',
'Middle_Name',
'Last_Name',
'Sex',
'Email',
'Phone',
'Disability_Status',
'Disability_Type',
'Disability_Type_Other',
'Participant_Profession',
'Participant_Field_of_Study',
'Participant_Facility_Organization_Type',
'Participant_Organization_Name',
'Participants_Home_Address',
'PreTest_Score',
'Skill_Test',
'Post_Test_Score',
'Training_Round',
'CandidateID',
'Date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TrainingID' => array( 'import_field' ),
'CandidateID' => array( 'import_field1' ),
'StudentID' => array( 'import_field2' ),
'Training_Organizer' => array( 'import_field3' ),
'Training_Type' => array( 'import_field4' ),
'Program_Area' => array( 'import_field5' ),
'Training_City_Town' => array( 'import_field6' ),
'Training_Venue' => array( 'import_field7' ),
'Training_Start_Date' => array( 'import_field8' ),
'Training_End_Date' => array( 'import_field9' ),
'First_Name' => array( 'import_field10' ),
'Middle_Name' => array( 'import_field11' ),
'Last_Name' => array( 'import_field12' ),
'Sex' => array( 'import_field13' ),
'Email' => array( 'import_field14' ),
'Phone' => array( 'import_field15' ),
'Disability_Status' => array( 'import_field16' ),
'Disability_Type' => array( 'import_field17' ),
'Disability_Type_Other' => array( 'import_field18' ),
'Participant_Profession' => array( 'import_field19' ),
'Participant_Field_of_Study' => array( 'import_field20' ),
'Participant_Facility_Organization_Type' => array( 'import_field21' ),
'Participant_Organization_Name' => array( 'import_field22' ),
'Participants_Home_Address' => array( 'import_field23' ),
'PreTest_Score' => array( 'import_field24' ),
'Skill_Test' => array( 'import_field25' ),
'Post_Test_Score' => array( 'import_field26' ),
'Training_Round' => array( 'import_field27' ),
'Date' => array( 'import_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field1',
'import_field28' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field1' => 'grid',
'import_field28' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field1',
'import_field28' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'TrainingID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CandidateID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'StudentID',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Training_Organizer',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Training_Type',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Program_Area',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Training_City_Town',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Training_Venue',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Training_Start_Date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Training_End_Date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'First_Name',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Middle_Name',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Last_Name',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Sex',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Email',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Phone',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Disability_Status',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Disability_Type',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Disability_Type_Other',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Participant_Profession',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Participant_Field_of_Study',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Participant_Facility_Organization_Type',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Participant_Organization_Name',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Participants_Home_Address',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'PreTest_Score',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Skill_Test',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Post_Test_Score',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Training_Round',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Date',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>