<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'TrainingID',
'Training_Organizer',
'Training_Type',
'Training_Venue',
'Training_Start_Date',
'Training_End_Date',
'Sex',
'CandidateID',
'Full_Name',
'DOB',
'Region',
'City',
'Phone_Number',
'Email_Address',
'TrainingTitle',
'Training_City',
'Trainer_Name',
'TrainingRound',
'TrainingNote',
'program_areas' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TrainingID' => array( 'import_field' ),
'CandidateID' => array( 'import_field1' ),
'Full_Name' => array( 'import_field2' ),
'Training_Organizer' => array( 'import_field3' ),
'Training_Type' => array( 'import_field4' ),
'DOB' => array( 'import_field5' ),
'Region' => array( 'import_field6' ),
'Training_Venue' => array( 'import_field7' ),
'Training_Start_Date' => array( 'import_field8' ),
'Training_End_Date' => array( 'import_field9' ),
'City' => array( 'import_field10' ),
'Phone_Number' => array( 'import_field11' ),
'Email_Address' => array( 'import_field12' ),
'Sex' => array( 'import_field13' ),
'TrainingTitle' => array( 'import_field14' ),
'Training_City' => array( 'import_field15' ),
'Trainer_Name' => array( 'import_field16' ),
'TrainingRound' => array( 'import_field17' ),
'TrainingNote' => array( 'import_field18' ),
'program_areas' => array( 'import_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field3',
'import_field4',
'import_field7',
'import_field8',
'import_field9',
'import_field13',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field10',
'import_field11',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field13' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field3',
'import_field4',
'import_field7',
'import_field8',
'import_field9',
'import_field13',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field10',
'import_field11',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'TrainingID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CandidateID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Full_Name',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Training_Organizer',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Training_Type',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'DOB',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Region',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Training_Venue',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Training_Start_Date',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Training_End_Date',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'City',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Phone_Number',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Email_Address',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Sex',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'TrainingTitle',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Training_City',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Trainer_Name',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'TrainingRound',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'TrainingNote',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'program_areas',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>