<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item4',
'dashboard-item3',
'dashboard-item2',
'dashboard-item5' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'notifications',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item5' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'notifications' => array( 'notifications' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 0,
'dashName' => 'candidates_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'star-o' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'candidates_grid',
'table' => 'candidates',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'event_participants',
'dashType' => 0,
'dashName' => 'event_participants_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'event_participants_grid',
'table' => 'event_participants',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'training_participants',
'dashType' => 0,
'dashName' => 'training_participants_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'flash' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'training_participants_grid',
'table' => 'training_participants',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'Candidate_Employment_Tracker',
'dashType' => 0,
'dashName' => 'Candidate_Employment_Tracker_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'book' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'Candidate_Employment_Tracker_grid',
'table' => 'Candidate_Employment_Tracker',
'type' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'regions',
'dashType' => 6,
'dashName' => 'regions_map',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => true,
'detailsMasterTable' => 'candidates',
'mapLatField' => 'Lat',
'mapLonField' => 'Lng',
'mapMarkerIcon' => '' ),
'elementName' => 'regions_map',
'table' => 'regions',
'type' => 6,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'latF' => 'Lat',
'lonF' => 'Lng',
'iconF' => '',
'updateMoved' => true,
'masterTable' => 'candidates',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 3,
'dashName' => 'candidates_record',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'elementName' => 'candidates_record',
'table' => 'candidates',
'type' => 3,
'tabsPageTypes' => array( 'view',
'edit',
'add' ),
'pageNames' => array( 'view' => '',
'edit' => '',
'add' => '' ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'candidates_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'candidates' ) ),
'candidates_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'candidates' ) ),
'candidates_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'candidates' ) ),
'candidates_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'candidates' ) ),
'candidates_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'candidates' ) ),
'candidates_Full_Name' => array( array( 'field' => 'Full_Name',
'table' => 'candidates' ) ),
'candidates_Sex' => array( array( 'field' => 'Sex',
'table' => 'candidates' ) ),
'candidates_DOB' => array( array( 'field' => 'DOB',
'table' => 'candidates' ) ),
'candidates_Region' => array( array( 'field' => 'Region',
'table' => 'candidates' ) ),
'candidates_City' => array( array( 'field' => 'City',
'table' => 'candidates' ) ),
'candidates_Sub_City' => array( array( 'field' => 'Sub_City',
'table' => 'candidates' ) ),
'candidates_Zone' => array( array( 'field' => 'Zone',
'table' => 'candidates' ) ),
'candidates_House_No' => array( array( 'field' => 'House_No',
'table' => 'candidates' ) ),
'candidates_Phone_Number' => array( array( 'field' => 'Phone_Number',
'table' => 'candidates' ) ),
'candidates_Phone_Number_Alternate' => array( array( 'field' => 'Phone_Number_Alternate',
'table' => 'candidates' ) ),
'candidates_Email_Address' => array( array( 'field' => 'Email_Address',
'table' => 'candidates' ) ),
'candidates_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'candidates' ) ),
'candidates_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'candidates' ) ),
'candidates_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'candidates' ) ),
'candidates_Institution_Type' => array( array( 'field' => 'Institution_Type',
'table' => 'candidates' ) ),
'candidates_Institution_Name' => array( array( 'field' => 'Institution_Name',
'table' => 'candidates' ) ),
'candidates_Education_Level' => array( array( 'field' => 'Education_Level',
'table' => 'candidates' ) ),
'candidates_Department' => array( array( 'field' => 'Department',
'table' => 'candidates' ) ),
'candidates_Minor' => array( array( 'field' => 'Minor',
'table' => 'candidates' ) ),
'candidates_Major' => array( array( 'field' => 'Major',
'table' => 'candidates' ) ),
'candidates_Enrollement_Type' => array( array( 'field' => 'Enrollement_Type',
'table' => 'candidates' ) ),
'candidates_Skills' => array( array( 'field' => 'Skills',
'table' => 'candidates' ) ),
'candidates_Languages' => array( array( 'field' => 'Languages',
'table' => 'candidates' ) ),
'candidates_English_Proficiency_Level' => array( array( 'field' => 'English_Proficiency_Level',
'table' => 'candidates' ) ),
'candidates_Industry_Specific_Skills' => array( array( 'field' => 'Industry_Specific_Skills',
'table' => 'candidates' ) ),
'candidates_IT_Related_Skills' => array( array( 'field' => 'IT_Related_Skills',
'table' => 'candidates' ) ),
'candidates_Certifications' => array( array( 'field' => 'Certifications',
'table' => 'candidates' ) ),
'candidates_Year_of_graduation' => array( array( 'field' => 'Year_of_graduation',
'table' => 'candidates' ) ),
'candidates_Field_Of_Study' => array( array( 'field' => 'Field_Of_Study',
'table' => 'candidates' ) ),
'candidates_GPA' => array( array( 'field' => 'GPA',
'table' => 'candidates' ) ),
'candidates_Intervention' => array( array( 'field' => 'Intervention',
'table' => 'candidates' ) ),
'candidates_Campaign' => array( array( 'field' => 'Campaign',
'table' => 'candidates' ) ),
'candidates_Attend_Employability_Skill' => array( array( 'field' => 'Attend_Employability_Skill',
'table' => 'candidates' ) ),
'candidates_DAAP_enrolled_1st_Round' => array( array( 'field' => 'DAAP_enrolled_1st Round',
'table' => 'candidates' ) ),
'candidates_DAAP_Completed' => array( array( 'field' => 'DAAP_Completed',
'table' => 'candidates' ) ),
'candidates_DAAP_Completed_Courses' => array( array( 'field' => 'DAAP_Completed_Courses',
'table' => 'candidates' ) ),
'candidates_Job_Fair_Clinic' => array( array( 'field' => 'Job_Fair_Clinic',
'table' => 'candidates' ) ),
'candidates_Job_Fair' => array( array( 'field' => 'Job_Fair',
'table' => 'candidates' ) ),
'candidates_Exit_Exam_Score' => array( array( 'field' => 'Exit_Exam_Score',
'table' => 'candidates' ) ),
'candidates_Exit_Exam_Status' => array( array( 'field' => 'Exit_Exam_Status',
'table' => 'candidates' ) ),
'candidates_DAAP_enrolled_2nd_Round' => array( array( 'field' => 'DAAP_enrolled_2nd_Round',
'table' => 'candidates' ) ),
'candidates_Upload_on_Tracker' => array( array( 'field' => 'Upload_on_Tracker',
'table' => 'candidates' ) ),
'candidates_Work_Experience' => array( array( 'field' => 'Work_Experience',
'table' => 'candidates' ) ),
'candidates_Joined_Dereja_Services' => array( array( 'field' => 'Joined_Dereja_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Services' => array( array( 'field' => 'Dereja_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Training_Services' => array( array( 'field' => 'Dereja_Training_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_Event_Services' => array( array( 'field' => 'Dereja_Event_Services',
'table' => 'candidates' ) ),
'candidates_Dereja_web_profile_completion' => array( array( 'field' => 'Dereja_web_profile_completion',
'table' => 'candidates' ) ),
'candidates_Dereja_Information_Source' => array( array( 'field' => 'Dereja_Information_Source',
'table' => 'candidates' ) ),
'candidates_Employment_Status' => array( array( 'field' => 'Employment_Status',
'table' => 'candidates' ) ),
'candidates_Employment_Company' => array( array( 'field' => 'Employment_Company',
'table' => 'candidates' ) ),
'candidates_Employment_Position' => array( array( 'field' => 'Employment_Position',
'table' => 'candidates' ) ),
'candidates_Remark' => array( array( 'field' => 'Remark',
'table' => 'candidates' ) ),
'event_participants_EventID' => array( array( 'field' => 'EventID',
'table' => 'event_participants' ) ),
'event_participants_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'event_participants' ) ),
'event_participants_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'event_participants' ) ),
'event_participants_Event_Start_Date' => array( array( 'field' => 'Event_Start_Date',
'table' => 'event_participants' ) ),
'event_participants_Event_End_Date' => array( array( 'field' => 'Event_End_Date',
'table' => 'event_participants' ) ),
'event_participants_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'event_participants' ) ),
'event_participants_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'event_participants' ) ),
'event_participants_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'event_participants' ) ),
'event_participants_Full_Name' => array( array( 'field' => 'Full_Name',
'table' => 'event_participants' ) ),
'event_participants_Sex' => array( array( 'field' => 'Sex',
'table' => 'event_participants' ) ),
'event_participants_Phone' => array( array( 'field' => 'Phone',
'table' => 'event_participants' ) ),
'event_participants_Email' => array( array( 'field' => 'Email',
'table' => 'event_participants' ) ),
'event_participants_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'event_participants' ) ),
'event_participants_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'event_participants' ) ),
'event_participants_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'event_participants' ) ),
'event_participants_Participant_Type' => array( array( 'field' => 'Participant_Type',
'table' => 'event_participants' ) ),
'event_participants_Participant_Field_of_Study' => array( array( 'field' => 'Participant_Field_of_Study',
'table' => 'event_participants' ) ),
'event_participants_Participant_Organization_Type' => array( array( 'field' => 'Participant_Organization_Type',
'table' => 'event_participants' ) ),
'event_participants_Participant_Organization_Name' => array( array( 'field' => 'Participant_Organization_Name',
'table' => 'event_participants' ) ),
'event_participants_Participant_Home_Address' => array( array( 'field' => 'Participant_Home_Address',
'table' => 'event_participants' ) ),
'training_participants_TrainingID' => array( array( 'field' => 'TrainingID',
'table' => 'training_participants' ) ),
'training_participants_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'training_participants' ) ),
'training_participants_StudentID' => array( array( 'field' => 'StudentID',
'table' => 'training_participants' ) ),
'training_participants_Training_Organizer' => array( array( 'field' => 'Training_Organizer',
'table' => 'training_participants' ) ),
'training_participants_Training_Type' => array( array( 'field' => 'Training_Type',
'table' => 'training_participants' ) ),
'training_participants_Program_Area' => array( array( 'field' => 'Program_Area',
'table' => 'training_participants' ) ),
'training_participants_Training_City_Town' => array( array( 'field' => 'Training_City_Town',
'table' => 'training_participants' ) ),
'training_participants_Training_Venue' => array( array( 'field' => 'Training_Venue',
'table' => 'training_participants' ) ),
'training_participants_Training_Start_Date' => array( array( 'field' => 'Training_Start_Date',
'table' => 'training_participants' ) ),
'training_participants_Training_End_Date' => array( array( 'field' => 'Training_End_Date',
'table' => 'training_participants' ) ),
'training_participants_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'training_participants' ) ),
'training_participants_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'training_participants' ) ),
'training_participants_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'training_participants' ) ),
'training_participants_Full_Name' => array( array( 'field' => 'Full_Name',
'table' => 'training_participants' ) ),
'training_participants_Sex' => array( array( 'field' => 'Sex',
'table' => 'training_participants' ) ),
'training_participants_Email' => array( array( 'field' => 'Email',
'table' => 'training_participants' ) ),
'training_participants_Phone' => array( array( 'field' => 'Phone',
'table' => 'training_participants' ) ),
'training_participants_Disability_Status' => array( array( 'field' => 'Disability_Status',
'table' => 'training_participants' ) ),
'training_participants_Disability_Type' => array( array( 'field' => 'Disability_Type',
'table' => 'training_participants' ) ),
'training_participants_Disability_Type_Other' => array( array( 'field' => 'Disability_Type_Other',
'table' => 'training_participants' ) ),
'training_participants_Participant_Profession' => array( array( 'field' => 'Participant_Profession',
'table' => 'training_participants' ) ),
'training_participants_Participant_Field_of_Study' => array( array( 'field' => 'Participant_Field_of_Study',
'table' => 'training_participants' ) ),
'training_participants_Participant_Facility_Organization_Type' => array( array( 'field' => 'Participant_Facility_Organization_Type',
'table' => 'training_participants' ) ),
'training_participants_Participant_Organization_Name' => array( array( 'field' => 'Participant_Organization_Name',
'table' => 'training_participants' ) ),
'training_participants_Participants_Home_Address' => array( array( 'field' => 'Participants_Home_Address',
'table' => 'training_participants' ) ),
'training_participants_PreTest_Score' => array( array( 'field' => 'PreTest_Score',
'table' => 'training_participants' ) ),
'training_participants_Skill_Test' => array( array( 'field' => 'Skill_Test',
'table' => 'training_participants' ) ),
'training_participants_Post_Test_Score' => array( array( 'field' => 'Post_Test_Score',
'table' => 'training_participants' ) ),
'regions_RegionID' => array( array( 'field' => 'RegionID',
'table' => 'regions' ) ),
'regions_RegionName' => array( array( 'field' => 'RegionName',
'table' => 'regions' ) ),
'regions_Lat' => array( array( 'field' => 'Lat',
'table' => 'regions' ) ),
'regions_Lng' => array( array( 'field' => 'Lng',
'table' => 'regions' ) ),
'Candidate_Employment_Tracker_CandidateID' => array( array( 'field' => 'CandidateID',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_JobID' => array( array( 'field' => 'JobID',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Referral_from_Dereja_service' => array( array( 'field' => 'Referral_from_Dereja_service',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Company_Name' => array( array( 'field' => 'Company_Name',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Company_Phone_Number' => array( array( 'field' => 'Company_Phone_Number',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Sector' => array( array( 'field' => 'Sector',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Job_Position' => array( array( 'field' => 'Job_Position',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Job_Type' => array( array( 'field' => 'Job_Type',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Job_Placement_Date' => array( array( 'field' => 'Job_Placement_Date',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Employment_End_Date' => array( array( 'field' => 'Employment_End_Date',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_First_Name' => array( array( 'field' => 'First_Name',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Middle_Name' => array( array( 'field' => 'Middle_Name',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Last_Name' => array( array( 'field' => 'Last_Name',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_Full_Name' => array( array( 'field' => 'Full_Name',
'table' => 'Candidate_Employment_Tracker' ) ),
'Candidate_Employment_Tracker_CurrentEmploymentStatus' => array( array( 'field' => 'CurrentEmploymentStatus',
'table' => 'Candidate_Employment_Tracker' ) ) ),
'allSearchFields' => array( 'candidates_CandidateID',
'candidates_StudentID',
'candidates_First_Name',
'candidates_Middle_Name',
'candidates_Last_Name',
'candidates_Full_Name',
'candidates_Sex',
'candidates_DOB',
'candidates_Region',
'candidates_City',
'candidates_Sub_City',
'candidates_Zone',
'candidates_House_No',
'candidates_Phone_Number',
'candidates_Phone_Number_Alternate',
'candidates_Email_Address',
'candidates_Disability_Status',
'candidates_Disability_Type',
'candidates_Disability_Type_Other',
'candidates_Institution_Type',
'candidates_Institution_Name',
'candidates_Education_Level',
'candidates_Department',
'candidates_Minor',
'candidates_Major',
'candidates_Enrollement_Type',
'candidates_Skills',
'candidates_Languages',
'candidates_English_Proficiency_Level',
'candidates_Industry_Specific_Skills',
'candidates_IT_Related_Skills',
'candidates_Certifications',
'candidates_Year_of_graduation',
'candidates_Field_Of_Study',
'candidates_GPA',
'candidates_Intervention',
'candidates_Campaign',
'candidates_Attend_Employability_Skill',
'candidates_DAAP_enrolled_1st_Round',
'candidates_DAAP_Completed',
'candidates_DAAP_Completed_Courses',
'candidates_Job_Fair_Clinic',
'candidates_Job_Fair',
'candidates_Exit_Exam_Score',
'candidates_Exit_Exam_Status',
'candidates_DAAP_enrolled_2nd_Round',
'candidates_Upload_on_Tracker',
'candidates_Work_Experience',
'candidates_Joined_Dereja_Services',
'candidates_Dereja_Services',
'candidates_Dereja_Training_Services',
'candidates_Dereja_Event_Services',
'candidates_Dereja_web_profile_completion',
'candidates_Dereja_Information_Source',
'candidates_Employment_Status',
'candidates_Employment_Company',
'candidates_Employment_Position',
'candidates_Remark',
'event_participants_EventID',
'event_participants_CandidateID',
'event_participants_StudentID',
'event_participants_Event_Start_Date',
'event_participants_Event_End_Date',
'event_participants_First_Name',
'event_participants_Middle_Name',
'event_participants_Last_Name',
'event_participants_Full_Name',
'event_participants_Sex',
'event_participants_Phone',
'event_participants_Email',
'event_participants_Disability_Status',
'event_participants_Disability_Type',
'event_participants_Disability_Type_Other',
'event_participants_Participant_Type',
'event_participants_Participant_Field_of_Study',
'event_participants_Participant_Organization_Type',
'event_participants_Participant_Organization_Name',
'event_participants_Participant_Home_Address',
'training_participants_TrainingID',
'training_participants_CandidateID',
'training_participants_StudentID',
'training_participants_Training_Organizer',
'training_participants_Training_Type',
'training_participants_Program_Area',
'training_participants_Training_City_Town',
'training_participants_Training_Venue',
'training_participants_Training_Start_Date',
'training_participants_Training_End_Date',
'training_participants_First_Name',
'training_participants_Middle_Name',
'training_participants_Last_Name',
'training_participants_Full_Name',
'training_participants_Sex',
'training_participants_Email',
'training_participants_Phone',
'training_participants_Disability_Status',
'training_participants_Disability_Type',
'training_participants_Disability_Type_Other',
'training_participants_Participant_Profession',
'training_participants_Participant_Field_of_Study',
'training_participants_Participant_Facility_Organization_Type',
'training_participants_Participant_Organization_Name',
'training_participants_Participants_Home_Address',
'training_participants_PreTest_Score',
'training_participants_Skill_Test',
'training_participants_Post_Test_Score',
'regions_RegionID',
'regions_RegionName',
'regions_Lat',
'regions_Lng',
'Candidate_Employment_Tracker_CandidateID',
'Candidate_Employment_Tracker_JobID',
'Candidate_Employment_Tracker_Referral_from_Dereja_service',
'Candidate_Employment_Tracker_Company_Name',
'Candidate_Employment_Tracker_Company_Phone_Number',
'Candidate_Employment_Tracker_Sector',
'Candidate_Employment_Tracker_Job_Position',
'Candidate_Employment_Tracker_Job_Type',
'Candidate_Employment_Tracker_Job_Placement_Date',
'Candidate_Employment_Tracker_Employment_End_Date',
'Candidate_Employment_Tracker_First_Name',
'Candidate_Employment_Tracker_Middle_Name',
'Candidate_Employment_Tracker_Last_Name',
'Candidate_Employment_Tracker_Full_Name',
'Candidate_Employment_Tracker_CurrentEmploymentStatus' ),
'googleLikeFields' => array( 'candidates_CandidateID',
'candidates_StudentID',
'candidates_First_Name',
'candidates_Middle_Name',
'candidates_Last_Name',
'candidates_Full_Name',
'candidates_Sex',
'candidates_DOB',
'candidates_Region',
'candidates_City',
'candidates_Sub_City',
'candidates_Zone',
'candidates_House_No',
'candidates_Phone_Number',
'candidates_Phone_Number_Alternate',
'candidates_Email_Address',
'candidates_Disability_Status',
'candidates_Disability_Type',
'candidates_Disability_Type_Other',
'candidates_Institution_Type',
'candidates_Institution_Name',
'candidates_Education_Level',
'candidates_Department',
'candidates_Minor',
'candidates_Major',
'candidates_Enrollement_Type',
'candidates_Skills',
'candidates_Languages',
'candidates_English_Proficiency_Level',
'candidates_Industry_Specific_Skills',
'candidates_IT_Related_Skills',
'candidates_Certifications',
'candidates_Year_of_graduation',
'candidates_Field_Of_Study',
'candidates_GPA',
'candidates_Intervention',
'candidates_Campaign',
'candidates_Attend_Employability_Skill',
'candidates_DAAP_enrolled_1st_Round',
'candidates_DAAP_Completed',
'candidates_DAAP_Completed_Courses',
'candidates_Job_Fair_Clinic',
'candidates_Job_Fair',
'candidates_Exit_Exam_Score',
'candidates_Exit_Exam_Status',
'candidates_DAAP_enrolled_2nd_Round',
'candidates_Upload_on_Tracker',
'candidates_Work_Experience',
'candidates_Joined_Dereja_Services',
'candidates_Dereja_Services',
'candidates_Dereja_Training_Services',
'candidates_Dereja_Event_Services',
'candidates_Dereja_web_profile_completion',
'candidates_Dereja_Information_Source',
'candidates_Employment_Status',
'candidates_Employment_Company',
'candidates_Employment_Position',
'candidates_Remark' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c6' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ),
'align' => 'center',
'width' => '' ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'align' => 'center' ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu',
'menuId' => 'DerejaMenuSet' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'notifications' => array( 'type' => 'notifications' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 0,
'dashName' => 'candidates_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'star-o' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'event_participants',
'dashType' => 0,
'dashName' => 'event_participants_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'training_participants',
'dashType' => 0,
'dashName' => 'training_participants_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'flash' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'regions',
'dashType' => 6,
'dashName' => 'regions_map',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'star-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => true,
'detailsMasterTable' => 'candidates',
'mapLatField' => 'Lat',
'mapLonField' => 'Lng',
'mapMarkerIcon' => '' ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'Candidate_Employment_Tracker',
'dashType' => 0,
'dashName' => 'Candidate_Employment_Tracker_grid',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'book' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'candidates',
'dashType' => 3,
'dashName' => 'candidates_record',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'bookmark' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>