<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_response  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeShowAdd"]=true;

		$this->events["BeforeProcessView"]=true;

		$this->events["BeforeQueryView"]=true;

		$this->events["BeforeShowView"]=true;

		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeQueryEdit"]=true;

		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeProcessExport"]=true;



	}

//	handlers

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		if(postvalue("a") == "getdate")
{
	$fd = postvalue("format_date");
	if(!$fd)
		echo runner_date_format("m/d/y", strtotime(postvalue("value")));
	else{
		$fd = str_replace("yyyy","Y",$fd);
		$fd = str_replace("yy","y",$fd);
		echo runner_date_format($fd, strtotime(postvalue("value")));
	}
	exit();
}
if(postvalue("act")=="email"){
	$email=postvalue("email");
	$msg=postvalue("url");
	$subject="Save for later";
	$ret=runner_mail(array('to' => $email, 'subject' => $subject, 'body' => $msg));
	if(!$ret["mailed"])
		echo $ret["message"];
	else
		echo "";
	exit();
}

if(postvalue("act")=="scenario"){
	if(!is_numeric(postvalue("qid")))
		exit();
	$str = "select ".AddFieldWrappers("qid")." from ".AddTableWrappers("sv_scenarios")." where ".AddFieldWrappers("quest")."=".postvalue("qid");
	$rs = CustomQuery($str);
	while($data=db_fetch_array($rs)){
		$qid = $data["qid"];
		$arrAnswers = getAnswerArray($qid, postvalue("hash"));
		$key=0;
		$qids = my_json_decode(postvalue("qids"));
		foreach($qids as $value){
			if(!is_null($value))
				$arrAnswers[$key]=$value;
			$key++;
		}
		$scenario[] = getScenarioResult($qid, $arrAnswers);
	}
	echo my_json_encode($scenario);
	exit();
}
//$pageObject->addJSFile("include/jquery-ui-1.9.2.custom.js");
$pageObject->addJSFile("include/bootstrap-datepicker.js");
$pageObject->addJSFile("include/survey_functions.js");

if (postvalue("sid"))
{
$_SESSION["sid"]=postvalue("sid");
}

if (postvalue("hash"))
{
	$_SESSION["hash"]=postvalue("hash");
}

if (postvalue("totalpage"))
{
	$_SESSION["total_page"]=postvalue("totalpage");
}

if (postvalue("page"))
{
	$_SESSION["page"]=postvalue("page");
}

global $cman;
$conn = $cman->getDefault();
$arrTable = $conn->getTableList();

$tableExist = false;
foreach($arrTable as $val){
	if(strpos(strtoupper($val),strtoupper("sv_survey_".$_SESSION["sid"]))!==false)
		$tableExist = true;
}

if(!$tableExist){
 echo GetCustomLabel("is_not_active");
 exit();
}
if(postvalue("hash")){
	$rss = CustomQuery("select ".AddFieldWrappers("submit")." from ".AddTableWrappers("sv_survey_".$_SESSION["sid"])." where ".AddFieldWrappers("hash")."='".$_SESSION["hash"]."'");
	$data = db_fetch_array($rss);
	if($data["submit"]){
		$username = DBLookup("select userID from ".AddTableWrappers("sv_survey_".postvalue("sid"))." where ".AddFieldWrappers("hash")."='".postvalue("hash")."'");
		$rsnew = DB::Query("select * from ".AddTableWrappers("sv_survey_".postvalue("sid"))." where ".AddFieldWrappers("userID")."='".$username."' order by id desc");
		$data2 = $rsnew->fetchAssoc();
		foreach($data2 as $key=>$val)
			$datanew[$key] = "";
		$datanew["hash"] = md5(mydate("j-n-Y H:i:s",""));
		$datanew["created"] = date("Y-m-d H:i:s");
		$datanew["lastpage"] = 0;
		$datanew["submit"] = 0;
		unset($datanew["id"]);
		DB::Insert("sv_survey_".postvalue("sid"), $datanew);
		header("Location: response_add.php?page=1&hash=".$datanew["hash"]."&sid=".postvalue("sid"));
		exit();
	}
}

if ($_SESSION["page"] > $_SESSION["total_page"])
	return;

$rss = CustomQuery("select * from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data = db_fetch_array($rss);
$format = $data["format"];

if(!postvalue("totalpage")){
	if(postvalue("hash"))
	{
		if($format != 'A')
		{
			$rss = CustomQuery("select ".AddFieldWrappers("lastpage")." from ".AddTableWrappers("sv_survey_".$_SESSION["sid"])." where ".AddFieldWrappers("hash")."='".$_SESSION["hash"]."'");
			$data = db_fetch_array($rss);
			if(postvalue("locat") == "prev")
				$_SESSION["page"] = $data["lastpage"]-1;
			else
				$_SESSION["page"] = $data["lastpage"]+1;
		}
		else
			$_SESSION["page"] = 2;
	}
	else
		$_SESSION["page"] = 1;
}

if (!$_SESSION["sid"] && !postvalue("sid"))
exit();

global $dal;

$rss = CustomQuery("select * from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data = db_fetch_array($rss);
$expires = $data["expires"];
$startdate = $data["startdate"];
$currtime = mydate("Y-m-d","");
$date_mess="";
if(!is_null($startdate) && strtotime($startdate)-strtotime($currtime)>0)
	$date_mess = GetCustomLabel("is_not_yet_started");

if(!is_null($expires) && strtotime($expires)-strtotime($currtime)<0)
	$date_mess = GetCustomLabel("no_longer_available");

if($date_mess != "")
{
	$_SESSION["date_mess"] = $date_mess;
}
else {
	$_SESSION["date_mess"] = '';
}

;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		
global $dal;

$rss = CustomQuery("select * from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data = db_fetch_array($rss);
$format = $data["format"];
$expires = $data["expires"];
$startdate = $data["startdate"];
$currtime = mydate("Y-m-d","");
$date_mess="";
if(!is_null($startdate) && strtotime($startdate)-strtotime($currtime)>0)
	$date_mess = GetCustomLabel("is_not_yet_started");

if(!is_null($expires) && strtotime($expires)-strtotime($currtime)<0)
	$date_mess = GetCustomLabel("no_longer_available"); 
if($date_mess == "")
{
	$_SESSION["date_mess"] = "";
	if($_REQUEST["act"]=="add")
		saveAnswer($_SESSION["sid"]);
}
else {
	$_SESSION["date_mess"] = $date_mess;
}


if($_REQUEST["act"]=="add" && !postvalue("totalpage")){

	$_SESSION["total_page"] = countTotalPage($_SESSION['sid'], postvalue("hash"), $format);
	header("Location: response_add.php?page=".$_REQUEST["page"]."&hash=".$_REQUEST["hash"]."&sid=".$_REQUEST["sid"]);
	exit();
}

// Place event code here.
// Use "Add Action" button to add code snippets.


return false;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		if(!$_REQUEST["hash"])
{
	$_SESSION["total_page"]=0;
	$_SESSION["page"]=0;
	$_SESSION["hash"] = md5(mydate("j-n-Y H:i:s",""));
}

$format = "A";
// test name and description
$rss3 = CustomQuery("select ".AddFieldWrappers("title").", ".AddFieldWrappers("description").", ".AddFieldWrappers("welcome_message").", ".AddFieldWrappers("end_message").", ".AddFieldWrappers("format").", ".AddFieldWrappers("progressbar").", ".AddFieldWrappers("allowprev")." from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data3 = db_fetch_array($rss3);
if ($data3)
{
	$_SESSION["survey_title"] = $data3["title"];
	$_SESSION["survey_description"] = $data3["description"];
	$_SESSION["survey_welcome"] = $data3["welcome_message"];
	$format = $data3["format"];
	$progressbar = $data3["progressbar"];
	$allowprev = $data3["allowprev"];
}
if($_SESSION["total_page"] && $_SESSION["total_page"] < $_SESSION["page"] || $_SESSION["date_mess"]) {
		$_SESSION["survey_title"] = $data3["title"];
		$_SESSION["survey_welcome"] = "";
		$_SESSION["sv_message"] = $_SESSION["date_mess"];
		if ($data3["end_message"])
			$_SESSION["survey_end"] = $data3["end_message"];
		else
			$_SESSION["survey_end"] = "Thank you!";
		$pageObject->hideItem("progressbar");
		$pageObject->hideItem("prev");
		$pageObject->hideItem("finish_button");
		$pageObject->hideItem("save_for_later");
		$pageObject->hideItem("total_questions");
		$pageObject->hideItem("questions_block");
		$pageObject->hideItem("finish_button");

		
		CustomQuery("update ".AddTableWrappers("sv_survey_".$_SESSION["sid"])." set ".AddFieldWrappers("submit")."=1 where ".AddFieldWrappers("hash")."='".$_SESSION["hash"]."'");			
		return;
}
else
	$pageObject->hideItem("end_message");

//if(!$_SESSION["total_page"] || 1==1)
//{
$_SESSION["total_page"] = countTotalPage($_SESSION['sid'], postvalue("hash"), $format);
//}

$pageObject->showItem("questions_block");
$pageObject->showItem("finish_button");

//set global  date format
$rssDate = CustomQuery("select ".AddTableWrappers("fd").".".AddFieldWrappers("format")." from ".AddTableWrappers("sv_surveys")." ".AddTableWrappers("sv")." left join ".AddTableWrappers("sv_format_date")." ".AddTableWrappers("fd")." on ".AddTableWrappers("sv").".".AddFieldWrappers("date_format")."=".AddTableWrappers("fd").".".AddFieldWrappers("id")." where ".AddTableWrappers("sv").".".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$dataDate = db_fetch_array($rssDate);
if ($dataDate)
$_SESSION["format_date"] = $dataDate['format'];


global $dal;
$rowinfo = array();
$group_name="";
$count=0;
// total number of questions in this test
$rss2 = CustomQuery("select ".AddFieldWrappers("id")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$_SESSION["sid"] );
while($data2 = db_fetch_array($rss2)){
	$arrAnswers = getAnswerArray($data2["id"], postvalue("hash"));
	$scenario = getScenarioResult($data2["id"], $arrAnswers);
	
	if(!$scenario["qhide"]){
		$count++;
	}
}

$_SESSION["total_questions"]=$count;

if ($count>1){
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("questions"));
}
else {
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("question"));
}



// all questions on one page mode
$rss=CustomQuery("select ".AddTableWrappers("q").".*,".AddTableWrappers("gr").".".AddFieldWrappers("name").",".AddTableWrappers("gr").".".AddFieldWrappers("description").", ".AddTableWrappers("gr").".".AddFieldWrappers("id")." as ".AddFieldWrappers("gid")." from ".AddTableWrappers("sv_questions")." ".AddTableWrappers("q")."
inner join ".AddTableWrappers("sv_groups")." ".AddTableWrappers("gr")." on ".AddTableWrappers("gr").".".AddFieldWrappers("id")."=".AddTableWrappers("q").".".AddFieldWrappers("group_id")."
where ".AddTableWrappers("q").".".AddFieldWrappers("sid")."=".$_SESSION['sid']."
order by ".AddTableWrappers("gr").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("id"));

if($_SESSION["page"]=="" || $_SESSION["page"] == 0)
	$_SESSION["page"] = 1;


if($_SESSION["total_page"]!=$_SESSION["page"])
	$_SESSION["buttonname"] = GetCustomLabel("next");
else
	$_SESSION["buttonname"] = GetCustomLabel("submit");

$num_group = 0;
$num_question = 0;
$questInPage = 0;
$hideInPage = 0;

$divclassname = "even";	

while($data=db_fetch_array($rss))
{
		$questInPage++;
		$scenario = getScenarioResult($data["id"], $arrAnswers);
		$st="";
		if($scenario["qhide"]){
			$st=" style='display:none'";
			$hideInPage++;
		}
		if(!$scenario["qhide"] && $format == "Q" || $format != "Q"){
			if ($group_name!=$data["name"] || $format == "Q" && ($num_question == $_SESSION["page"] || $_SESSION["page"] == $_SESSION["total_page"]))
			{	
				if($questInPage!=$hideInPage || $hideInPage==0){
					if ($group_name!="" && $questions)
					{
						if($format == "Q")
							$record["group_name"] = "Question ".$_SESSION["page"];
						$record["questions"]=$questions;
						$rowinfo["data"][]=$record;
						$hideInPage = 0;
						$questInPage = 0;
					}
				
					$record = array();
					if($format == "G" || $format == "A")
						$record["group_name"] = $data["name"];
					if($format == "Q")
						$record["group_name"] = "Question ".$_SESSION["page"];
					$record["group_description"] = $data["description"];
					$record["description_block"]=$data["description"]!="";
					$group_name=$data["name"];
					$questions="";
					$num_group++;
				}
			}
			$settings = array();
			$settings["required"] = $data["required"];
			$settings["regexp"] = $data["regex"];
			$settings["other"] = $data["other"];
			$settings["max_length"] = $data["max_length"];
			$settings["int_only"] = $data["int_only"];
			$settings["file_extensions"] = $data["file_extensions"];
			$settings["max_num_of_files"] = $data["max_num_of_files"];
			$settings["max_file_size"] = $data["max_file_size"];
			$settings["help"] = $data["help"];
			$settings["helporientation"] = $data["help_orientation"];
			if ($data["type"]=='X'){
				$questions.= buildInputControlFullImg($data["id"],$settings,$format);
				$questions.= "<div".$st."  class=".$divclassname." id=quest_scen".$data["id"].">".buildQuestionText($data["question"],$data["required"],$data["id"],$data['type']); 
				$questions.= buildInputControl($data["id"],$data["type"],$settings,$format); 
				$questions.= buildInputControlFull($data["id"],$settings,$format)."</div>";
			}
			else {
				$questions.= "<div".$st."  class=".$divclassname." id=quest_scen".$data["id"].">".buildQuestionText($data["question"],$data["required"],$data["id"],$data['type']); 
				$questions.= buildInputControlFullImg($data["id"],$settings,$format);
				$questions.= buildInputControl($data["id"],$data["type"],$settings,$format)."</div>"; 
			}
			$questions.= "<div".$st.">&nbsp;</div>";
			/*if ($divclassname=="even"){
				$divclassname = "odd";
			}
			else {
				$divclassname = "even";
			}*/
			/*if (isset($data["fullquestion"])){
				if ($data["fullquestion"]) {
					$questions.= buildInputControlFull($data["id"],$data["fullquestion"]); 
				}
			}*/
			$num_question++;
			if($format == "A" || $format == "G" && $num_group == $_SESSION["page"] || $format == "Q" && $num_question == $_SESSION["page"])
			{
				if($format == "G")
					$curr_quest = $num_group;
				if($format == "Q")
					$curr_quest = $num_question;
			}
			else
			{
					$record = array();
					$questions = "";
					$hideInPage = 0;
					$questInPage = 0;
			}
		}
}


if(count($record))
{
	$record["questions"]=$questions;
	$rowinfo["data"][]=$record;
}

if(!isset($rowinfo["data"][0]["group_name"]))
{
	header("Location: response_add.php?page=".$_SESSION["page"]."&hash=".$_SESSION["hash"]."&sid=".$_SESSION["sid"]);
	exit();
}

$_SESSION["rowinfo"]= $rowinfo;

if(!$allowprev || $_SESSION["page"]<=1)
	$pageObject->hideItem("prev");

$_SESSION["sv_page"] = "?page=".$_SESSION["page"]."&hash=".$_SESSION["hash"]."&sid=".$_SESSION["sid"]."&act=add";

//$xt->assign("curr_url",$_SESSION["UserID"]);
//$_SESSION["sfl"] = "document.forms[0].action=document.forms[0].action+'&save=later&totalpage=".$_SESSION["total_page"]."';document.forms[0].submit();";
//$_SESSION["saveforlater"] = postvalue("save");
if($progressbar && $format!="A")
{	
	$pageObject->showItem("progressbar");
	$text = "";
	if($_SESSION["total_page"] < 10)
	{
		$text = "";
		for($i=1;$i<=$_SESSION["total_page"];$i++)
		{
			if($i <= $curr_quest)
				$text.="<td class=progress><img src='images/progressbar1.jpg'></td>";
			else
				$text.="<td class=progress><img src='images/progressbar2.jpg'></td>";
		}
	}
	else
	{
		if($_SESSION["page"] > 1)
		{
			$proc = ($_SESSION["page"]-1)*100/$_SESSION["total_page"];
			$text = "<td>".round($proc,1)."%</td><td><div class='ui-progressbar ui-widget ui-widget-content ui-corner-all' style='width:200px;height:20px;'>
			<div style='width: ".$proc."%;height:20px;' class='ui-progressbar-value ui-widget-header ui-corner-left'></div></div></td><td>100%</td>";
		}
	}
	$_SESSION["progreessbar_table"] = $text;
}	
else
	$pageObject->hideItem("progressbar");

$pageObject->setProxyValue("hash",$_SESSION["hash"]);
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
				// View page: Before process
function BeforeProcessView($pageObject)
{

		if ($_REQUEST["sid"])
{
$_SESSION["sid"]=$_REQUEST["sid"];
}
if ($_REQUEST["resp"])
{
$_SESSION["resp"]=$_REQUEST["resp"];
}



;
} // function BeforeProcessView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// View page: Before SQL query
function BeforeQueryView(&$strSQL, &$strWhereClause, $pageObject)
{

		$strWhereClause = "1=1";
;
} // function BeforeQueryView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		if (!$_SESSION["sid"] && !$_REQUEST["sid"] || !$_SESSION["resp"] && !$_REQUEST["resp"])
exit();

//$templatefile="survey_view.htm";

// check if survey is active

// test name and description
$rss3 = CustomQuery("select ".AddFieldWrappers("title").",".AddFieldWrappers("description").", ".AddFieldWrappers("welcome_message")." from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data3 = db_fetch_array($rss3);
if ($data3)
{
	$_SESSION["survey_title"] = $data3["title"];
	$_SESSION["survey_welcome"] = $data3["welcome_message"];
	$_SESSION["survey_description"] = $data3["description"];
}


global $dal;
$rowinfo = array();
$group_name="";

// total number of questions in this test
$rss2 = CustomQuery("select count(".AddFieldWrappers("id").") as ".AddFieldWrappers("c")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$_SESSION["sid"] );
$data2 = db_fetch_array($rss2);
if ($data2)
$count=$data2["c"];


$rss2=CustomQuery("select * from ".AddTableWrappers("sv_survey_".$_SESSION["sid"])." where ".AddFieldWrappers("id")."=".$_SESSION["resp"]);
$data2=db_fetch_array($rss2);

// all questions on one page mode
$rss=CustomQuery("select ".AddTableWrappers("q").".*,".AddTableWrappers("gr").".".AddFieldWrappers("name").",".AddTableWrappers("gr").".".AddFieldWrappers("description")." from ".AddTableWrappers("sv_questions")." ".AddTableWrappers("q")."
inner join ".AddTableWrappers("sv_groups")." ".AddTableWrappers("gr")." on ".AddTableWrappers("gr").".".AddFieldWrappers("id")."=".AddTableWrappers("q").".".AddFieldWrappers("group_id")."
where ".AddTableWrappers("q").".".AddFieldWrappers("sid")."=".$_SESSION['sid']."
order by ".AddTableWrappers("gr").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("id"));

while($data=db_fetch_array($rss))
{
	$arrAnswers = getAnswerArray($data["id"], $data2["hash"]);
	$scenario = getScenarioResult($data["id"], $arrAnswers);
	if(!$scenario["qhide"]){
		if ($group_name!=$data["name"])
		{	
			if ($group_name!="")
			{
				$record["questions"]=$questions;
				$rowinfo["data"][]=$record;

			}
			$record = array();
			$record["group_name"] = $data["name"];
			$record["group_description"] = $data["description"];
			$record["description_block"]=$data["description"]!="";
			$group_name=$data["name"];
			$questions="";
		}

 	  $questions.= "<div class='even_view'><b>".buildQuestionText($data["question"],$data["required"],$data["id"],$data['type'])."</b>";  
		$settings = array();
		$settings["required"] = $data["required"];
		$settings["other"] = $data["other"];
		$rss2=CustomQuery("select * from ".AddTableWrappers("sv_survey_".$_SESSION["sid"])." where ".AddFieldWrappers("id")."=".$_SESSION["resp"]);
		if($data2)
			$questions.= buildViewControl($data2, $data["type"],$data["id"], $data["group_id"]);
		$questions.= "</div>";
	}
	else
		$count--;
}

if ($count>1){
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("questions"));
}
else {
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("question"));
}

if ($record)
{
	$record["questions"]=$questions;
	$rowinfo["data"][]=$record;
}

$_SESSION["rowinfo"]= $rowinfo;









;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		if (postvalue("sid"))
{
$_SESSION["sid"]=postvalue("sid");
}

;
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Edit page: Before SQL query
function BeforeQueryEdit(&$strSQL, &$strWhereClause, $pageObject)
{

		$strWhereClause = "1=1";
;
} // function BeforeQueryEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		
if (!$_SESSION["sid"] && !$_REQUEST["sid"])
	exit();


//$templatefile="survey_stats.htm";

// check if survey is active

// test name and description
$rss3 = CustomQuery("select ".AddFieldWrappers("title").", ".AddFieldWrappers("welcome_message")." from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$_SESSION["sid"]);
$data3 = db_fetch_array($rss3);
if ($data3)
{
	$_SESSION["survey_title"] = $data3["title"];
	$_SESSION["survey_welcome"] = $data3["welcome_message"];
	$_SESSION["survey_description"] = $data3["description"];
}


global $dal;
$rowinfo = array();
$group_name="";

// total number of questions in this test
$rss2 = CustomQuery("select count(".AddFieldWrappers("id").") as ".AddFieldWrappers("c")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$_SESSION["sid"] );
$data2 = db_fetch_array($rss2);
if ($data2)
$count=$data2["c"];
if ($count>1){
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("questions"));
}
else {
	$_SESSION["total_questions"] = str_replace("%count%",$count,GetCustomLabel("question"));
}



// all questions on one page mode
$rss=CustomQuery("select ".AddTableWrappers("q").".*,".AddTableWrappers("gr").".".AddFieldWrappers("name").",".AddTableWrappers("gr").".".AddFieldWrappers("description")." from ".AddTableWrappers("sv_questions")." ".AddTableWrappers("q")."
inner join ".AddTableWrappers("sv_groups")." ".AddTableWrappers("gr")." on ".AddTableWrappers("gr").".".AddFieldWrappers("id")."=".AddTableWrappers("q").".".AddFieldWrappers("group_id")."
where ".AddTableWrappers("q").".".AddFieldWrappers("sid")."=".$_SESSION['sid']."
order by ".AddTableWrappers("gr").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("sortorder").",".AddTableWrappers("q").".".AddFieldWrappers("id"));

while($data=db_fetch_array($rss))
{
	if ($group_name!=$data["name"])
	{	
		if ($group_name!="")
		{
			$record["questions"]=$questions;
			$rowinfo["data"][]=$record;

		}
		$record = array();
		$record["group_name"] = $data["name"];
		$record["group_description"] = $data["description"];
		$record["description_block"]=$data["description"]!="";
		$group_name=$data["name"];
		$questions="";
	}

	$questions.= "<div class='even_view'><b>".buildQuestionText($data["question"],$data["required"],$data["id"],$data['type'])."</b>";  
	$settings = array();
	$settings["required"] = $data["required"];
	$settings["other"] = $data["other"];

	$questions.= buildViewControlStats($data["id"],$data["type"],$data["group_id"],$settings)."</div>";

}

if ($record)
{
	$record["questions"]=$questions;
	$rowinfo["data"][]=$record;
}

$_SESSION["rowinfo"]= $rowinfo;








;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
				// Export page: Before process
function BeforeProcessExport($pageObject)
{

		if ($_REQUEST["sid"])
{
$_SESSION["sid"]=$_REQUEST["sid"];
}
if ($_REQUEST["resp"])
{
$_SESSION["resp"]=$_REQUEST["resp"];
}


;
} // function BeforeProcessExport

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>