<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_sv_answer_options  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowList"]=true;


		$this->events["BeforeAdd"]=true;

		$this->events["BeforeProcessList"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["ProcessValuesAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		
if(!$_SESSION["survey_active"]){
	$xt->assign("inlineadd_link",true);
	$xt->assign("deleteselected_link",true);
}
else{
	$xt->assign("inlineadd_link",false);
	$xt->assign("deleteselected_link",false);
}

;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		if(empty($values["sortorder"])){
		$values["sortorder"] = 1;
		$sort = 2;
		$rs = DB::Query("select * from ".addTableWrappers("sv_answer_options")." where ".addFieldWrappers("question_id")."=".$values["question_id"]." order by ".addFieldWrappers("sortorder"));
		while($data = $rs->fetchAssoc()){
			DB::Update("sv_answer_options", array("sortorder"=>$sort), array("id"=>$data["id"]));
			$sort++;
		}
}
return true;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

				// List page: Before process
function BeforeProcessList($pageObject)
{

					$mr = $pageObject->getMasterRecord();

			if(count($mr)>0){
					$max = DB::Query("select max(".addFieldWrappers("sortorder").") from ".addTableWrappers("sv_answer_options")." where ".addFieldWrappers("question_id")."=".$mr["id"]);
					if( is_null($max->value(0)) ){
							$_SESSION["sv_answer_options_default_sortorder"] = 1;
					}
					else{
					
							$_SESSION["sv_answer_options_default_sortorder"] = intval($max->value(0))+1;

					}

			}


;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

					$mr = $pageObject->getMasterRecord();

			if(count($mr)>0){
					$max = DB::Query("select max(".addFieldWrappers("sortorder").") from ".addTableWrappers("sv_answer_options")." where ".addFieldWrappers("question_id")."=".$mr["id"]);
					//Если еще не было записей, ставим единицу
					if( is_null($max->value(0)) ){
							$_SESSION["sv_answer_options_default_sortorder"] = 1;
					}
					else{
					
							$_SESSION["sv_answer_options_default_sortorder"] = intval($max->value(0))+1;

					}

			}
;
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$mr = $pageObject->getMasterRecord();

if(count($mr)>0){
		$max = DB::Query("select max(".addFieldWrappers("sortorder").") from ".addTableWrappers("sv_answer_options")." where ".addFieldWrappers("question_id")."=".$mr["id"]);
		if( is_null($max->value(0)) ){
				$_SESSION["sv_answer_options_default_sortorder"] = 1;
		}
		else{
		
				$_SESSION["sv_answer_options_default_sortorder"] = intval($max->value(0))+1;

		}

}
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesAdd(&$values, $pageObject)
{

		
//print_r($values);
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function ProcessValuesAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>