<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_sv_questions  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeDelete"]=true;

		$this->events["BeforeShowList"]=true;


		$this->events["BeforeProcessAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeShowAdd"]=true;


		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeShowEdit"]=true;


		$this->events["BeforeMoveNextList"]=true;



	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		if(postvalue("a") == "reorder"){
	$respJSON = array();
	$txt = '
	<div class="demo">
	<ul id="sortable">';
	if(postvalue("type") == "group")
		$rs=DB::Query("select gr.".addFieldWrappers("id").", gr.".addFieldWrappers("name").", count(q.".addFieldWrappers("id").") as quest from ".addTableWrappers("sv_groups")." gr left join ".addTableWrappers("sv_questions")." q on gr.".addFieldWrappers("id")."=q.".addFieldWrappers("group_id")." where gr.".addFieldWrappers("sid")."=".postvalue("sid")." group by gr.".addFieldWrappers("id").", gr.".addFieldWrappers("name").",gr.".addFieldWrappers("sortorder")." order by gr.".addFieldWrappers("sortorder").",gr.".addFieldWrappers("id"));
	else	
		$rs=DB::Query("select ".addFieldWrappers("id").", ".addFieldWrappers("question")." as name, '1' as quest from ".addTableWrappers("sv_questions")." where ".addFieldWrappers("group_id")."=".postvalue("sid")." order by ".addFieldWrappers("sortorder").",".addFieldWrappers("id"));

		while($data = $rs->fetchAssoc())
		{
			if($data["quest"]>0)
				$txt.='<li class="ui-state-default" id='.$data["id"].'>'.$data["name"].'</li>';
		}
		
	$txt.='</ul>

	</div>';
	$respJSON['html'] = $txt;
	echo my_json_encode($respJSON);
	exit();
}

$strTableName = $pageObject->tName;

if (postvalue("masterkey1")){
		$_SESSION["sid"] = postvalue("masterkey1");
	}
	else{
		$_SESSION["sid"] = $_SESSION[$strTableName."_masterkey1"];
	}

if($_GET["attr"])
{
	$attr = substr($_GET["attr"],0,-1);
	$arr = explode(",",$attr);
	foreach($arr as $key=>$value)
	{
		if($_GET["type"] == "group")
			CustomQuery("update ".AddTableWrappers("sv_groups")." set ".AddFieldWrappers("sortorder")."=".($key+1)." where ".AddFieldWrappers("id")."=".$value);
		else
			CustomQuery("update ".AddTableWrappers("sv_questions")." set ".AddFieldWrappers("sortorder")."=".($key+1)." where ".AddFieldWrappers("id")."=".$value);
	}
	$sid = '';
	if (postvalue("masterkey1")){
		$sid = postvalue("masterkey1");
	}
	else {
		$sid = $_SESSION[$strTableName."_masterkey1"];
	}
	
	
	header("Location: sv_questions_list.php?mastertable=".$_SESSION[$strTableName."_mastertable"]."&masterkey1=".$sid);
}

if (!$_GET["a"] && $_GET["masterkey1"] && $_GET["mastertable"]){
	$rss=CustomQuery("select count(".AddFieldWrappers("id").") as ".AddFieldWrappers("cquest")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$_GET["masterkey1"]);
	$data1 = db_fetch_array($rss);
	if (!$data1['cquest'] && postvalue("loc")<>"survey"){
		header("Location: sv_questions_list.php?mastertable=".$_GET["mastertable"]."&masterkey1=".$_GET["masterkey1"]."&loc=survey");
	}
}
$_SESSION["group"]="";

;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record deleted
function BeforeDelete($where, &$deleted_values, &$message, $pageObject)
{

		CustomQuery("delete from ".AddTableWrappers("sv_scenarios")." where ".AddFieldWrappers("qid")."=".$deleted_values["id"]);


// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		$strTableName = $pageObject->tName;
$pageObject->AddJSFile("include/survey_functions.js");
if (!$pageObject->rowsFound){
	$xt->displayBrickHidden("message");
}
$sid = "";
if ($_GET["masterkey1"]){
	$sid = $_GET["masterkey1"];
}
else {
	$sid = $_SESSION[$strTableName."_masterkey1"];
}
$_SESSION["q_sid"] = $sid;
if ($sid != '') {
	$rss=CustomQuery("select ".AddFieldWrappers("active")." from ".AddTableWrappers("sv_surveys")." where ".AddFieldWrappers("id")."=".$sid);
	$data = db_fetch_array($rss);
	if ($data)
	{
		$tmp_active = 0;
		if($data["active"] == 1){
			$pageObject->setProxyValue("hideB","true");
			$tmp_active = 1;
		}
		$_SESSION["survey_active"]=$tmp_active;
	}
	$rss=CustomQuery("select count(".AddFieldWrappers("group_id").") as ".AddFieldWrappers("cgr")." from (select ".AddFieldWrappers("group_id")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$sid." group by ".AddFieldWrappers("group_id").") ".AddFieldWrappers("aaa"));
	$data = db_fetch_array($rss);
	if ($data)
	{
		if($data["cgr"]<=1)
		{
			$pageObject->hideItem("reorder_groups");
		}
	}
}




// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
				// Add page: Before process
function BeforeProcessAdd($pageObject)
{

		$strTableName = $pageObject->tName;
$_SESSION["gr_masterkey"] = $_SESSION[$strTableName."_masterkey1"];
$_SESSION["curr_qid"]=0;

$_SESSION["sv_question_details_default_sortorder"] = 0;
$_SESSION["sv_answer_options_default_sortorder"] = 0;
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$strTableName = $pageObject->tName;

if (!$values['sortorder'] || $values['sortorder']==0)
{
	$rss = CustomQuery("select max(".AddFieldWrappers("sortorder").")+1 as ".AddFieldWrappers("c")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("sid")."=".$_SESSION[$strTableName."_masterkey1"]." and ".AddFieldWrappers("group_id")."=".$values["group_id"]);
	$data1 = db_fetch_array($rss);
	$values['sortorder']=$data1["c"];
}

return true;
;
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowAdd(&$xt, &$templatefile, $pageObject)
{

		$pageObject->AddJSFile("include/survey_functions.js");
$xt->assign("imagetype","<img align='left' id='imgType' src='' style='border:1px solid #000000; display:none;'>");
$xt->assign("ansoptHidden","style='display:none'");
$xt->assign("answerHidden","style='display:none'");

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		$_SESSION["curr_qid"]=postvalue("editid1");
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$pageObject->AddJSFile("include/survey_functions.js");
if(!$_SESSION["survey_active"]){
	$xt->assign("type_fieldblock",true);
	$xt->assign("group_id_fieldblock",true);
	$xt->assign("other_fieldblock",true);
}
else{
	$xt->assign("type_fieldblock",false);
	$xt->assign("group_id_fieldblock",false);
	$xt->assign("other_fieldblock",false);
}
$xt->assign("view_page_button",false);
$xt->assign("ansoptHidden","style='display:none'");
$xt->assign("answerHidden","style='display:none'");
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		$row_data = "";
if($_SESSION["group"]!=$data['groupname'])
{
	$_SESSION["group"]=$data["groupname"];
	$row_showheader=true;
	$row_data=$data["groupname"];
	/*$row["editgroup"] = 	'<a href="sv_groups_edit.php?editid1='.$data['group_id'].'" name="editLink'.$data['group_id'].'" id="editLink'.$data['group_id'].'" 
	title="Edit" class="runner-button-img" onclick="showEditGroup('.$data['group_id'].')">
	<img src="images/icon_edit_new.gif" alt="Edit" class="runner-cicon"></a>';*/
	$row_data.= '<a href="#" title="Edit" class="runner-button-img" onclick="showEditGroup('.$data['group_id'].');return false;">
	<img src="images/icon_edit_new.gif" alt="Edit" class="runner-cicon"></a>';

	$rss=CustomQuery("select count(".AddFieldWrappers("id").") as ".AddFieldWrappers("cquest")." from ".AddTableWrappers("sv_questions")." where ".AddFieldWrappers("group_id")."=".$data["group_id"]);
	$data1 = db_fetch_array($rss);
	if ($data1)
	{
		if($data1["cquest"]>"1")
		{

			$row_data.= "&nbsp;&nbsp;<A class='rnr-link' href='#' onclick='showReorder(\"quest\",".$data["group_id"]."); return false;'>
													Re-order questions
												 </A>";
		}
	}
	$record["grouptext_value"] = $row_data;
}
else
		$pageObject->hideItem("grouptext", $recordId);
	

if (!hasSubquestions($data["type"]))
$record["sv_question_details_dtable_link"]=false;

if (!hasAnswerOptions($data["type"]))
$record["sv_answer_options_dtable_link"]=false;






;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>