<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_sv_scenarios  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessList"]=true;

		$this->events["BeforeShowList"]=true;

		$this->events["BeforeMoveNextList"]=true;



	}

//	handlers

				// List page: Before process
function BeforeProcessList($pageObject)
{

		$curr_q=0;
if(postvalue("masterkey1"))
	$curr_q=postvalue("masterkey1");
elseif(postvalue("editid1"))
	$curr_q=postvalue("editid1");
		
$sql="SELECT ".AddFieldWrappers("sv_questions").".".AddFieldWrappers("id").",".AddFieldWrappers("sv_questions").".".AddFieldWrappers("type")." FROM ".AddFieldWrappers("sv_questions")." INNER JOIN ".AddFieldWrappers("sv_groups")." ON ".AddFieldWrappers("sv_questions").".".AddFieldWrappers("group_id")." = ".AddFieldWrappers("sv_groups").".".AddFieldWrappers("id")." where ".AddFieldWrappers("sv_questions").".".AddFieldWrappers("sid")."=".$_SESSION["sid"]." ORDER BY ".AddFieldWrappers("sv_groups").".".AddFieldWrappers("sortorder").", ".AddFieldWrappers("sv_questions").".".AddFieldWrappers("sortorder").", ".AddFieldWrappers("sv_questions").".".AddFieldWrappers("id");
$rs=CustomQuery($sql);
$res="";
$my_break = true;
while($data=db_fetch_array($rs)){
	if($data["id"]==$curr_q || !$my_break)
		$my_break = false;
	else{
		if(strlen($res)>0)
			$res.=",";
		$res.=$data["id"];
	}
}
if(!$res)
	$res=0;
$_SESSION["curr_qid"]=$res;


// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeProcessList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowList(&$xt, &$templatefile, $pageObject)
{

		
if(!$_SESSION["survey_active"]){
	$xt->assign("inlineadd_link",true);
	$xt->assign("deleteselected_link",true);
	$xt->assign("editselected_link",true);
}
else{
	$xt->assign("inlineadd_link",false);
	$xt->assign("deleteselected_link",false);
	$xt->assign("editselected_link",false);
}

;
} // function BeforeShowList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		if($_SESSION["survey_active"]){
	$record["inlineeditlink_attrs"]="style='display:none'";
}


//print_r($record);
//inlineeditlink_attrs

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>