<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_Share  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeProcessEdit"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["ProcessValuesEdit"]=true;

		$this->events["BeforeShowEdit"]=true;



	}

//	handlers

		
		
		
		
				// Edit page: Before process
function BeforeProcessEdit($pageObject)
{

		if (postvalue("hash")) {
	$_SESSION["file_type"]=DBLookup("select ".addFieldWrappers("file_type")." from ".AddTableWrappers("doc_files")." where ".addFieldWrappers("hash")."='".postvalue("hash")."'");
	$_SESSION["share_hash"] = postvalue("hash");
}
;
} // function BeforeProcessEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		global $cLoginTable, $cUserNameField;

$values["hash"]=$_SESSION["share_hash"];

if($values["share_type"] == 1 && $values["share_users"] == "")
	$values["share_type"] = 4;

if($values["share_type"] == 2){
	$res="";
	DB::SetConnection(DB::ConnectionByTable($cLoginTable));
	$rs = DB::Query("select ".addFieldWrappers("id")." from ".addFieldWrappers($cLoginTable)." where ".addFieldWrappers("id")."<>".$_SESSION["user_id"]);
	DB::SetConnection(DB::DefaultConnection());
	while($data = db_fetch_array($rs)){
		if($res)
			$res.=",";
		$res.=$data["id"];
	}
	$oid = isOwner($_SESSION["current_folder"]);
	$arr = explode(",",$res);
	if(!in_array($oid,$arr)){
		if($res)
			$res.=",";
		$res.= $oid;
	}
	$values["share_users"] = $res;
}

if(($values["share_type"] == 1 || $values["share_type"] == 2) && $values["share_users"] != $oldvalues["share_users"] && $oldvalues["share_users"]!=""){
	
	$oid = isOwner($_SESSION["current_folder"]);
	$arr = explode(",",$values["share_users"]);
	if(!in_array($oid,$arr)){
		if($values["share_users"])
			$values["share_users"].=",";
		$values["share_users"].= $oid;
	}
	
	if($oldvalues["share_startPoint"]!=$oldvalues["share_users"] && $values["share_type"] != 5){
			$arrnew = array();
			$arrold = array();
			$arrpoint = array();
			if($values["share_users"])
				$arrnew = explode(",",$values["share_users"]);
			if($oldvalues["share_users"])
				$arrold = explode(",",$oldvalues["share_users"]);
			if($oldvalues["share_startPoint"])
				$arrpoint = explode(",",$oldvalues["share_startPoint"]);
			$addarr = array_diff($arrnew,$arrold);
			$delarr = array_diff($arrold,$arrnew);
			$arrpoint = array_diff($arrpoint,$delarr);
			$arrpoint = array_merge($arrpoint,$addarr);
			$values["share_startPoint"] = implode(",",$arrpoint);
	}
	else{
		$values["share_startPoint"] = $values["share_users"];
	}
}

if($values["share_type"] == 3){
	$values["share_startPoint"] = null;
	$values["share_users"] = null;
}
if($values["share_type"] == 4){
	$values["share_startPoint"] = null;
	$values["share_users"] = null;
	$values["share_ro"] = null;
	$values["share_needDate"] = null;
	$values["share_date"] = null;
	$values["downloads"] = null;
}

return true;

;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		if(($values["share_type"]==1 or $values["share_type"]==2) and $values["file_type"]=="folder"){
	setChildrenRights($keys["id"],$values);
}
if($values["share_type"]==3){
	if($values["file_type"]=="folder")
		setChildrenRights($keys["id"],$values);
	$message=$values['share_message']."\n\n".$values['name'];
	//$subject=$_SESSION["full_name"]." shared a ".$_SESSION["file_type"]." with you";
	$subject = GetCustomLabel("user_shared_file");
	$subject = str_replace("%username%",$_SESSION["full_name"],$subject);
	$subject = str_replace("%file_type%",$_SESSION["file_type"],$subject);
	
		$url = projectURL() . GetTableLink( "doc_files", "list" );
	$message.="\n\n".$url."?hash=".$values['hash'];
	$email=$values['share_sendto'];
	if($email){
		$ret = runner_mail(array('to' => $email, 'subject' => $subject, 'body' => $message));
		if(!$ret["mailed"])
			$_SESSION["message"] = $ret["message"];
		else
			$_SESSION["message"] = GetCustomLabel("noty_sent");
	}
}
if($values["share_type"] == 4 and $values["file_type"]=="folder"){
		resetChildrenRights($keys["id"],$values);
}
$_SESSION["afterUpdate"] = "true";


;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Process record values
function ProcessValuesEdit(&$values, $pageObject)
{

		if(!$values["share_type"]){
	$values["share_type"] = 4;
	$values["share_ro"] = GetCustomLabel("read_write");
	//$values["share_message"] = "I'd like to share ".$_SESSION["file_type"]." with you";
}

if(!$values["share_ro"])
	 $values["share_ro"] = GetCustomLabel("read_write");


if(!$values["share_date"])
	$values["share_date"] = now();

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function ProcessValuesEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$xt->assign("header",false);
$xt->assign("footer",false);
$xt->assign("back_button",false);
$xt->assign("container_header", false);
$xt->assign("righteditbuttons", false);
if(!$values["share_type"]){
	$values["share_type"] = 4;
}
	
$url = projectURL() . GetTableLink( "doc_files", "list" );	

$xt->assign("hash_editcontrol",$url);

if($values["share_type"]==1){
	$pageObject->hideField("hash");
	$pageObject->hideField("share_sendto");
	$pageObject->hideField("share_message");
	$pageObject->showField("share_ro");
	$pageObject->hideField("share_needDate");
	$pageObject->hideField("share_date");
	$pageObject->showField("share_users");
}
if($values["share_type"]==2){
	$pageObject->hideField("hash");
	$pageObject->hideField("share_sendto");
	$pageObject->hideField("share_message");
	$pageObject->showField("share_ro");
	$pageObject->hideField("share_needDate");
	$pageObject->hideField("share_date");
	$pageObject->hideField("share_users");
}
if($values["share_type"]==3){
	$pageObject->hideField("share_users");
	$pageObject->showField("hash");
	$pageObject->showField("share_sendto");
	$pageObject->showField("share_message");
	$pageObject->showField("share_ro");
	$pageObject->showField("share_needDate");
	$pageObject->showField("share_date");
}
if($values["share_type"]==4){
	$pageObject->hideField("share_users");
	$pageObject->hideField("hash");
	$pageObject->hideField("share_sendto");
	$pageObject->hideField("share_message");
	$pageObject->hideField("share_needDate");
	$pageObject->hideField("share_date");
	$pageObject->hideField("share_ro");
}

if($_SESSION["afterUpdate"] == "true"){
	$pageObject->setProxyValue("afterUpdate","true");
	$_SESSION["afterUpdate"] = "";
}
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>