<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'spreadsheetMode' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 2 ),
'details' => array( 'hd_messages' => array( 'displayPreview' => 2,
'previewPageId' => '',
'showCount' => false,
'badgeColor' => '',
'hideEmptyChild' => false,
'hideEmptyPreview' => null,
'showProceedLink' => null,
'printDetails' => false ) ),
'master' => array( 'hd_folders' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id' => array( 'totalsType' => '' ),
'created' => array( 'totalsType' => '' ),
'subject' => array( 'totalsType' => '' ),
'statusid' => array( 'totalsType' => '' ),
'priorityid' => array( 'totalsType' => '' ),
'folderid' => array( 'totalsType' => '' ),
'categoryid' => array( 'totalsType' => '' ),
'directionid' => array( 'totalsType' => '' ),
'ticketemail' => array( 'totalsType' => '' ),
'assignedid' => array( 'totalsType' => '' ),
'attached' => array( 'totalsType' => '' ),
'cnt' => array( 'totalsType' => '' ),
'ticketid' => array( 'totalsType' => '' ),
'clientinfo' => array( 'totalsType' => '' ),
'clientid' => array( 'totalsType' => '' ),
'updated' => array( 'totalsType' => '' ),
'client_status' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'attached',
'ticketemail',
'subject',
'cnt',
'priorityid',
'created',
'assignedid',
'updated' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'created',
'client_status',
'subject',
'statusid',
'folderid',
'categoryid',
'ticketemail',
'assignedid',
'priorityid',
'updated' ),
'filterFields' => array( 'statusid' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'subject' => array( 'simple_grid_field2',
'simple_grid_field6' ),
'ticketemail' => array( 'simple_grid_field',
'simple_grid_field5' ),
'attached' => array( 'grid_field1' ),
'cnt' => array( 'messages_label',
'cnt_field' ),
'priorityid' => array( 'priority_label',
'priorityid_field' ),
'created' => array( 'created_field',
'created_label' ),
'assignedid' => array( 'assign_label',
'assigned_field' ),
'updated' => array( 'grid_field',
'grid_field_label' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'hd_tickets_context_menu',
'pupup_menus',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'change_status',
'change_priority',
'change_assigned',
'More_button',
'inline_add',
'delete',
'close_tickets',
'move_to_folder',
'folder_select',
'new_ticket',
'details_found',
'page_size',
'pagination',
'snippet',
'print_panel' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field5',
'simple_grid_field',
'simple_grid_field6',
'simple_grid_field2',
'action_info',
'created_label',
'created_field',
'assign_label',
'assigned_field',
'priority_label',
'priorityid_field',
'grid_checkbox_head',
'grid_checkbox',
'grid_field1',
'messages_label',
'cnt_field',
'grid_field_label',
'grid_field',
'grid_inline_cancel' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'below-grid' => array(  ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'hd_tickets_context_menu' => 'supertop',
'pupup_menus' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'change_status' => 'above-grid',
'change_priority' => 'above-grid',
'change_assigned' => 'above-grid',
'More_button' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'close_tickets' => 'above-grid',
'move_to_folder' => 'above-grid',
'folder_select' => 'above-grid',
'new_ticket' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'above-grid',
'snippet' => 'above-grid',
'print_panel' => 'above-grid',
'simple_grid_field5' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field2' => 'grid',
'action_info' => 'grid',
'created_label' => 'grid',
'created_field' => 'grid',
'assign_label' => 'grid',
'assigned_field' => 'grid',
'priority_label' => 'grid',
'priorityid_field' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_field1' => 'grid',
'messages_label' => 'grid',
'cnt_field' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_inline_cancel' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'action_info' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'created_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'created_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'assign_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'assigned_field' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'priority_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'priorityid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox1' ),
'messages_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'cnt_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'collapse_button' => array( 'collapse_button' ),
'-' => array( '-',
'-1',
'-2',
'-3',
'-4' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field',
'grid_field1',
'cnt_field',
'priorityid_field',
'created_field',
'assigned_field',
'grid_field' ),
'master_info' => array( 'master_info' ),
'logo' => array( 'logo1' ),
'grid_field_label' => array( 'simple_grid_field5',
'simple_grid_field6',
'messages_label',
'priority_label',
'created_label',
'assign_label',
'grid_field_label' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'custom_button' => array( 'close_tickets',
'change_status',
'change_priority',
'change_assigned',
'move_to_folder',
'new_ticket',
'More_button' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'snippet' => array( 'folder_select',
'hd_tickets_context_menu',
'pupup_menus',
'snippet',
'action_info' ),
'print_panel' => array( 'print_panel' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'ticketemail_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'subject_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'cnt_fieldheadercolumn' ),
'items' => array( 'messages_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'priorityid_fieldheadercolumn' ),
'items' => array( 'priority_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'created_fieldheadercolumn' ),
'items' => array( 'created_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'assignedid_fieldheadercolumn' ),
'items' => array( 'assign_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'updated_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'attached_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'ticketemail_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'simple_grid_field2',
'action_info' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'cnt_fieldcolumn' ),
'items' => array( 'cnt_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'priorityid_fieldcolumn' ),
'items' => array( 'priorityid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'created_fieldcolumn' ),
'items' => array( 'created_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'assignedid_fieldcolumn' ),
'items' => array( 'assigned_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'updated_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 10,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'Close_selected_tickets',
'Change_Status',
'Change_Priority',
'Assign',
'Move_to_Folder1',
'New_Ticket1',
'More_button' ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'Close_selected_tickets',
'Change_Status',
'Change_Priority',
'Assign',
'Move_to_Folder1',
'New_Ticket1',
'More_button' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'hd_tickets_context_menu',
'pupup_menus' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c3' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'change_status',
'change_priority',
'change_assigned',
'More_button',
'inline_add',
'delete',
'close_tickets',
'move_to_folder',
'folder_select',
'new_ticket' ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
 width:70%!important;
}
' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'details_found',
'page_size',
'pagination' ),
'align' => 'right',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  width:30% !important;
}
' ),
'c4' => array( 'model' => 'c3',
'items' => array( 'snippet' ) ),
'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'print_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_checkbox1' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field3' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_checkbox1' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field3' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox',
'colspan' => 2 ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field3' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'ticketemail',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'nowrap' => true,
'field' => 'ticketemail',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'subject',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2',
'action_info' ),
'nowrap' => true,
'customCSS' => ':host {
  padding-left:6px;
}
',
'field' => 'subject',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'created_label' ),
'field' => 'created',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'created_field' ),
'nowrap' => true,
'customCSS' => ':host {
  padding-left:6px;
}
',
'field' => 'created',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'assign_label' ),
'field' => 'assignedid',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'assigned_field' ),
'nowrap' => true,
'customCSS' => ':host {
  padding-left:6px;
}
',
'field' => 'assignedid',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'priority_label' ),
'field' => 'priorityid',
'columnName' => 'field' ),
'headcell_field6' => array( 'model' => 'cell_field',
'items' => array( 'priorityid_field' ),
'customCSS' => ':host {
  padding-left:6px;
}
',
'field' => 'priorityid',
'columnName' => 'field' ),
'headcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'align' => 'center' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'align' => 'center' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_checkbox1' => array( 'model' => 'headcell_checkbox',
'items' => array(  ),
'customCSS' => '/* Put  your custom CSS code here */

:host {
  width:30px;
}
' ),
'cell_checkbox1' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_field1' ),
'align' => 'center',
'field' => 'attached',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'messages_label' ),
'align' => 'center',
'field' => 'cnt',
'columnName' => 'field' ),
'headcell_field9' => array( 'model' => 'cell_field',
'items' => array( 'cnt_field' ),
'align' => 'center',
'field' => 'cnt',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'updated',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'updated',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'width' => '100%' ),
'c' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-4',
'advsearch_link',
'show_search_panel',
'hide_search_panel' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field2' => array( 'field' => 'subject',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'hd_folders' => 'true' ) ),
'logo1' => array( 'type' => 'logo' ),
'simple_grid_field' => array( 'field' => 'ticketemail',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'label' => array( 'field' => 'ticketemail',
'table' => 'hd_tickets',
'type' => 3 ) ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'ticketemail' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'subject' ),
'delete' => array( 'type' => 'delete' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'-4' => array( 'type' => '-' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'grid_field1' => array( 'field' => 'attached',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'close_tickets' => array( 'eventId' => 'Close_selected_tickets',
'label' => array( 'text' => 'Close selected tickets',
'type' => 0 ),
'type' => 'custom_button' ),
'change_status' => array( 'eventId' => 'Change_Status',
'label' => array( 'text' => 'Change Status',
'type' => 0 ),
'type' => 'custom_button' ),
'change_priority' => array( 'eventId' => 'Change_Priority',
'label' => array( 'text' => 'Change Priority',
'type' => 0 ),
'type' => 'custom_button' ),
'change_assigned' => array( 'eventId' => 'Assign',
'label' => array( 'text' => 'Assign',
'type' => 0 ),
'type' => 'custom_button' ),
'move_to_folder' => array( 'eventId' => 'Move_to_Folder1',
'label' => array( 'text' => 'Move to Folder',
'type' => 0 ),
'type' => 'custom_button' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'messages_label' => array( 'type' => 'grid_field_label',
'field' => 'cnt',
'label' => array( 'field' => 'cnt',
'table' => 'hd_tickets',
'type' => 3 ),
'mobileControl' => '' ),
'cnt_field' => array( 'field' => 'cnt',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'mobileControl' => '' ),
'priority_label' => array( 'type' => 'grid_field_label',
'field' => 'priorityid',
'label' => array( 'field' => 'priorityid',
'table' => 'hd_tickets',
'type' => 3 ),
'mobileControl' => '' ),
'priorityid_field' => array( 'field' => 'priorityid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'mobileControl' => '' ),
'created_field' => array( 'field' => 'created',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'mobileControl' => '' ),
'created_label' => array( 'type' => 'grid_field_label',
'field' => 'created',
'mobileControl' => '' ),
'assign_label' => array( 'type' => 'grid_field_label',
'field' => 'assignedid',
'label' => array( 'field' => 'assignedid',
'table' => 'hd_tickets',
'type' => 3 ),
'mobileControl' => '' ),
'assigned_field' => array( 'field' => 'assignedid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'label' => array( 'field' => 'assignedid',
'table' => 'hd_tickets',
'type' => 3 ),
'mobileControl' => '' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field1',
'search_panel_field9',
'search_panel_field2',
'search_panel_field3',
'search_panel_field6',
'search_panel_field5',
'search_panel_field7',
'search_panel_field8',
'search_panel_field4',
'search_panel_field' ) ),
'search_panel_field' => array( 'field' => 'updated',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'new_ticket' => array( 'eventId' => 'New_Ticket1',
'label' => array( 'text' => 'New Ticket',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'default' ),
'search_panel_field1' => array( 'field' => 'created',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'subject',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field3' => array( 'field' => 'statusid',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field4' => array( 'field' => 'priorityid',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field5' => array( 'field' => 'categoryid',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'folderid',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'ticketemail',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'assignedid',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'More_button' => array( 'type' => 'custom_button',
'eventId' => 'More_button',
'label' => array( 'text' => 'More',
'type' => 0 ),
'icon' => array( 'glyph' => 'cog' ) ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'filter_panel_field' => array( 'field' => 'statusid',
'type' => 'filter_panel_field' ),
'search_panel_field9' => array( 'field' => 'client_status',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'folder_select' => array( 'eventId' => 'folder_list',
'label' => array( 'text' => 'folder_list',
'type' => 0 ),
'type' => 'snippet' ),
'hd_tickets_context_menu' => array( 'eventId' => 'hd_tickets_context_menu',
'label' => array( 'text' => 'hd_tickets_context_menu',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin:0px;
}
' ),
'pupup_menus' => array( 'eventId' => 'pupup_menus',
'label' => array( 'text' => 'pupup menus',
'type' => 0 ),
'type' => 'snippet',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin:0px;
}
' ),
'grid_field' => array( 'field' => 'updated',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'updated' ),
'snippet' => array( 'eventId' => 'online_users',
'label' => array( 'text' => 'online_users',
'type' => 0 ),
'type' => 'snippet' ),
'action_info' => array( 'eventId' => 'action_info',
'label' => array( 'text' => 'action_info',
'type' => 0 ),
'type' => 'snippet' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array(  ) ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'responsiveGrid' => false,
'spreadsheetGrid' => false,
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>