<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'created',
'categoryid',
'priorityid',
'id',
'client_status',
'clientinfo',
'statusid',
'assignedid' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'created' => array( 'simple_grid_field1',
'simple_grid_field2' ),
'categoryid' => array( 'simple_grid_field7' ),
'priorityid' => array( 'simple_grid_field',
'simple_grid_field5' ),
'id' => array( 'grid_field',
'grid_field_label' ),
'client_status' => array( 'grid_field1',
'grid_field_label1' ),
'clientinfo' => array( 'grid_field2' ),
'statusid' => array( 'grid_field3',
'grid_field_label2' ),
'assignedid' => array( 'grid_field4',
'grid_field_label3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array(  ),
'above-grid' => array( 'inline_add' ),
'grid' => array( 'snippet2',
'grid_field_label',
'grid_field',
'simple_grid_field7',
'grid_field_label3',
'grid_field4',
'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field5',
'simple_grid_field',
'grid_field_label2',
'grid_field3',
'grid_field_label1',
'grid_field1',
'grid_field2',
'grid_inline_cancel' ),
'below-grid' => array(  ) ),
'formXtTags' => array( 'top' => array(  ),
'above-grid' => array( 'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'inline_add' => 'above-grid',
'snippet2' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'simple_grid_field7' => 'grid',
'grid_field_label3' => 'grid',
'grid_field4' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field' => 'grid',
'grid_field_label2' => 'grid',
'grid_field3' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field2' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'snippet2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'grid_field' => array( 'simple_grid_field1',
'simple_grid_field7',
'simple_grid_field',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field5',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3' ),
'snippet' => array( 'snippet2' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'snippet2',
'grid_field_label',
'grid_field',
'simple_grid_field7',
'grid_field_label3',
'grid_field4',
'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field5',
'simple_grid_field',
'grid_field_label2',
'grid_field3',
'grid_field_label1',
'grid_field1',
'grid_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field',
'colspan' => 1 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field',
'colspan' => 1 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field',
'colspan' => 1 ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'snippet2',
'grid_field_label',
'grid_field',
'simple_grid_field7',
'grid_field_label3',
'grid_field4',
'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field5',
'simple_grid_field',
'grid_field_label2',
'grid_field3',
'grid_field_label1',
'grid_field1',
'grid_field2' ),
'align' => 'left',
'field' => 'id',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'simple_grid_field1' => array( 'field' => 'created',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'field' => 'categoryid',
'type' => 'grid_field',
'label' => array( 'field' => 'categoryid',
'table' => 'hd_tickets',
'type' => 3 ) ),
'simple_grid_field' => array( 'field' => 'priorityid',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'created',
'padding' => array( 'left' => '20px' ),
'bold' => true,
'label' => array( 'field' => 'created',
'table' => 'hd_tickets',
'type' => 3 ) ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'priorityid',
'padding' => array( 'left' => '20px' ),
'bold' => true,
'label' => array( 'field' => 'priorityid',
'table' => 'hd_tickets',
'type' => 3 ) ),
'grid_field' => array( 'field' => 'id',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'id',
'label' => array( 'field' => 'id',
'table' => 'hd_tickets',
'type' => 3 ),
'bold' => true ),
'grid_field1' => array( 'field' => 'client_status',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'client_status',
'bold' => true,
'padding' => array( 'left' => '20px' ),
'label' => array( 'field' => 'client_status',
'table' => 'hd_tickets',
'type' => 3 ) ),
'grid_field2' => array( 'field' => 'clientinfo',
'type' => 'grid_field' ),
'snippet2' => array( 'eventId' => 'back_to_tickets',
'label' => array( 'text' => 'back_to_tickets',
'type' => 0 ),
'type' => 'snippet' ),
'grid_field3' => array( 'field' => 'statusid',
'type' => 'grid_field',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  display:none;
}
' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'statusid',
'label' => array( 'field' => 'statusid',
'table' => 'hd_tickets',
'type' => 3 ),
'bold' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
 display:none;
}
' ),
'grid_field4' => array( 'field' => 'assignedid',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'assignedid',
'bold' => true,
'customCSS' => '/* Put  your custom CSS code here */

:host {
    padding-left: 20px;
}
' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>