<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'timeperiod',
'findusers',
'soundenable',
'videoenable',
'soundpath',
'Z_Token',
'timezone',
'saveInCloud' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'timeperiod' => array( 'integrated_edit_field',
'edit_field_label' ),
'findusers' => array( 'integrated_edit_field1',
'edit_field_label1' ),
'soundenable' => array( 'integrated_edit_field3',
'edit_field_label3' ),
'videoenable' => array( 'integrated_edit_field4',
'edit_field_label4' ),
'soundpath' => array( 'sound_label',
'sound_field' ),
'Z_Token' => array( 'Zoom_field1' ),
'timezone' => array( 'setvideo_field3',
'setvideo_label3' ),
'saveInCloud' => array( 'setvideo_label2',
'setvideo_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_close' ),
'supertop' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'edit_field_label',
'edit_field_label1',
'integrated_edit_field',
'integrated_edit_field1' ),
'section1' => array( 'sound_label',
'sound_field',
'sound_button',
'edit_field_label3',
'integrated_edit_field3' ),
'section2' => array( 'edit_field_label4',
'integrated_edit_field4',
'setvideo_label3',
'setvideo_field3',
'setvideo_label2',
'setvideo_field2',
'Zoom_text2',
'Zoom_field1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ),
'below-grid' => array( 'save_edit',
'close_button' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_close' => 'below-grid',
'expand_menu_button' => 'supertop',
'expand_menu_button1' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'tabs' => 'grid',
'edit_field_label' => 'section',
'edit_field_label1' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field1' => 'section',
'sound_label' => 'section1',
'sound_field' => 'section1',
'sound_button' => 'section1',
'edit_field_label3' => 'section1',
'integrated_edit_field3' => 'section1',
'edit_field_label4' => 'section2',
'integrated_edit_field4' => 'section2',
'setvideo_label3' => 'section2',
'setvideo_field3' => 'section2',
'setvideo_label2' => 'section2',
'setvideo_field2' => 'section2',
'Zoom_text2' => 'section2',
'Zoom_field1' => 'section2' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c1' ),
'edit_field_label1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c' ),
'sound_label' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'sound_field' => array( 'location' => 'section1',
'cellId' => 'c' ),
'sound_button' => array( 'location' => 'section1',
'cellId' => 'c' ),
'edit_field_label3' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'edit_field_label4' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c' ),
'setvideo_label3' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'setvideo_field3' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'setvideo_label2' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'setvideo_field2' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'Zoom_text2' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'Zoom_field1' => array( 'location' => 'section2',
'cellId' => 'c7' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_menu_button1' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_close' => array( 'edit_close' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field4',
'sound_field',
'setvideo_field3',
'setvideo_field2' ),
'menu' => array( 'menu' ),
'expand_menu_button' => array( 'expand_menu_button',
'expand_menu_button1' ),
'collapse_button' => array( 'collapse_button' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label3',
'edit_field_label4',
'sound_label',
'setvideo_label3',
'setvideo_label2' ),
'logo' => array( 'logo1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'custom_button' => array( 'sound_button' ),
'text' => array( 'Zoom_text2' ),
'integrated_edit_field' => array( 'Zoom_field1' ),
'tabs' => array( 'tabs' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'timeperiod_fieldblock',
'findusers_fieldblock' ),
'items' => array( 'edit_field_label',
'edit_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'soundpath_fieldblock' ),
'items' => array( 'sound_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'soundenable_fieldblock' ),
'items' => array( 'edit_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'videoenable_fieldblock' ),
'items' => array( 'edit_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'Zoom_text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'Zoom_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'saveInCloud_fieldblock' ),
'items' => array( 'setvideo_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'setvideo_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'timezone_fieldblock' ),
'items' => array( 'setvideo_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'setvideo_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'New_Button1' ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'New_Button1' ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'expand_menu_button1',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c6' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label',
'edit_field_label1' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'sound_label' ),
'customCSS' => '[data-itemid="sound_field"] a{
    display:none;
}' ),
'c' => array( 'model' => 'c1',
'items' => array( 'sound_field',
'sound_button' ),
'orientation' => 'horizontal' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'edit_field_label3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_field_label4' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'setvideo_label3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'setvideo_field3' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'setvideo_label2' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'setvideo_field2' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'Zoom_text2' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'Zoom_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header',
'title' => array( 'page' => 'edit',
'table' => 'chat_settings',
'type' => 7 ) ),
'edit_message' => array( 'type' => 'edit_message',
'customCSS' => '/* Put  your custom CSS code here */

:host {
  color: red;
}
' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_close' => array( 'type' => 'edit_close' ),
'integrated_edit_field' => array( 'field' => 'timeperiod',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'width' => '80px',
'nowrap' => true,
'updateOnEdit' => false ),
'menu' => array( 'type' => 'menu' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'timeperiod',
'separated' => true,
'nowrap' => true ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button1' => array( 'type' => 'expand_menu_button' ),
'integrated_edit_field1' => array( 'field' => 'findusers',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false,
'customCSS' => '
',
'nowrap' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'findusers',
'separated' => true,
'label' => array( 'field' => 'findusers',
'table' => 'chat_settings',
'type' => 3 ),
'nowrap' => true,
'padding' => array( 'top' => '17px' ) ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'integrated_edit_field3' => array( 'field' => 'soundenable',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'videoenable',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'soundenable',
'separated' => true,
'label' => array( 'field' => 'soundenable',
'table' => 'chat_settings',
'type' => 3 ) ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'videoenable',
'separated' => true,
'label' => array( 'field' => 'videoenable',
'table' => 'chat_settings',
'type' => 3 ) ),
'sound_label' => array( 'type' => 'edit_field_label',
'field' => 'soundpath',
'separated' => true,
'label' => array( 'field' => 'soundpath',
'table' => 'chat_settings',
'type' => 3 ) ),
'sound_button' => array( 'eventId' => 'New_Button1',
'label' => array( 'text' => '',
'type' => 0 ),
'type' => 'custom_button',
'icon' => array( 'glyph' => 'volume-up' ) ),
'sound_field' => array( 'field' => 'soundpath',
'type' => 'edit_field',
'orientation' => 1,
'joined' => false,
'separated' => true,
'updateOnEdit' => false,
'customCSS' => '/* Put  your custom CSS code here */

:host {
  margin-top:-27px!important;
}
',
'width' => '350px' ),
'Zoom_text2' => array( 'type' => 'text',
'label' => array( 'text' => '<p>1. Sign in to&nbsp;<a href="https://marketplace.zoom.us/user/build" target="_blank" rel="noopener noreferrer"><u>https://marketplace.zoom.us/user/build</u></a></p><p>2. Proceed to create a JWT app at&nbsp;<a href="https://marketplace.zoom.us/develop/create" target="_blank" rel="noopener noreferrer"><u>https://marketplace.zoom.us/develop/create</u></a></p><p>3. Copy the API&nbsp;token you see there and paste it to API&nbsp;token field below.</p>',
'type' => 0 ),
'editedByRte' => true ),
'Zoom_field1' => array( 'field' => 'Z_Token',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'setvideo_field3' => array( 'field' => 'timezone',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false,
'width' => '300px' ),
'setvideo_label3' => array( 'type' => 'edit_field_label',
'field' => 'timezone',
'separated' => true ),
'setvideo_label2' => array( 'type' => 'edit_field_label',
'field' => 'saveInCloud',
'separated' => true ),
'setvideo_field2' => array( 'field' => 'saveInCloud',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'General',
'type' => 0 ),
array( 'text' => 'Audio',
'type' => 0 ),
array( 'text' => 'Video',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>